/**
 * College logos, and the reason this is off by default.
 *
 * ## This is trademark, not copyright
 *
 * There is no such thing as a freely-licensed university logo. Photographs can
 * be CC0; a logo cannot, because it is a trademark rather than merely a
 * copyrighted image. Wikipedia's university logos are uploaded under *non-free*
 * fair-use rationales that do not extend to a product like this one.
 *
 * So unlike `school-photos.ts`, there is no licence to record. The question is
 * whether the use needs permission at all. Using a mark purely to *identify*
 * an institution, at identification size, without implying endorsement, is the
 * nominative-use argument that college-search products generally rely on.
 *
 * **This is not legal advice, and nothing here establishes that the use is
 * permitted.** Most universities' brand guidelines prohibit third-party use
 * outright, and admissions-adjacent products are the category they police most
 * actively. That is why the default is off.
 *
 * ## What makes this safer than the photo problem
 *
 * Identity comes free. The hard part with a campus photograph was proving the
 * image actually shows the campus it claims to. A logo fetched from the
 * university's *own domain* — derived from the official admissions URL this
 * repo already cites for that school's prompts — is that university's mark by
 * construction. There is no misattribution risk.
 *
 * ## How it is kept from shipping by accident
 *
 * Three independent gates, any one of which is enough:
 *
 * 1. `SHOW_SCHOOL_LOGOS` is unset in production, so `logosEnabled()` is false
 *    and `SchoolMark` renders generated initials.
 * 2. `SCHOOL_LOGOS` is empty in the committed source. `scripts/fetch-school-logos.mts`
 *    rewrites this array locally, which shows up as an uncommitted change —
 *    a visible decision rather than a silent one.
 * 3. `public/school-logos/` is gitignored, so the image files are never
 *    committed and never reach a deployment even if the flag were set.
 *
 * @see docs/school-logos.md
 */

/**
 * Schools that have asked not to be shown, or that a human has decided not to
 * show. The fetch script skips these, and `logoForSchool` refuses them even if
 * a stale entry survives in the registry — a removal request should not depend
 * on remembering to re-run a script.
 */
export const DECLINED_SCHOOLS: readonly string[] = [];

/**
 * Schools where a human looked at every candidate and found none acceptable.
 *
 * Distinct from DECLINED_SCHOOLS, which is about permission. This is about
 * quality: the search found something, a person looked at it, and it was wrong.
 *
 * Currently empty. Santa Barbara lived here while the only square candidate
 * its own site offered was an external-link arrow; promoting Wikipedia
 * infoboxes to a first-class source turned up a real 646px UCSB seal, so the
 * exclusion was no longer the right answer.
 */
export const NO_USABLE_LOGO: readonly string[] = [];

export type SchoolLogo = {
  /** Must match the school name the app renders. */
  school: string;
  /** Path under public/. Always a normalised 512x512 PNG. */
  file: string;
  /**
   * Whether the asset came from the institution itself or from a third party.
   *
   * "official" means it was found on a domain belonging to the university.
   * "secondary" means a reputable third party (Wikidata/Wikimedia Commons),
   * which is weaker on both identity and rights and is reported separately.
   */
  origin: "official" | "secondary";
  /** The page the asset was found on. */
  declaredOn: string;
  /** The absolute URL the bytes came from. */
  sourceUrl: string;
  /** Which strategy found it, for the record: "declared icon", "header logo", ... */
  via: string;
  /** The university domain this was attributed to. */
  domain: string;
  /**
   * True when the source was a designed app icon whose colour field runs to
   * the edge. Those keep their field; everything else is trimmed to its real
   * content and re-inset, so perceived size stays consistent.
   */
  fullBleed: boolean;
  /** Aspect ratio of the real content, after trimming. */
  aspect: number;
  /** Long edge of the real content in source pixels, before normalising. */
  contentPx: number;
  /** e.g. "png", "svg", "png embedded in ico". */
  sourceFormat: string;
  /** Source dimensions before normalising, e.g. "229x256". */
  sourceSize: string;
  /** sha256 of the normalised bytes. */
  sha256: string;
  /** ISO date the asset was retrieved. */
  retrievedAt: string;
  /**
   * Per-school rendering escape hatch, for the rare mark that the automatic
   * treatment gets wrong. `scale` multiplies the content size; `background`
   * overrides the disc colour.
   */
  render?: { scale?: number; background?: string };
  /** Anything a human should know, including doubts. */
  note?: string;
};

/**
 * Empty in the committed source. Populated locally by
 * `npm run logos:fetch`; see the gates above.
 */
export const SCHOOL_LOGOS: readonly SchoolLogo[] = [
  {
    school: "Amherst College",
    file: "/school-logos/amherst-college.png",
    origin: "official",
    declaredOn: "https://www.amherst.edu/",
    sourceUrl: "https://www.amherst.edu/themes/custom/amherst_new/favicon.ico",
    via: "declared icon",
    domain: "amherst.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 256,
    sourceFormat: "png embedded in ico",
    sourceSize: "256x256",
    sha256: "867369c76839c45ede744d0f723874d1e8312daf1e233f5fce68a5c4085097d8",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Arizona State University",
    file: "/school-logos/arizona-state-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Arizona_State_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/Arizona_State_University_seal.svg/250px-Arizona_State_University_seal.svg.png",
    via: "wikimedia",
    domain: "asu.edu",
    fullBleed: false,
    aspect: 1.004,
    contentPx: 245,
    sourceFormat: "png",
    sourceSize: "250x250",
    sha256: "ae6e55fc6c96f4deba327075e564f4af8616a9b9bbc23ae568898e99f0981691",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Arizona_State_University_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Boston College",
    file: "/school-logos/boston-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Boston_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/00/Boston_College_seal.svg/330px-Boston_College_seal.svg.png",
    via: "wikimedia",
    domain: "bc.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 330,
    sourceFormat: "png",
    sourceSize: "330x330",
    sha256: "561a7bf762373250612a342659cbb757473e6420ecd23c4a603982124a0db9d9",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Boston_College_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Boston University",
    file: "/school-logos/boston-university.png",
    origin: "official",
    declaredOn: "https://bu.edu/",
    sourceUrl: "https://bu.edu/apple-touch-icon.png",
    via: "conventional path",
    domain: "bu.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 180,
    sourceFormat: "png",
    sourceSize: "180x180",
    sha256: "bfc9d65c38eefa3c620fddb7a421adae3a867b960111fcddc3cf6bf1170af327",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Bowdoin College",
    file: "/school-logos/bowdoin-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Bowdoin_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Formal_Seal_of_Bowdoin_College%2C_Brunswick%2C_ME%2C_USA.svg/250px-Formal_Seal_of_Bowdoin_College%2C_Brunswick%2C_ME%2C_USA.svg.png",
    via: "wikimedia",
    domain: "bowdoin.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 250,
    sourceFormat: "png",
    sourceSize: "250x250",
    sha256: "cd481da7cb560d5098affe317f67ecaefbdbffe919c4b9dc23951c3bd28cd8fb",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Formal_Seal_of_Bowdoin_College,_Brunswick,_ME,_USA.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Brandeis University",
    file: "/school-logos/brandeis-university.png",
    origin: "official",
    declaredOn: "https://www.brandeis.edu/",
    sourceUrl: "https://www.brandeis.edu/_files/favicons/favicon-196x196.png",
    via: "declared icon",
    domain: "brandeis.edu",
    fullBleed: false,
    aspect: 0.789,
    contentPx: 180,
    sourceFormat: "png",
    sourceSize: "196x196",
    sha256: "9d217983b31786588a18ceb992adf6ec88ffecdf5d1e18e949cc1e97b5ce3ecd",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Brown University",
    file: "/school-logos/brown-university.png",
    origin: "secondary",
    declaredOn: "https://commons.wikimedia.org/wiki/File:Brown_seal.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Brown%20seal.svg?width=640",
    via: "wikimedia",
    domain: "brown.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 959,
    sourceFormat: "png",
    sourceSize: "960x960",
    sha256: "6ac36f675ff00c78754bb9665b4a027b608aacf4988b95340514c27cf6fc0cf5",
    retrievedAt: "2026-08-29",
    note: "Wikidata Q49114 P158 (seal): Brown seal.svg",
  },
  {
    school: "Bucknell University",
    file: "/school-logos/bucknell-university.png",
    origin: "official",
    declaredOn: "https://www.bucknell.edu/themes/custom/bucknell/assets/dist/favicon/site.webmanifest",
    sourceUrl: "https://www.bucknell.edu/themes/custom/bucknell/assets/dist/favicon/android-chrome-512x512.png",
    via: "manifest icon",
    domain: "bucknell.edu",
    fullBleed: false,
    aspect: 0.804,
    contentPx: 509,
    sourceFormat: "png",
    sourceSize: "512x512",
    sha256: "ec80a422ef57dd4ea1d82b066885ba0e0aabc422e6403e595a2e8d82a125a32f",
    retrievedAt: "2026-08-29",
  },
  {
    school: "California Institute of Technology",
    file: "/school-logos/california-institute-of-technology.png",
    origin: "official",
    declaredOn: "https://www.caltech.edu/",
    sourceUrl: "https://www.caltech.edu/static/core/img/favicon-192.png?v=7.9.9",
    via: "declared icon",
    domain: "caltech.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 192,
    sourceFormat: "png",
    sourceSize: "192x192",
    sha256: "980af12f783dffb24759fa321232e6f3345708fd9f8065f04f053d0d57eb7391",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Carleton College",
    file: "/school-logos/carleton-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Carleton_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/4/41/Combined_logo_and_seal_for_Carleton_College.png",
    via: "wikimedia",
    domain: "carleton.edu",
    fullBleed: false,
    aspect: 2.004,
    contentPx: 447,
    sourceFormat: "png",
    sourceSize: "447x223",
    sha256: "b721a1130084762b0e744a2a3740f0047917268f8415542424eab927927362d8",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Combined_logo_and_seal_for_Carleton_College.png - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Carnegie Mellon University",
    file: "/school-logos/carnegie-mellon-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Carnegie_Mellon_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/bb/Carnegie_Mellon_University_seal.svg/330px-Carnegie_Mellon_University_seal.svg.png",
    via: "wikimedia",
    domain: "cmu.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 330,
    sourceFormat: "png",
    sourceSize: "330x330",
    sha256: "76bd64c833b08054a1985a36edc1d6099d875fcc7679f1421da07eb5bc711b4e",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Carnegie_Mellon_University_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Case Western Reserve University",
    file: "/school-logos/case-western-reserve-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Case_Western_Reserve_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/08/Case_Western_Reserve_University_seal.svg/330px-Case_Western_Reserve_University_seal.svg.png",
    via: "wikimedia",
    domain: "case.edu",
    fullBleed: false,
    aspect: 1.038,
    contentPx: 330,
    sourceFormat: "png",
    sourceSize: "330x318",
    sha256: "c87dbf741af78aa46b001547eb990bc0a821fce7bddaa7376e5d55ca32c496ce",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Case_Western_Reserve_University_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Claremont McKenna College",
    file: "/school-logos/claremont-mckenna-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Claremont_McKenna_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/7/73/Claremont_McKenna_College_Seal.svg/250px-Claremont_McKenna_College_Seal.svg.png",
    via: "wikimedia",
    domain: "cmc.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 250,
    sourceFormat: "png",
    sourceSize: "250x250",
    sha256: "86fc963d1b7e1daeb9a27b1c74a90890271ea6f77f6ed9cd8faa7f2f704b310d",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Claremont_McKenna_College_Seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Colby College",
    file: "/school-logos/colby-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Colby_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Colby_college_maine_seal.svg/250px-Colby_college_maine_seal.svg.png",
    via: "wikimedia",
    domain: "colby.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 249,
    sourceFormat: "png",
    sourceSize: "250x251",
    sha256: "958903acb278520ed01681696e3618358b9c06eeaf25cf274649ed41d6e86a7d",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Colby_college_maine_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Colgate University",
    file: "/school-logos/colgate-university.png",
    origin: "official",
    declaredOn: "https://www.colgate.edu/",
    sourceUrl: "https://www.colgate.edu/themes/custom/colgate/favicons/favicon-196x196.png",
    via: "declared icon",
    domain: "colgate.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 196,
    sourceFormat: "png",
    sourceSize: "196x196",
    sha256: "77141e40326bb44c22412a2b11bdb86a744bdba15ad6b61ac929fa524d91b4e0",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Colorado College",
    file: "/school-logos/colorado-college.png",
    origin: "official",
    declaredOn: "https://www.coloradocollege.edu/",
    sourceUrl: "https://www.coloradocollege.edu/home/favicon.png",
    via: "declared icon",
    domain: "coloradocollege.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 256,
    sourceFormat: "png",
    sourceSize: "256x256",
    sha256: "22fbdb778be28e7a89b858b6e19a42a089de8e173b23338e957e5f88b287938c",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Columbia University",
    file: "/school-logos/columbia-university.png",
    origin: "official",
    declaredOn: "https://undergrad.admissions.columbia.edu/",
    sourceUrl: "https://undergrad.admissions.columbia.edu/themes/custom/cua/favicoadmissions128.png",
    via: "declared icon",
    domain: "columbia.edu",
    fullBleed: false,
    aspect: 1.174,
    contentPx: 525,
    sourceFormat: "png",
    sourceSize: "534x534",
    sha256: "e724b91d8c43035087995de92dbc83f2e5d5f00221c04828ee63bc6d291b1cc7",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Cornell University",
    file: "/school-logos/cornell-university.png",
    origin: "official",
    declaredOn: "https://www.cornell.edu/site.webmanifest",
    sourceUrl: "https://www.cornell.edu/web-app-manifest-512x512.png",
    via: "manifest icon",
    domain: "cornell.edu",
    fullBleed: false,
    aspect: 0.996,
    contentPx: 494,
    sourceFormat: "png",
    sourceSize: "512x512",
    sha256: "8fa137d3dd77ab7b4da0777f3650c2b74c5d7164873517498f2e41e1dbfa8bcc",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Dartmouth College",
    file: "/school-logos/dartmouth-college.png",
    origin: "official",
    declaredOn: "https://home.dartmouth.edu/",
    sourceUrl: "https://home.dartmouth.edu/themes/custom/darthome_2021/dist/images/touch-icons/apple-touch-icon-ipad-retina-152x152.png",
    via: "declared icon",
    domain: "dartmouth.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 152,
    sourceFormat: "png",
    sourceSize: "152x152",
    sha256: "6c3fa2c8ced82373a12741ef25053e4715f12bf7beb32a9275c2450e5bb3aa44",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Davidson College",
    file: "/school-logos/davidson-college.png",
    origin: "official",
    declaredOn: "https://davidson.edu/",
    sourceUrl: "https://davidson.edu/apple-touch-icon.png",
    via: "conventional path",
    domain: "davidson.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 180,
    sourceFormat: "png",
    sourceSize: "180x180",
    sha256: "d9a4c708990e9b8ca59d9d3afd5b407ddf0830183efa4f9db1804949a890bd2f",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Duke University",
    file: "/school-logos/duke-university.png",
    origin: "official",
    declaredOn: "https://www.duke.edu/",
    sourceUrl: "https://www.duke.edu/wp-content/uploads/2025/12/cropped-dfavicon-1-192x192.png",
    via: "declared icon",
    domain: "duke.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 192,
    sourceFormat: "png",
    sourceSize: "192x192",
    sha256: "9738a9a44aa13e10b176a434b57c1f99db47650954687e70ac8a0c9ece130fa7",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Emory University",
    file: "/school-logos/emory-university.png",
    origin: "official",
    declaredOn: "https://www.emory.edu/",
    sourceUrl: "https://www.emory.edu/themes/emory/favicon.svg",
    via: "declared icon",
    domain: "emory.edu",
    fullBleed: false,
    aspect: 0.915,
    contentPx: 2322,
    sourceFormat: "svg",
    sourceSize: "2400x2400",
    sha256: "2be68fe7108f865553096211a463781e639a6cd5373794883b4d318b1450a558",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Florida State University",
    file: "/school-logos/florida-state-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Florida_State_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Florida_State_University_seal.svg/250px-Florida_State_University_seal.svg.png",
    via: "wikimedia",
    domain: "fsu.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 247,
    sourceFormat: "png",
    sourceSize: "250x250",
    sha256: "6ebe696734ac99274535e4951c99549be9a5c4666489321c09cc942b930de1f8",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Florida_State_University_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "George Washington University",
    file: "/school-logos/george-washington-university.png",
    origin: "official",
    declaredOn: "https://www.gwu.edu/",
    sourceUrl: "https://www.gwu.edu/sites/g/files/zaxdzs7131/files/header_block/gw_primary_logo.png",
    via: "header logo",
    domain: "gwu.edu",
    fullBleed: false,
    aspect: 1.339,
    contentPx: 600,
    sourceFormat: "png",
    sourceSize: "600x457",
    sha256: "f0ce196ad7c8bd8e7871cb726ae375f088aace7b2c7c8bbf4d99f44f3ef6cdfc",
    retrievedAt: "2026-08-29",
    render: {"background":"#7a322d"},
    note: "GW Monogram | light mark: rendered on a dark plate",
  },
  {
    school: "Georgetown University",
    file: "/school-logos/georgetown-university.png",
    origin: "official",
    declaredOn: "https://www.georgetown.edu/",
    sourceUrl: "https://www.georgetown.edu/wp-content/uploads/fbrfg/apple-touch-icon.png",
    via: "declared icon",
    domain: "georgetown.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 180,
    sourceFormat: "png",
    sourceSize: "180x180",
    sha256: "8e13d7b5d6d2448a86e8b5677de439bb2f175228ef8d970906896cb26fd56996",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Georgia Institute of Technology",
    file: "/school-logos/georgia-institute-of-technology.png",
    origin: "secondary",
    declaredOn: "https://commons.wikimedia.org/wiki/File:Georgia_Tech_seal.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Georgia%20Tech%20seal.svg?width=640",
    via: "wikimedia",
    domain: "gatech.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 960,
    sourceFormat: "png",
    sourceSize: "960x960",
    sha256: "32b13f896b2be7c61ed6d4105556728d83344cb118c5edb52166df57a23ac67d",
    retrievedAt: "2026-08-29",
    note: "Wikidata Q864855 P154 (logo): Georgia Tech seal.svg",
  },
  {
    school: "Grinnell College",
    file: "/school-logos/grinnell-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Grinnell_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/bc/Grinnell_College_seal.svg/500px-Grinnell_College_seal.svg.png",
    via: "wikimedia",
    domain: "grinnell.edu",
    fullBleed: false,
    aspect: 1.202,
    contentPx: 500,
    sourceFormat: "png",
    sourceSize: "500x416",
    sha256: "f413fe61fa4fa7ea8d12d7b19248d16bb6cdf71726de5556fe60dc74f21c80ba",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Grinnell_College_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Hamilton College",
    file: "/school-logos/hamilton-college.png",
    origin: "official",
    declaredOn: "https://www.hamilton.edu/v22/favicons/site.webmanifest?20251212",
    sourceUrl: "https://www.hamilton.edu/assets/images/favicons/android-chrome-192x192.png",
    via: "manifest icon",
    domain: "hamilton.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 192,
    sourceFormat: "png",
    sourceSize: "192x192",
    sha256: "09d0c0e84473be3aa183b5d2d6ae8dce8fa1133d8791c0d31ad52441062fa27c",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Harvard University",
    file: "/school-logos/harvard-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Harvard_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Harvard_University_coat_of_arms.svg/330px-Harvard_University_coat_of_arms.svg.png",
    via: "wikimedia",
    domain: "harvard.edu",
    fullBleed: false,
    aspect: 1.028,
    contentPx: 328,
    sourceFormat: "png",
    sourceSize: "330x321",
    sha256: "93ae16171a7af4a28d70d40e2229a93bd76720f71a5fe4c76ddc6b23ac0d6c75",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Harvard_University_coat_of_arms.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Harvey Mudd College",
    file: "/school-logos/harvey-mudd-college.png",
    origin: "official",
    declaredOn: "https://www.hmc.edu/wp-content/themes/mudd-2021/favicons/manifest.json",
    sourceUrl: "https://www.hmc.edu/wp-content/themes/mudd-2021/favicons/android-chrome-256x256.png",
    via: "manifest icon",
    domain: "hmc.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 256,
    sourceFormat: "png",
    sourceSize: "256x256",
    sha256: "51758d3a96f181ded1ba1508da7e27e2c6747af517e56fb676f629377f55bae9",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Haverford College",
    file: "/school-logos/haverford-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Haverford_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Formal_Seal_of_Haverford_College%2C_Haverford_Township%2C_PA%2C_USA.svg/250px-Formal_Seal_of_Haverford_College%2C_Haverford_Township%2C_PA%2C_USA.svg.png",
    via: "wikimedia",
    domain: "haverford.edu",
    fullBleed: false,
    aspect: 0.984,
    contentPx: 248,
    sourceFormat: "png",
    sourceSize: "250x250",
    sha256: "95e94f6f1affe3c4396cabfe4080ab275286519327fd432310dfd84b54d92808",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Formal_Seal_of_Haverford_College,_Haverford_Township,_PA,_USA.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Indiana University Bloomington",
    file: "/school-logos/indiana-university-bloomington.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Indiana_University_Bloomington",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Indiana_University_seal.svg/250px-Indiana_University_seal.svg.png",
    via: "wikimedia",
    domain: "iu.edu",
    fullBleed: false,
    aspect: 1.004,
    contentPx: 248,
    sourceFormat: "png",
    sourceSize: "250x250",
    sha256: "2f6e894a94d03108d2b491511d2eab5163c72a6c17ddf3497ddad4601cd9310b",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Indiana_University_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Johns Hopkins University",
    file: "/school-logos/johns-hopkins-university.png",
    origin: "official",
    declaredOn: "https://apply.jhu.edu/",
    sourceUrl: "https://apply.jhu.edu/wp-content/uploads/2022/11/cropped-cropped-favicon-194x194-1-192x192.png",
    via: "declared icon",
    domain: "jhu.edu",
    fullBleed: false,
    aspect: 0.94,
    contentPx: 182,
    sourceFormat: "png",
    sourceSize: "192x192",
    sha256: "9ff3336e1140ae12dab560fca02387b483b210d2aa3cb5f50015846d0409ed33",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Lehigh University",
    file: "/school-logos/lehigh-university.png",
    origin: "official",
    declaredOn: "https://www2.lehigh.edu/",
    sourceUrl: "https://www2.lehigh.edu/sites/www2/files/favicons/favicon192.png",
    via: "declared icon",
    domain: "lehigh.edu",
    fullBleed: false,
    aspect: 0.734,
    contentPx: 192,
    sourceFormat: "png",
    sourceSize: "192x192",
    sha256: "03f84498b448fa7d23de0fc94f69043995549e5d3a326e40b835f3943ee2f832",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Massachusetts Institute of Technology",
    file: "/school-logos/massachusetts-institute-of-technology.png",
    origin: "official",
    declaredOn: "https://mitadmissions.org/",
    sourceUrl: "https://mitadmissions.org/wp-content/themes/mit-admissions-theme/static/img/favicon/android-icon-192x192.png?v=1.3.8",
    via: "declared icon",
    domain: "mitadmissions.org",
    fullBleed: false,
    aspect: 1,
    contentPx: 192,
    sourceFormat: "png",
    sourceSize: "192x192",
    sha256: "d482f3c530f307830d3a56a0806f5bdc94a532da48b01f27b624b34dc955ede7",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Michigan State University",
    file: "/school-logos/michigan-state-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Michigan_State_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Michigan_State_University_seal.svg/250px-Michigan_State_University_seal.svg.png",
    via: "wikimedia",
    domain: "msu.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 250,
    sourceFormat: "png",
    sourceSize: "250x251",
    sha256: "8d54adb8262499405d221f2f1b1cdc1c4a4664aaf9820af4bf72a23e3d59bc82",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Michigan_State_University_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Middlebury College",
    file: "/school-logos/middlebury-college.png",
    origin: "official",
    declaredOn: "https://www.middlebury.edu/",
    sourceUrl: "https://www.middlebury.edu/themes/custom/middlebury_theme/images/midd-shield-white.svg",
    via: "header logo",
    domain: "middlebury.edu",
    fullBleed: false,
    aspect: 0.917,
    contentPx: 900,
    sourceFormat: "svg",
    sourceSize: "825x900",
    sha256: "086c1771dc23e81c347d27a5324b50739f2a60ec26d7876a88508ff299a00913",
    retrievedAt: "2026-08-29",
    render: {"background":"#7a322d"},
    note: "Logo for Middlebury | light mark: rendered on a dark plate",
  },
  {
    school: "New York University",
    file: "/school-logos/new-york-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/New_York_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/New_York_University_Seal.svg/250px-New_York_University_Seal.svg.png",
    via: "wikimedia",
    domain: "nyu.edu",
    fullBleed: false,
    aspect: 0.988,
    contentPx: 253,
    sourceFormat: "png",
    sourceSize: "250x254",
    sha256: "968b105881468f7df236bd45c58ecc9dbc5e9044b6e7c9474fbe495d799d2a9b",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: New_York_University_Seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "North Carolina State University",
    file: "/school-logos/north-carolina-state-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/North_Carolina_State_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/2/24/North_Carolina_State_University_seal.svg/250px-North_Carolina_State_University_seal.svg.png",
    via: "wikimedia",
    domain: "ncsu.edu",
    fullBleed: false,
    aspect: 0.988,
    contentPx: 251,
    sourceFormat: "png",
    sourceSize: "250x254",
    sha256: "15ba18cb87da80bd6e94b0623a0879331ea057786391ae5a6547f87723a42e09",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: North_Carolina_State_University_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Northeastern University",
    file: "/school-logos/northeastern-university.png",
    origin: "official",
    declaredOn: "https://www.northeastern.edu/",
    sourceUrl: "https://brand.northeastern.edu/global/assets/favicon/apple-touch-152x152.png?v=2",
    via: "declared icon",
    domain: "northeastern.edu",
    fullBleed: false,
    aspect: 1.303,
    contentPx: 129,
    sourceFormat: "png",
    sourceSize: "152x152",
    sha256: "f5aaf3a568c5d0d3f70d6d579f6de2241a260e1c92d4509d48ce413ae656af78",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Northwestern University",
    file: "/school-logos/northwestern-university.png",
    origin: "official",
    declaredOn: "https://www.northwestern.edu/",
    sourceUrl: "https://common.northwestern.edu/v8/icons/favicon-180.png",
    via: "declared icon",
    domain: "northwestern.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 180,
    sourceFormat: "png",
    sourceSize: "180x180",
    sha256: "d32e3a2957e188901b3ed278a5ee6084df0b2eb1f531b100f6019aa2307f2b22",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Oberlin College",
    file: "/school-logos/oberlin-college.png",
    origin: "official",
    declaredOn: "https://www.oberlin.edu/",
    sourceUrl: "https://www.oberlin.edu/themes/custom/oberlin/apple-touch-icon.png",
    via: "declared icon",
    domain: "oberlin.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 180,
    sourceFormat: "png",
    sourceSize: "180x180",
    sha256: "97d36e03fdded738abaa359a4d79cb7ae7b3485a19a10b68a01cf768c89fb41a",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Ohio State University",
    file: "/school-logos/ohio-state-university.png",
    origin: "official",
    declaredOn: "https://osu.edu/",
    sourceUrl: "https://osu.edu/apple-touch-icon.png",
    via: "conventional path",
    domain: "osu.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 512,
    sourceFormat: "png",
    sourceSize: "512x512",
    sha256: "e4982f00b182c6b786b5fe33ee94a7cb8be9e0f24db43deaae8f777253408637",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Pennsylvania State University",
    file: "/school-logos/pennsylvania-state-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Pennsylvania_State_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Pennsylvania_State_University_seal.svg/330px-Pennsylvania_State_University_seal.svg.png",
    via: "wikimedia",
    domain: "psu.edu",
    fullBleed: false,
    aspect: 1.041,
    contentPx: 327,
    sourceFormat: "png",
    sourceSize: "330x318",
    sha256: "0c620bdb79006639914e9da98cb87a72e2466372aa0af7503cb374ec6dcfdfa5",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Pennsylvania_State_University_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Pitzer College",
    file: "/school-logos/pitzer-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Pitzer_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/Pitzer_College_seal%2C_cali.svg/330px-Pitzer_College_seal%2C_cali.svg.png",
    via: "wikimedia",
    domain: "pitzer.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 330,
    sourceFormat: "png",
    sourceSize: "330x330",
    sha256: "57ce415fa1b209d0cf39a353f4398b305b1c2fec3889234edad82dfcade89378",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Pitzer_College_seal,_cali.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Pomona College",
    file: "/school-logos/pomona-college.png",
    origin: "secondary",
    declaredOn: "https://commons.wikimedia.org/wiki/File:Pomona_College_1891_seal.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Pomona%20College%201891%20seal.jpg",
    via: "wikimedia",
    domain: "pomona.edu",
    fullBleed: false,
    aspect: 0.623,
    contentPx: 1079,
    sourceFormat: "jpeg",
    sourceSize: "827x1200",
    sha256: "e8927b102c54c8820d70dc963e0ec35e806a971883b83fcbc383b22057cec4cc",
    retrievedAt: "2026-08-29",
    note: "Wikidata Q7227384 P158 (seal): Pomona College 1891 seal.jpg",
  },
  {
    school: "Princeton University",
    file: "/school-logos/princeton-university.png",
    origin: "official",
    declaredOn: "https://www.princeton.edu/themes/custom/hobbes/icons/manifest.json",
    sourceUrl: "https://www.princeton.edu/themes/custom/hobbes/icons/android-chrome-512x512.png",
    via: "manifest icon",
    domain: "princeton.edu",
    fullBleed: false,
    aspect: 0.785,
    contentPx: 475,
    sourceFormat: "png",
    sourceSize: "512x512",
    sha256: "5178aead16187f031cc9a61a99fc6a054932b9a205858b8e34ac49625ce5d5b6",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Purdue University",
    file: "/school-logos/purdue-university.png",
    origin: "official",
    declaredOn: "https://purdue.edu/",
    sourceUrl: "https://www.purdue.edu/home/wp-content/mu-plugins/boilerup-wp/favicon/favicon-96x96.png",
    via: "declared icon",
    domain: "purdue.edu",
    fullBleed: false,
    aspect: 1.86,
    contentPx: 199,
    sourceFormat: "png",
    sourceSize: "200x200",
    sha256: "face29524a08db4efb5ef03e1149dc742d27220adeb6a67ff5037a14309cb027",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Reed College",
    file: "/school-logos/reed-college.png",
    origin: "official",
    declaredOn: "https://www.reed.edu/",
    sourceUrl: "https://www.reed.edu/global_assets/images/logo/griffin-2016/ffffff.svg",
    via: "header logo",
    domain: "reed.edu",
    fullBleed: false,
    aspect: 1.001,
    contentPx: 1480,
    sourceFormat: "svg",
    sourceSize: "1480x1478",
    sha256: "f49c261b2443606db26c8a217410c25b264b7e93bd6430fa76ba4a91fd637d80",
    retrievedAt: "2026-08-29",
    render: {"background":"#2b5578"},
    note: "Reed College | light mark: rendered on a dark plate",
  },
  {
    school: "Rice University",
    file: "/school-logos/rice-university.png",
    origin: "official",
    declaredOn: "https://www.rice.edu/",
    sourceUrl: "https://www.rice.edu/sites/g/files/bxs2566/files/favicon.ico",
    via: "declared icon",
    domain: "rice.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 128,
    sourceFormat: "bmp ico via sips",
    sourceSize: "128x128",
    sha256: "ae59487553fc7e7bcb162050010578154c484bdcc1da2f206f88d13f53968249",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Rutgers University",
    file: "/school-logos/rutgers-university.png",
    origin: "official",
    declaredOn: "https://www.rutgers.edu/",
    sourceUrl: "https://www.rutgers.edu/themes/custom/rutgers_edu/favicon.ico",
    via: "declared icon",
    domain: "rutgers.edu",
    fullBleed: false,
    aspect: 1.128,
    contentPx: 256,
    sourceFormat: "png embedded in ico",
    sourceSize: "256x256",
    sha256: "bfa3ff87a619652e17569c3dea150c47edd6245dc26c6382be1588144661b7c3",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Scripps College",
    file: "/school-logos/scripps-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Scripps_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2c/Scripps_College_seal.svg/250px-Scripps_College_seal.svg.png",
    via: "wikimedia",
    domain: "scrippscollege.edu",
    fullBleed: false,
    aspect: 0.98,
    contentPx: 255,
    sourceFormat: "png",
    sourceSize: "250x255",
    sha256: "35f7cb7ef68b95cfff35e49f44f33f8c651be2375ba43e548a9c58db788a366e",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Scripps_College_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Smith College",
    file: "/school-logos/smith-college.png",
    origin: "official",
    declaredOn: "https://www.smith.edu/",
    sourceUrl: "https://www.smith.edu/sites/default/files/favicons/favicon.svg?tkft5c",
    via: "declared icon",
    domain: "smith.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 400,
    sourceFormat: "svg",
    sourceSize: "400x400",
    sha256: "8aca842b046a6efbac45cafa23b77083cb6449fcba978932c81c9a13bd72256a",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Stanford University",
    file: "/school-logos/stanford-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Stanford_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Seal_of_Leland_Stanford_Junior_University.svg/960px-Seal_of_Leland_Stanford_Junior_University.svg.png",
    via: "wikimedia",
    domain: "stanford.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 960,
    sourceFormat: "png",
    sourceSize: "960x960",
    sha256: "c94b9a7afb1a90c9e2624cae3aa48969b1a0a207819510b3e2e870e2eb147812",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Seal_of_Leland_Stanford_Junior_University.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Swarthmore College",
    file: "/school-logos/swarthmore-college.png",
    origin: "official",
    declaredOn: "https://www.swarthmore.edu/themes/custom/swarthmore_theme/images/icons/favicons/site.webmanifest",
    sourceUrl: "https://www.swarthmore.edu/themes/custom/swarthmore_theme/images/icons/favicons/android-chrome-384x384.png",
    via: "manifest icon",
    domain: "swarthmore.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 378,
    sourceFormat: "png",
    sourceSize: "384x384",
    sha256: "fff174268bf02288f244293b124bf007563e628a10fbf5239ce2fea0cf7b086e",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Texas A&M University",
    file: "/school-logos/texas-a-m-university.png",
    origin: "official",
    declaredOn: "https://www.tamu.edu/",
    sourceUrl: "https://www.tamu.edu/_files/icons/favicon/android-chrome-192x192.png",
    via: "declared icon",
    domain: "tamu.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 192,
    sourceFormat: "png",
    sourceSize: "192x192",
    sha256: "67918851ac90b3684979c5eb25387ecd204da2a91b6c991a38899eaf020b72be",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Trinity College",
    file: "/school-logos/trinity-college.png",
    origin: "official",
    declaredOn: "https://www.trincoll.edu/",
    sourceUrl: "https://www.trincoll.edu/wp-content/themes/trinity/primary/android-chrome-256x256.png",
    via: "declared icon",
    domain: "trincoll.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 256,
    sourceFormat: "png",
    sourceSize: "256x256",
    sha256: "cfd5bef2876701e622ace8f404bad8c94928a41a8ff01346c3796c8958ec684a",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Tufts University",
    file: "/school-logos/tufts-university.png",
    origin: "official",
    declaredOn: "https://www.tufts.edu/",
    sourceUrl: "https://www.tufts.edu/themes/custom/tuftsedu_theme/favicon.png",
    via: "declared icon",
    domain: "tufts.edu",
    fullBleed: false,
    aspect: 1.221,
    contentPx: 498,
    sourceFormat: "png",
    sourceSize: "512x512",
    sha256: "4cd6f65db21c7d1aca274bcafe74e5269edb53d658a862519476b829e7f02450",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Tulane University",
    file: "/school-logos/tulane-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Tulane_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Tulane_University_Logo.svg/250px-Tulane_University_Logo.svg.png",
    via: "wikimedia",
    domain: "tulane.edu",
    fullBleed: false,
    aspect: 0.704,
    contentPx: 355,
    sourceFormat: "png",
    sourceSize: "250x355",
    sha256: "5485658ef07fa63ad577c7f64e1fa25db6182656c9630bf245bba7d7ff53f233",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Tulane_University_Logo.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "University of California, Berkeley",
    file: "/school-logos/university-of-california-berkeley.png",
    origin: "official",
    declaredOn: "https://www.berkeley.edu/",
    sourceUrl: "https://www.berkeley.edu/favicon.svg?v=2",
    via: "declared icon",
    domain: "berkeley.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 6401,
    sourceFormat: "svg",
    sourceSize: "6413x6400",
    sha256: "a4412845779611998c115fcb218f84d94aebdcbc7fc52ffbf729c2fbbf9b3c27",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of California, Davis",
    file: "/school-logos/university-of-california-davis.png",
    origin: "secondary",
    declaredOn: "https://commons.wikimedia.org/wiki/File:The_University_of_California_Davis.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/The%20University%20of%20California%20Davis.svg?width=640",
    via: "wikimedia",
    domain: "ucdavis.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 892,
    sourceFormat: "png",
    sourceSize: "960x960",
    sha256: "f1258e299a88b9272bfcf1c38dad0806fa8d7ffd12ddfa1e5991a9e335e1b99e",
    retrievedAt: "2026-08-29",
    note: "Wikidata Q129421 P154 (logo): The University of California Davis.svg",
  },
  {
    school: "University of California, Irvine",
    file: "/school-logos/university-of-california-irvine.png",
    origin: "secondary",
    declaredOn: "https://commons.wikimedia.org/wiki/File:University_of_California%2C_Irvine_logo.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20California%2C%20Irvine%20logo.svg?width=640",
    via: "wikimedia",
    domain: "universityofcalifornia.edu",
    fullBleed: false,
    aspect: 2.359,
    contentPx: 953,
    sourceFormat: "png",
    sourceSize: "960x412",
    sha256: "fa63c7909f55f646c61e1424929269fbb7daca18f7cdd37e7db2bd0222d97265",
    retrievedAt: "2026-08-29",
    note: "Wikidata Q868421 P154 (logo): University of California, Irvine logo.svg",
  },
  {
    school: "University of California, Los Angeles",
    file: "/school-logos/university-of-california-los-angeles.png",
    origin: "secondary",
    declaredOn: "https://commons.wikimedia.org/wiki/File:The_University_of_California_UCLA.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/The%20University%20of%20California%20UCLA.svg?width=640",
    via: "wikimedia",
    domain: "ucla.edu",
    fullBleed: false,
    aspect: 0.999,
    contentPx: 961,
    sourceFormat: "png",
    sourceSize: "960x961",
    sha256: "259207d9303b9c898380c89d4a9ecd04286c3803ec56175ffc3542ad41458e17",
    retrievedAt: "2026-08-29",
    note: "Wikidata Q174710 P158 (seal): The University of California UCLA.svg",
  },
  {
    school: "University of California, San Diego",
    file: "/school-logos/university-of-california-san-diego.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/University_of_California%2C_San_Diego",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Seal_of_the_University_of_California%2C_San_Diego.svg/250px-Seal_of_the_University_of_California%2C_San_Diego.svg.png",
    via: "wikimedia",
    domain: "ucsd.edu",
    fullBleed: false,
    aspect: 0.996,
    contentPx: 249,
    sourceFormat: "png",
    sourceSize: "250x252",
    sha256: "758a94cfc2e6f43ec41b6ec2d79dacc11ac270e04b72fa9c7d8f7dec18559a73",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Seal_of_the_University_of_California,_San_Diego.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "University of California, Santa Barbara",
    file: "/school-logos/university-of-california-santa-barbara.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/University_of_California%2C_Santa_Barbara",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/4/48/UC_Santa_Barbara_Seal.png",
    via: "wikimedia",
    domain: "ucsb.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 634,
    sourceFormat: "png",
    sourceSize: "646x646",
    sha256: "3b8cc0d3398adf6cac1a39d10c26de155866b1904ab3ba0634f4a195f1075a09",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: UC_Santa_Barbara_Seal.png - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "University of California, Santa Cruz",
    file: "/school-logos/university-of-california-santa-cruz.png",
    origin: "secondary",
    declaredOn: "https://commons.wikimedia.org/wiki/File:The_University_of_California_1868_UCSC.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/The%20University%20of%20California%201868%20UCSC.svg?width=640",
    via: "wikimedia",
    domain: "universityofcalifornia.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 892,
    sourceFormat: "png",
    sourceSize: "960x960",
    sha256: "ad339275da6cb4109b4e925a437983cc4d6dab2ff2d75170e81378464310e845",
    retrievedAt: "2026-08-29",
    note: "Wikidata Q1047293 P154 (logo): The University of California 1868 UCSC.svg",
  },
  {
    school: "University of Chicago",
    file: "/school-logos/university-of-chicago.png",
    origin: "official",
    declaredOn: "https://www.uchicago.edu/",
    sourceUrl: "https://www.uchicago.edu/-/media/images/logo-background-mobile.svg?iar=0&amp;hash=72DEE767D878668741296F29D0ABA96F",
    via: "header logo",
    domain: "uchicago.edu",
    fullBleed: false,
    aspect: 1.728,
    contentPx: 1246,
    sourceFormat: "svg",
    sourceSize: "1288x738",
    sha256: "40cca7d6548d4cf5b40e3e0567c634f4f521701f43bf53e778c05bc4fa4243a3",
    retrievedAt: "2026-08-29",
    note: "The University of Chicago Logo",
  },
  {
    school: "University of Colorado Boulder",
    file: "/school-logos/university-of-colorado-boulder.png",
    origin: "official",
    declaredOn: "https://www.colorado.edu/",
    sourceUrl: "https://www.colorado.edu/themes/custom/boulder_base/favicon.png",
    via: "declared icon",
    domain: "colorado.edu",
    fullBleed: false,
    aspect: 1.067,
    contentPx: 64,
    sourceFormat: "png",
    sourceSize: "64x64",
    sha256: "3a113ed802362393842877428a2f91f4370ea52da427c91abd66a1aed29a7471",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of Connecticut",
    file: "/school-logos/university-of-connecticut.png",
    origin: "official",
    declaredOn: "https://uconn.edu/",
    sourceUrl: "https://uconn.edu/wp-content/uploads/sites/23/2019/09/cropped-uconn-white-favicon-192x192.jpg",
    via: "declared icon",
    domain: "uconn.edu",
    fullBleed: false,
    aspect: 0.947,
    contentPx: 170,
    sourceFormat: "jpeg",
    sourceSize: "192x192",
    sha256: "ef3618bf5c13c513f2b3baf4013f53723ca2c74b87228d217ef92d4c144f7d6b",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of Florida",
    file: "/school-logos/university-of-florida.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/University_of_Florida",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/University_of_Florida_seal.svg/250px-University_of_Florida_seal.svg.png",
    via: "wikimedia",
    domain: "ufl.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 247,
    sourceFormat: "png",
    sourceSize: "250x250",
    sha256: "5157be7ce8b07c0141b3e5e67e72ffbd451b2625874782e23d2a824c3a90337a",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: University_of_Florida_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "University of Georgia",
    file: "/school-logos/university-of-georgia.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/University_of_Georgia",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/University_of_Georgia_seal_1801.svg/960px-University_of_Georgia_seal_1801.svg.png",
    via: "wikimedia",
    domain: "uga.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 960,
    sourceFormat: "png",
    sourceSize: "960x960",
    sha256: "4a7ffb0c791674c5b05ec4ee54091afae5f531c85be669741f7bd72cc1017d4f",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: University_of_Georgia_seal_1801.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "University of Illinois Urbana-Champaign",
    file: "/school-logos/university-of-illinois-urbana-champaign.png",
    origin: "official",
    declaredOn: "https://illinois.edu/",
    sourceUrl: "https://cdn.brand.illinois.edu/touch-icon-180x180.png",
    via: "declared icon",
    domain: "illinois.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 180,
    sourceFormat: "png",
    sourceSize: "180x180",
    sha256: "50e630162b26c6b74f1827099d1f586620971be121817b197052e914df147e7f",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of Maryland, College Park",
    file: "/school-logos/university-of-maryland-college-park.png",
    origin: "official",
    declaredOn: "https://umd.edu/default/static/icons/favicon-256.png",
    sourceUrl: "https://umd.edu/default/static/icons/favicon-256.png",
    via: "curated",
    domain: "umd.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 256,
    sourceFormat: "png",
    sourceSize: "256x256",
    sha256: "8eb9dd0e784cf6979848b85e5d675decc93cd2df3049c43a7eba353f183c6316",
    retrievedAt: "2026-08-29",
    note: "curated: Maryland's own 256px flag globe. Its apple-touch-icon serves the red athletics UMD lockup instead, and the full ringed seal's lettering is illegible at 44px",
  },
  {
    school: "University of Massachusetts Amherst",
    file: "/school-logos/university-of-massachusetts-amherst.png",
    origin: "official",
    declaredOn: "https://www.umass.edu/favicons/site.webmanifest",
    sourceUrl: "https://www.umass.edu/sites/default/files/favicons/android-chrome-256x256.png?v=1.0.0",
    via: "manifest icon",
    domain: "umass.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 256,
    sourceFormat: "png",
    sourceSize: "256x256",
    sha256: "fb92d061ecf7d981411ad2bd50c2d9783d61af1cad87cf558110e17bb5501bd8",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of Miami",
    file: "/school-logos/university-of-miami.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/University_of_Miami",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/2/27/University_of_Miami_seal.svg/330px-University_of_Miami_seal.svg.png",
    via: "wikimedia",
    domain: "miami.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 328,
    sourceFormat: "png",
    sourceSize: "330x330",
    sha256: "1799b5b54cbd991261ecd87aba8db993984d91f2780bb4377334e4180dcf37b4",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: University_of_Miami_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "University of Michigan",
    file: "/school-logos/university-of-michigan.png",
    origin: "secondary",
    declaredOn: "https://commons.wikimedia.org/wiki/Special:FilePath/Michigan%20Wolverines%20logo.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Michigan%20Wolverines%20logo.svg?width=640",
    via: "curated",
    domain: "umich.edu",
    fullBleed: false,
    aspect: 1.39,
    contentPx: 955,
    sourceFormat: "png",
    sourceSize: "960x693",
    sha256: "54d3bb2f337fb527a59457322eba4d2c051088acb0b9c79259d9ce031001e595",
    retrievedAt: "2026-08-29",
    note: "curated: the block M, which its own site and Wikidata both omit in favour of a wordmark",
  },
  {
    school: "University of Minnesota Twin Cities",
    file: "/school-logos/university-of-minnesota-twin-cities.png",
    origin: "official",
    declaredOn: "https://twin-cities.umn.edu/manifest.json",
    sourceUrl: "https://twin-cities.umn.edu/sites/twin-cities.umn.edu/files/pwa/tc-maskable-icon_sm.png",
    via: "manifest icon",
    domain: "umn.edu",
    fullBleed: false,
    aspect: 1.269,
    contentPx: 443,
    sourceFormat: "png",
    sourceSize: "512x512",
    sha256: "c9d7dafe3dfc8a7b9ae0a63a2ec35f86ffaa4b89da49162598ea14145b8cdca0",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of North Carolina at Chapel Hill",
    file: "/school-logos/university-of-north-carolina-at-chapel-hill.png",
    origin: "official",
    declaredOn: "https://www.unc.edu/",
    sourceUrl: "https://www.unc.edu/wp-content/uploads/2025/11/cropped-CB_Background-Favicon-300x300.jpg",
    via: "declared icon",
    domain: "unc.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 300,
    sourceFormat: "jpeg",
    sourceSize: "300x300",
    sha256: "d276ca0f12ed811f3f1b1b48c8dc741cf4b063d513fe024e604e0fdb6146517d",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of Notre Dame",
    file: "/school-logos/university-of-notre-dame.png",
    origin: "official",
    declaredOn: "https://www.nd.edu/",
    sourceUrl: "https://static.nd.edu/images/webclips/default/webclip-512.png",
    via: "declared icon",
    domain: "nd.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 512,
    sourceFormat: "png",
    sourceSize: "512x512",
    sha256: "b836e2ab098d82fe15a64fe7ea0ce7a79073b188b4ace73f80368f35c65ea8bd",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of Pennsylvania",
    file: "/school-logos/university-of-pennsylvania.png",
    origin: "official",
    declaredOn: "https://www.upenn.edu/",
    sourceUrl: "https://www.upenn.edu/themes/custom/penn_global/assets/img/simplified-shield.ico",
    via: "declared icon",
    domain: "upenn.edu",
    fullBleed: false,
    aspect: 0.939,
    contentPx: 244,
    sourceFormat: "bmp ico via sips",
    sourceSize: "229x256",
    sha256: "bbbc848928ddf20e292535fd5bf0e75c0db32d8d53a022b83a711cab9e417270",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of Pittsburgh",
    file: "/school-logos/university-of-pittsburgh.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/University_of_Pittsburgh",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/University_of_Pittsburgh_seal.svg/330px-University_of_Pittsburgh_seal.svg.png",
    via: "wikimedia",
    domain: "pitt.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 330,
    sourceFormat: "png",
    sourceSize: "330x330",
    sha256: "321ae603f5f6d93745cb7cceff92ca1dba8b64169dd16e446a79f20ba53a78a1",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: University_of_Pittsburgh_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "University of Richmond",
    file: "/school-logos/university-of-richmond.png",
    origin: "official",
    declaredOn: "https://www.richmond.edu/",
    sourceUrl: "https://d2n43swdo6jzfk.cloudfront.net/dist/img/png/apple-touch-icon-ipad-retina-152x152.png",
    via: "declared icon",
    domain: "richmond.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 152,
    sourceFormat: "png",
    sourceSize: "152x152",
    sha256: "3ecb4db210eb9f5b7694240922656cf87ba995ebcbdb48cb194131be23f3e5ca",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of Rochester",
    file: "/school-logos/university-of-rochester.png",
    origin: "official",
    declaredOn: "https://www.rochester.edu/",
    sourceUrl: "https://www.rochester.edu/assets/images/brand/favicon/favicon.svg?v=3",
    via: "declared icon",
    domain: "rochester.edu",
    fullBleed: false,
    aspect: 0.766,
    contentPx: 8338,
    sourceFormat: "svg",
    sourceSize: "8338x8338",
    sha256: "456df2bad13d57eb497bd82a34f3019a97551268e26b718342ddc4433eacf198",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of Southern California",
    file: "/school-logos/university-of-southern-california.png",
    origin: "official",
    declaredOn: "https://usc.edu/wp-content/themes/usc-communications-2023/favicon/site.webmanifest",
    sourceUrl: "https://usc.edu/wp-content/themes/usc-communications-2023/favicon/android-chrome-512x512.png",
    via: "manifest icon",
    domain: "usc.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 512,
    sourceFormat: "png",
    sourceSize: "512x512",
    sha256: "4015ac35243e92f6707a5ecfc2beaf4935056af3ddbed1a6bfab438f09f7fb6a",
    retrievedAt: "2026-08-29",
  },
  {
    school: "University of Texas at Austin",
    file: "/school-logos/university-of-texas-at-austin.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/University_of_Texas_at_Austin",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/University_of_Texas_at_Austin_seal.svg/250px-University_of_Texas_at_Austin_seal.svg.png",
    via: "wikimedia",
    domain: "utexas.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 249,
    sourceFormat: "png",
    sourceSize: "250x250",
    sha256: "b573d70a5287f9297d7e1d5f50cda117ef0d22359aebe338d89789d6e929b548",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: University_of_Texas_at_Austin_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "University of Virginia",
    file: "/school-logos/university-of-virginia.png",
    origin: "secondary",
    declaredOn: "https://commons.wikimedia.org/wiki/File:University_of_Virginia_Rotunda_logo.svg",
    sourceUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/University%20of%20Virginia%20Rotunda%20logo.svg?width=640",
    via: "wikimedia",
    domain: "virginia.edu",
    fullBleed: false,
    aspect: 0.982,
    contentPx: 965,
    sourceFormat: "png",
    sourceSize: "960x978",
    sha256: "e984b5858b47affb9293fadd31dacafd0129c90758c2bc69582c51f71727b79b",
    retrievedAt: "2026-08-29",
    note: "Wikidata Q213439 P154 (logo): University of Virginia Rotunda logo.svg",
  },
  {
    school: "University of Washington",
    file: "/school-logos/university-of-washington.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/University_of_Washington",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/58/University_of_Washington_seal.svg/250px-University_of_Washington_seal.svg.png",
    via: "wikimedia",
    domain: "washington.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 248,
    sourceFormat: "png",
    sourceSize: "250x250",
    sha256: "7447a8eb7bd55aacb699df206f6b462eb52cba5222c3f0f3352d40486eb75d79",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: University_of_Washington_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "University of Wisconsin-Madison",
    file: "/school-logos/university-of-wisconsin-madison.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/University_of_Wisconsin-Madison",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Seal_of_the_University_of_Wisconsin.svg/960px-Seal_of_the_University_of_Wisconsin.svg.png",
    via: "wikimedia",
    domain: "wisc.edu",
    fullBleed: false,
    aspect: 0.997,
    contentPx: 947,
    sourceFormat: "png",
    sourceSize: "960x960",
    sha256: "148c0b070251825e5ca090673a6a257db7a660cc09ac4c588478803d6c109cab",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Seal_of_the_University_of_Wisconsin.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Vanderbilt University",
    file: "/school-logos/vanderbilt-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Vanderbilt_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/2/29/Vanderbilt_University_seal.svg/250px-Vanderbilt_University_seal.svg.png",
    via: "wikimedia",
    domain: "vanderbilt.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 250,
    sourceFormat: "png",
    sourceSize: "250x251",
    sha256: "0654c1f04608c2b39f025daaf01c97c1f7e47c12a66dd9f134b6dbc42f811ad7",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Vanderbilt_University_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Vassar College",
    file: "/school-logos/vassar-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Vassar_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Vassar_College_Seal.svg/330px-Vassar_College_Seal.svg.png",
    via: "wikimedia",
    domain: "vassar.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 330,
    sourceFormat: "png",
    sourceSize: "330x330",
    sha256: "45e5830089612ff2366812c9df0e65db31a09de15fbdc47d2d74ece9507e0f41",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Vassar_College_Seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Villanova University",
    file: "/school-logos/villanova-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Villanova_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/d/da/Villanova_University_seal.svg/250px-Villanova_University_seal.svg.png",
    via: "wikimedia",
    domain: "villanova.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 249,
    sourceFormat: "png",
    sourceSize: "250x250",
    sha256: "ceeede02667bcb359a8a69d8359425f5d64948f0ad0786461719cda5b96ca6ef",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Villanova_University_seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Virginia Polytechnic Institute and State University",
    file: "/school-logos/virginia-polytechnic-institute-and-state-university.png",
    origin: "official",
    declaredOn: "https://vt.edu/",
    sourceUrl: "https://vt.edu/apple-touch-icon.png",
    via: "conventional path",
    domain: "vt.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 180,
    sourceFormat: "png",
    sourceSize: "180x180",
    sha256: "562da257bd98e9efea4c15af14a5d7dc6020648f6cabc1db4f6043ed75240884",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Wake Forest University",
    file: "/school-logos/wake-forest-university.png",
    origin: "official",
    declaredOn: "https://www.wfu.edu/",
    sourceUrl: "https://prod.wp.cdn.aws.wfu.edu/wfu-gutenberg-quarantheme/assets/images/icon-512.png",
    via: "declared icon",
    domain: "wfu.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 512,
    sourceFormat: "png",
    sourceSize: "512x512",
    sha256: "253c4c4260f5061a1baa6a68e04f09de053d472690a6b16dcff82189ee16da28",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Washington and Lee University",
    file: "/school-logos/washington-and-lee-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Washington_and_Lee_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Washington_and_lee_univ_seal.png",
    via: "wikimedia",
    domain: "wlu.edu",
    fullBleed: false,
    aspect: 1,
    contentPx: 265,
    sourceFormat: "png",
    sourceSize: "270x271",
    sha256: "ff103d3299c9474ac0246d84c33416d925af9d7bfef88b139f118321a44c4fd0",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Washington_and_lee_univ_seal.png - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Washington University in St. Louis",
    file: "/school-logos/washington-university-in-st-louis.png",
    origin: "official",
    declaredOn: "https://washu.edu/",
    sourceUrl: "https://washu.edu/app/themes/antipasto/assets/img/favicon/apple-touch-icon.png",
    via: "declared icon",
    domain: "washu.edu",
    fullBleed: false,
    aspect: 0.884,
    contentPx: 172,
    sourceFormat: "png",
    sourceSize: "180x180",
    sha256: "2dc0c67ef644016affcad4bd9b626e3f4bb96345a39bf35033c8fe3f124efe60",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Wellesley College",
    file: "/school-logos/wellesley-college.png",
    origin: "official",
    declaredOn: "https://www.wellesley.edu/",
    sourceUrl: "https://www.wellesley.edu/frontend/static-html/favicons/apple-touch-icon.png?v=2.0.0",
    via: "declared icon",
    domain: "wellesley.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 180,
    sourceFormat: "png",
    sourceSize: "180x180",
    sha256: "575d4949e5240fafa79a56a59eeff19f4165cad079c1b1728238cbcf2512c990",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Wesleyan University",
    file: "/school-logos/wesleyan-university.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Wesleyan_University",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/5/5e/Wesleyan_University_Academic_Seal.png",
    via: "wikimedia",
    domain: "wesleyan.edu",
    fullBleed: false,
    aspect: 0.997,
    contentPx: 286,
    sourceFormat: "png",
    sourceSize: "317x314",
    sha256: "ebf89cd3472c13d995f17e1d62c2dd6c09365425cc4896fe2316e620d306b97a",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Wesleyan_University_Academic_Seal.png - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "William & Mary",
    file: "/school-logos/william-mary.png",
    origin: "official",
    declaredOn: "https://www.wm.edu/",
    sourceUrl: "https://www.wm.edu/apple-touch-icon.png",
    via: "declared icon",
    domain: "wm.edu",
    fullBleed: false,
    aspect: 1.009,
    contentPx: 107,
    sourceFormat: "png",
    sourceSize: "152x152",
    sha256: "f0287ae3ca340fbc33e12ffed5cddf3b50cd09cdc9dea0869697abd68d438915",
    retrievedAt: "2026-08-29",
  },
  {
    school: "Williams College",
    file: "/school-logos/williams-college.png",
    origin: "secondary",
    declaredOn: "https://en.wikipedia.org/wiki/Williams_College",
    sourceUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/1/19/Williams_College_Seal.svg/250px-Williams_College_Seal.svg.png",
    via: "wikimedia",
    domain: "williams.edu",
    fullBleed: false,
    aspect: 1.008,
    contentPx: 250,
    sourceFormat: "png",
    sourceSize: "250x248",
    sha256: "ffb243c073f79f92e463339b71acb956ec9d429a2c2b2ec39bb54fee151afaf4",
    retrievedAt: "2026-08-29",
    note: "Wikipedia infobox: Williams_College_Seal.svg - likely a non-free fair-use upload, verify before enabling",
  },
  {
    school: "Yale University",
    file: "/school-logos/yale-university.png",
    origin: "official",
    declaredOn: "https://www.yale.edu/",
    sourceUrl: "https://www.yale.edu/sites/all/themes/yale_blue/images/favicons/android-chrome-192x192.png",
    via: "declared icon",
    domain: "yale.edu",
    fullBleed: true,
    aspect: 1,
    contentPx: 192,
    sourceFormat: "png",
    sourceSize: "192x192",
    sha256: "c5f66967926f7847b01b05a8a54ef324ca3b2deb7dd4ed595321ac462b19e928",
    retrievedAt: "2026-08-29",
  },
];

/**
 * Whether logos are shown at all.
 *
 * This used to require `SHOW_SCHOOL_LOGOS=1`, back when the files were
 * gitignored and the registry was empty in the committed source: three
 * independent gates so that trademarked marks could not ship by accident.
 *
 * The owner has now deliberately opened the other two - the assets are
 * committed and the registry is populated - so keeping the environment gate
 * would only mean a deploy that silently renders initials. Committing the
 * files *is* the deliberate act now. An empty registry still renders initials,
 * and `SHOW_SCHOOL_LOGOS=0` still forces them off, which is the switch to reach
 * for if a takedown request ever arrives.
 */
export function logosEnabled(): boolean {
  if (process.env.SHOW_SCHOOL_LOGOS === "0") return false;
  return SCHOOL_LOGOS.length > 0;
}

const flatten = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

/**
 * Shorter forms of a school's name that still identify it unambiguously.
 *
 * A workspace stores whatever name the student typed or the catalogue imported,
 * and those disagree: this database holds both "University of Maryland" and
 * "University of Maryland, College Park". An exact-match lookup gave the
 * shorter one initials while the longer one had a logo.
 *
 * A campus suffix is only dropped when the remainder belongs to exactly one
 * school. "University of Maryland, College Park" yields "University of
 * Maryland" because nothing else claims it; "University of California,
 * Berkeley" yields nothing, because seven campuses would answer to "University
 * of California" and a wrong mark is worse than initials.
 */
function buildIndex(): Map<string, SchoolLogo> {
  const index = new Map<string, SchoolLogo>();
  for (const logo of SCHOOL_LOGOS) index.set(flatten(logo.school), logo);

  const contenders = new Map<string, SchoolLogo[]>();
  for (const logo of SCHOOL_LOGOS) {
    const shortened = [
      logo.school.split(",")[0],
      logo.school.split(" at ")[0],
      logo.school.split(/\s*[-–—]\s*/)[0],
    ];
    for (const candidate of shortened) {
      const key = flatten(candidate);
      if (!key || index.has(key)) continue;
      contenders.set(key, [...(contenders.get(key) ?? []), logo]);
    }
  }
  for (const [key, matches] of contenders) {
    if (matches.length === 1) index.set(key, matches[0]);
  }
  return index;
}

let index: Map<string, SchoolLogo> | null = null;

export function logoForSchool(name: string): SchoolLogo | undefined {
  if (!logosEnabled()) return undefined;
  if (DECLINED_SCHOOLS.includes(name) || NO_USABLE_LOGO.includes(name)) return undefined;
  index ??= buildIndex();
  const found = index.get(flatten(name));
  if (!found) return undefined;
  // The alias must not resurrect a school that was deliberately excluded.
  if (DECLINED_SCHOOLS.includes(found.school) || NO_USABLE_LOGO.includes(found.school)) return undefined;
  return found;
}
