import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { runTravilaTurn } from "./travila";

function jsonResponse(body: unknown, ok = true, status = 200) {
  return { ok, status, json: async () => body } as Response;
}

/**
 * Transport only.
 *
 * These cases used to run through shortenEssay, which was this file's one
 * feature-level caller before the rewrite-style shortener was removed. The
 * create-thread -> send-message -> poll contract is still shared by every
 * coach, so the coverage moved down to runTravilaTurn rather than leaving with
 * the shortener. Input validation is deliberately absent - each coach owns its
 * own validator, and each has its own tests for it.
 */
describe("runTravilaTurn", () => {
  const run = () => runTravilaTurn("test-key", "user-1", "some_profile", "instruction text");

  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
    vi.unstubAllGlobals();
  });

  it("returns the assistant text, joining text parts and dropping reasoning parts", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
      .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
      .mockResolvedValueOnce(jsonResponse({
        messageHistory: [
          {
            role: "ROLE_ASSISTANT",
            generatedBy: "run-1",
            content: [
              { type: "CONTENT_PART_TYPE_REASONING", content: "internal thinking" },
              { type: "CONTENT_PART_TYPE_TEXT", content: "Part one." },
              { type: "CONTENT_PART_TYPE_TEXT", content: "Part two." },
            ],
          },
        ],
      }));
    vi.stubGlobal("fetch", fetchMock);

    const promise = run();
    await vi.runAllTimersAsync();

    expect(await promise).toEqual({ text: "Part one.\n\nPart two." });
    expect(fetchMock).toHaveBeenCalledTimes(3);
    // The profile and the instruction are the caller's, passed through as given.
    const sendMessageBody = JSON.parse(fetchMock.mock.calls[1][1].body);
    expect(sendMessageBody.setActiveProfileId).toBe("some_profile");
    expect(sendMessageBody.userMessage.content[0].content).toBe("instruction text");
  });

  it("polls again when the matching assistant message has not arrived yet", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
      .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
      .mockResolvedValueOnce(jsonResponse({ messageHistory: [] }))
      .mockResolvedValueOnce(jsonResponse({
        messageHistory: [
          { role: "ROLE_ASSISTANT", generatedBy: "run-1", content: [{ type: "CONTENT_PART_TYPE_TEXT", content: "Done." }] },
        ],
      }));
    vi.stubGlobal("fetch", fetchMock);

    const promise = run();
    await vi.runAllTimersAsync();

    expect(await promise).toEqual({ text: "Done." });
    expect(fetchMock).toHaveBeenCalledTimes(4);
  });

  it("ignores an assistant message generated by a different run", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
      .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
      .mockResolvedValue(jsonResponse({
        messageHistory: [
          { role: "ROLE_ASSISTANT", generatedBy: "run-0", content: [{ type: "CONTENT_PART_TYPE_TEXT", content: "Stale." }] },
        ],
      }));
    vi.stubGlobal("fetch", fetchMock);

    const promise = run();
    await vi.runAllTimersAsync();

    expect(await promise).toEqual({ error: { status: "error", reason: "timeout" } });
  });

  it("times out if the run never completes", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
      .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
      .mockResolvedValue(jsonResponse({ messageHistory: [] }));
    vi.stubGlobal("fetch", fetchMock);

    const promise = run();
    await vi.runAllTimersAsync();

    expect(await promise).toEqual({ error: { status: "error", reason: "timeout" } });
  });

  it("reports a malformed response when the assistant message has no text parts", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
      .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
      .mockResolvedValueOnce(jsonResponse({
        messageHistory: [
          { role: "ROLE_ASSISTANT", generatedBy: "run-1", content: [{ type: "CONTENT_PART_TYPE_REASONING", content: "only thinking" }] },
        ],
      }));
    vi.stubGlobal("fetch", fetchMock);

    const promise = run();
    await vi.runAllTimersAsync();

    expect(await promise).toMatchObject({ error: { status: "error", reason: "malformed" } });
  });

  it("reports an http error and stops on a non-2xx response", async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(jsonResponse({}, false, 500));
    vi.stubGlobal("fetch", fetchMock);

    expect(await run()).toMatchObject({ error: { status: "error", reason: "http" } });
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });
});

/**
 * Observability. These exist because the run log sits on the request path of
 * every AI feature: if it can throw, or if it can ever carry essay text, that
 * is a production incident rather than a missing log line.
 */
describe("[travila-run] logging", () => {
  const SECRET_INSTRUCTION = "SECRET-ESSAY-TEXT the student's confidential draft";

  beforeEach(() => { vi.useFakeTimers(); });
  afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });

  async function runAndCapture(fetchMock: ReturnType<typeof vi.fn>) {
    vi.stubGlobal("fetch", fetchMock);
    const logged: unknown[][] = [];
    vi.spyOn(console, "log").mockImplementation((...args: unknown[]) => { logged.push(args); });
    const promise = runTravilaTurn("test-key", "user-1", "college_essay_shorten_coach", SECRET_INSTRUCTION);
    await vi.runAllTimersAsync();
    const result = await promise;
    const runs = logged.filter((a) => a[0] === "[travila-run]");
    return { result, runs, payload: runs.length ? JSON.parse(String(runs[0][1])) : null };
  }

  const okFetch = () => vi.fn()
    .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
    .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
    .mockResolvedValueOnce(jsonResponse({
      messageHistory: [{
        role: "ROLE_ASSISTANT", generatedBy: "run-1",
        content: [{ type: "CONTENT_PART_TYPE_TEXT", content: "SECRET-REPLY the model's answer" }],
        usage: { promptTokens: 1200, completionTokens: 300, totalTokens: 1500, costEstimate: 0.0012,
                 completionTokensDetails: { reasoningTokens: 64 } },
        generationContext: { model: "google/gemini-3.7-flash", profileId: "college_essay_shorten_coach", profileVersion: 1 },
      }],
    }));

  it("emits exactly one run log with the run's metadata", async () => {
    const { result, runs, payload } = await runAndCapture(okFetch());
    expect(result).toHaveProperty("text");
    expect(runs).toHaveLength(1);
    expect(payload).toMatchObject({
      feature: "shorten",
      profileId: "college_essay_shorten_coach",
      profileVersion: 1,
      model: "google/gemini-3.7-flash",
      runId: "run-1",
      status: "ok",
      promptTokens: 1200,
      completionTokens: 300,
      reasoningTokens: 64,
      totalTokens: 1500,
      costEstimate: 0.0012,
    });
    expect(typeof payload.latencyMs).toBe("number");
  });

  it("never logs the instruction, the reply, the key, or the user id", async () => {
    const { runs } = await runAndCapture(okFetch());
    const line = JSON.stringify(runs);
    for (const secret of ["SECRET-ESSAY-TEXT", "SECRET-REPLY", "test-key", "user-1", "confidential"]) {
      expect(line, `run log leaked ${secret}`).not.toContain(secret);
    }
  });

  it("logs a sanitized failure once, without changing what the caller receives", async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(jsonResponse({}, false, 503));
    const { result, runs, payload } = await runAndCapture(fetchMock);
    // The existing failure contract is untouched.
    expect(result).toEqual({ error: { status: "error", reason: "http", detail: "create-thread: 503" } });
    expect(runs).toHaveLength(1);
    expect(payload).toMatchObject({ status: "error", errorReason: "http", errorDetail: "create-thread: 503" });
  });

  it("cannot fail the run even if logging itself throws", async () => {
    vi.stubGlobal("fetch", okFetch());
    vi.spyOn(console, "log").mockImplementation(() => { throw new Error("logging backend exploded"); });
    const promise = runTravilaTurn("test-key", "user-1", "college_essay_shorten_coach", SECRET_INSTRUCTION);
    await vi.runAllTimersAsync();
    // The student still gets their answer.
    expect(await promise).toEqual({ text: "SECRET-REPLY the model's answer" });
  });
});
