import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { runTravilaTurn } from "./travila";

function jsonResponse(body: unknown, ok = true, status = 200) {
  return { ok, status, json: async () => body } as Response;
}

/**
 * Transport only.
 *
 * These cases used to run through shortenEssay, which was this file's one
 * feature-level caller before the rewrite-style shortener was removed. The
 * create-thread -> send-message -> poll contract is still shared by every
 * coach, so the coverage moved down to runTravilaTurn rather than leaving with
 * the shortener. Input validation is deliberately absent - each coach owns its
 * own validator, and each has its own tests for it.
 */
describe("runTravilaTurn", () => {
  const run = () => runTravilaTurn("test-key", "user-1", "some_profile", "instruction text");

  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
    vi.unstubAllGlobals();
  });

  it("returns the assistant text, joining text parts and dropping reasoning parts", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
      .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
      .mockResolvedValueOnce(jsonResponse({
        messageHistory: [
          {
            role: "ROLE_ASSISTANT",
            generatedBy: "run-1",
            content: [
              { type: "CONTENT_PART_TYPE_REASONING", content: "internal thinking" },
              { type: "CONTENT_PART_TYPE_TEXT", content: "Part one." },
              { type: "CONTENT_PART_TYPE_TEXT", content: "Part two." },
            ],
          },
        ],
      }));
    vi.stubGlobal("fetch", fetchMock);

    const promise = run();
    await vi.runAllTimersAsync();

    expect(await promise).toEqual({ text: "Part one.\n\nPart two." });
    expect(fetchMock).toHaveBeenCalledTimes(3);
    // The profile and the instruction are the caller's, passed through as given.
    const sendMessageBody = JSON.parse(fetchMock.mock.calls[1][1].body);
    expect(sendMessageBody.setActiveProfileId).toBe("some_profile");
    expect(sendMessageBody.userMessage.content[0].content).toBe("instruction text");
  });

  it("polls again when the matching assistant message has not arrived yet", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
      .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
      .mockResolvedValueOnce(jsonResponse({ messageHistory: [] }))
      .mockResolvedValueOnce(jsonResponse({
        messageHistory: [
          { role: "ROLE_ASSISTANT", generatedBy: "run-1", content: [{ type: "CONTENT_PART_TYPE_TEXT", content: "Done." }] },
        ],
      }));
    vi.stubGlobal("fetch", fetchMock);

    const promise = run();
    await vi.runAllTimersAsync();

    expect(await promise).toEqual({ text: "Done." });
    expect(fetchMock).toHaveBeenCalledTimes(4);
  });

  it("ignores an assistant message generated by a different run", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
      .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
      .mockResolvedValue(jsonResponse({
        messageHistory: [
          { role: "ROLE_ASSISTANT", generatedBy: "run-0", content: [{ type: "CONTENT_PART_TYPE_TEXT", content: "Stale." }] },
        ],
      }));
    vi.stubGlobal("fetch", fetchMock);

    const promise = run();
    await vi.runAllTimersAsync();

    expect(await promise).toEqual({ error: { status: "error", reason: "timeout" } });
  });

  it("times out if the run never completes", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
      .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
      .mockResolvedValue(jsonResponse({ messageHistory: [] }));
    vi.stubGlobal("fetch", fetchMock);

    const promise = run();
    await vi.runAllTimersAsync();

    expect(await promise).toEqual({ error: { status: "error", reason: "timeout" } });
  });

  it("reports a malformed response when the assistant message has no text parts", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(jsonResponse({ thread: { threadId: "thread-1" } }))
      .mockResolvedValueOnce(jsonResponse({ runId: "run-1" }))
      .mockResolvedValueOnce(jsonResponse({
        messageHistory: [
          { role: "ROLE_ASSISTANT", generatedBy: "run-1", content: [{ type: "CONTENT_PART_TYPE_REASONING", content: "only thinking" }] },
        ],
      }));
    vi.stubGlobal("fetch", fetchMock);

    const promise = run();
    await vi.runAllTimersAsync();

    expect(await promise).toMatchObject({ error: { status: "error", reason: "malformed" } });
  });

  it("reports an http error and stops on a non-2xx response", async () => {
    const fetchMock = vi.fn().mockResolvedValueOnce(jsonResponse({}, false, 500));
    vi.stubGlobal("fetch", fetchMock);

    expect(await run()).toMatchObject({ error: { status: "error", reason: "http" } });
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });
});
