export const PROMPT_FAMILIES = [
  ["core-story", "Personal Statement / Core Story", "Open-ended personal narrative, defining experience, growth, or central story.", "#7b403c"],
  ["identity-background", "Identity & Background", "Culture, family, upbringing, identity, diversity, lived experience, or formative environment.", "#9a6048"],
  ["community-contribution", "Community & Contribution", "Belonging, service, collaboration, community impact, and intended contribution.", "#59644d"],
  ["challenge-growth", "Challenge, Setback & Growth", "Obstacles, failure, conflict, resilience, recovery, change, and lessons learned.", "#6c5b51"],
  ["intellectual-curiosity", "Intellectual Curiosity", "Ideas, questions, research, creativity, and learning beyond requirements.", "#49636b"],
  ["why-major", "Why Major / Academic Interests", "Academic development, interdisciplinary interests, and reasons for pursuing a field.", "#56617a"],
  ["why-school", "Why This School / Program", "Institutional fit, specific resources, programs, culture, and intended contribution.", "#8a493f"],
  ["activities-impact", "Activities, Leadership & Impact", "Activities, work, responsibilities, projects, leadership, initiative, and measurable impact.", "#83703f"],
  ["values-meaning", "Values, Perspective & Meaning", "Beliefs, ethical questions, changed perspectives, motivations, and priorities.", "#6d5570"],
  ["short-takes", "Short Takes & Personality", "Joy, gratitude, roommate responses, lists, favorite media, and other short-form prompts.", "#3f6b65"],
] as const;

export const SECONDARY_TAGS = [
  "family",
  "culture",
  "service",
  "leadership",
  "creativity",
  "research",
  "entrepreneurship",
  "career goals",
  "future impact",
  "disagreement",
  "change of mind",
  "achievement",
  "responsibility",
  "interdisciplinary",
  "roommate",
  "gratitude",
  "joy",
  "books/media",
  "unusual format",
  "school-specific",
  "very short response",
] as const;
