import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const arizonaState: SchoolSourceRecord = {
  schoolName: "Arizona State University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "school-specific",
  sourceUrl: "https://admission.asu.edu/apply/first-year/admission",
  retrievedAt: "2026-08-31",
  note: "ASU affirmatively states that its general first-year application requires no essay or personal statement. The separate Barrett Honors College Fall 2027 application requires one 300-500 word essay chosen from three prompts.",
  promptGroups: [
    { key: "barrett-essay", label: "Barrett Honors essay (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "what-is-a-question-you-find-yourself-returning-to", title: "What is a question you find yourself returning to repeatedly", promptText: "What is a question you find yourself returning to repeatedly? How does your pursuit of an answer, or even just the persistence of the question itself, suggest you are a strong fit for Barrett?", minWordCount: 300, maxWordCount: 500, requirement: "conditional", conditionalNote: "Applicant applies separately to Barrett and chooses this as one of three essay options.", groupKey: "barrett-essay", programKey: "barrett-honors-college", programLabel: "Barrett, The Honors College", note: "Applicant applies separately to Barrett and chooses this as one of three essay options." },
    { externalRef: "tell-us-about-a-time-when-something-did-not-go", title: "Tell us about a time when something did not go according to plan", promptText: "Tell us about a time when something did not go according to plan. Focus less on the outcome and more on how the ways you responded in the moment suggest you are a strong fit for Barrett.", minWordCount: 300, maxWordCount: 500, requirement: "conditional", conditionalNote: "Applicant applies separately to Barrett and chooses this as one of three essay options.", groupKey: "barrett-essay", programKey: "barrett-honors-college", programLabel: "Barrett, The Honors College", note: "Applicant applies separately to Barrett and chooses this as one of three essay options." },
    { externalRef: "what-is-an-object-that-connects-you-to-your-family-or", title: "What is an object that connects you to your family or community, and", promptText: "What is an object that connects you to your family or community, and how or why does it do this? How does this connection make you a strong fit for Barrett?", minWordCount: 300, maxWordCount: 500, requirement: "conditional", conditionalNote: "Applicant applies separately to Barrett and chooses this as one of three essay options.", groupKey: "barrett-essay", programKey: "barrett-honors-college", programLabel: "Barrett, The Honors College", note: "Applicant applies separately to Barrett and chooses this as one of three essay options." },
  ],
};
