import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const bostonUniversity: SchoolSourceRecord = {
  schoolName: "Boston University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.bu.edu/admissions/apply/first-year/",
  retrievedAt: "2026-08-31",
  note: "Multiple independent 2026-27-labeled secondary sources (College Essay Guy, College Transitions, College Essay Advisors, GradGPT, Indigo Research) all agree that BU's main Common App supplement for the 2026-27 cycle (Fall 2027 entry) is a single required 300-word-or-less question, 'What about being a student at BU most excites you?', with no second contribution sentence, no founding-principles preamble, and no social-issue alternative.",
  promptGroups: [
    { key: "bu-kilachand", label: "Kilachand Honors College (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "what-about-being-a-student-at-bu-most-excites-you", title: "What about being a student at BU most excites you", promptText: "What about being a student at BU most excites you?", maxWordCount: 300, requirement: "required" },
    { externalRef: "what-about-the-kilachand-honors-college-resonates-with", title: "What about the Kilachand Honors College resonates with you, and how", promptText: "What about the Kilachand Honors College resonates with you, and how would Kilachand’s curriculum fulfill your academic, creative, intellectual, and/or professional goals?", maxWordCount: 600, requirement: "conditional", conditionalNote: "Applicant requests consideration for Kilachand Honors College and chooses one of two options.", groupKey: "bu-kilachand", programKey: "kilachand-honors-college", programLabel: "Kilachand Honors College" },
    { externalRef: "if-you-could-create-a-new-kilachand-course-what-would", title: "If you could create a new Kilachand course, what would it be", promptText: "If you could create a new Kilachand course, what would it be? How would your imagined course align with the core values of Kilachand?", maxWordCount: 600, requirement: "conditional", conditionalNote: "Applicant requests consideration for Kilachand Honors College and chooses one of two options.", groupKey: "bu-kilachand", programKey: "kilachand-honors-college", programLabel: "Kilachand Honors College" },
  ],
};
