import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const bowdoin: SchoolSourceRecord = {
  schoolName: "Bowdoin College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.bowdoin.edu/admissions/apply/",
  retrievedAt: "2026-08-31",
  note: "Bowdoin’s current official application page confirms two optional 250-word essays. A current-cycle secondary source confirms the required 140-character discovery question. The line-selection control for The Offer is not itself a writing field and is not separately listed.",
  prompts: [
    { externalRef: "how-did-you-first-learn-about-bowdoin", title: "How did you first learn about Bowdoin", promptText: "How did you first learn about Bowdoin?", maxCharCount: 140, requirement: "required" },
    { externalRef: "offer-of-the-college", title: "The Offer of the College", promptText: "Generations of students have found connection and meaning in Bowdoin’s “The Offer of the College,” written in 1906 by Bowdoin President William DeWitt Hyde. To be at home in all lands and all ages; to count Nature a familiar acquaintance, and Art an intimate friend; to gain a standard for the appreciation of others’ work and the criticism of your own; to carry the keys of the world’s library in your pocket, and feel its resources behind you in whatever task you undertake; to make hosts of friends...who are to be leaders in all walks of life; to lose yourself in generous enthusiasms and cooperate with others for common ends— This is the offer of the college for the best four years of your life. Which line from The Offer resonates most with you? The Offer represents Bowdoin’s values. Please reflect on the line you selected and how it has meaning to you.", maxWordCount: 250, requirement: "optional" },
    { externalRef: "navigating-through-differences", title: "Navigating through differences", promptText: "Bowdoin believes that its broadly diverse and inclusive campus community prepares graduates to be contributing and useful citizens of the world. Every graduate of this institution should be confident in their preparation to be able to navigate through differences and in all sorts of situations. A Bowdoin education does not guarantee these skills, but it does impart a set of tools necessary to bravely enter unfamiliar conditions with the confidence to deal effectively with ambiguity. If you wish, you may share anything about the unique experiences and perspectives that you would bring with you to the Bowdoin campus and community or an experience you have had that required you to navigate across or through difference.", maxWordCount: 250, requirement: "optional" },
  ],
};
