import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const brandeis: SchoolSourceRecord = {
  schoolName: "Brandeis University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.brandeis.edu/admissions/apply/application-process/first-year.html",
  retrievedAt: "2026-08-31",
  note: "No general Brandeis writing supplement exists for standard domestic first-year applicants: confirmed by Common App's own Brandeis writing-requirements support article, Common App's official 2026-27 First-Year Requirements Grid (content.commonapp.org/Files/ReqGrid.pdf, updated 08-21-2026), and multiple secondary guides (GradGPT, explicitly labeled 2026-27; CollegeVine; collegeadvisor.com), which all state that only two conditional applicant groups write a Brandeis-specific supplemental essay.",
  prompts: [
    { externalRef: "what-excites-you-the-most-about-being-an-international", title: "What excites you the most about being an international student at", promptText: "What excites you the most about being an international student at Brandeis University?", maxWordCount: 250, requirement: "conditional", conditionalNote: "International first-year applicants only.", programKey: "international-applicants", programLabel: "International applicants" },
    { externalRef: "the-myra-kraft-transitional-year-program-mktyp", title: "The Myra Kraft Transitional Year Program (MKTYP) / Achievers Program is", promptText: "The Myra Kraft Transitional Year Program (MKTYP) / Achievers Program is designed to guide you toward adjusting to the rigors and challenges of the college experience with a small cohort of peers. What strengths will you bring to the group, and in what areas will you benefit from the strengths of others?", maxWordCount: 250, requirement: "conditional", conditionalNote: "Applicants who opt into the Myra Kraft Achievers Program (MKAP, formerly MKTYP) only. This is a distinct, separate application track from the international-applicant supplement above; it is not defined by, or limited to, international status -- domestic applicants may also apply to MKAP.", programKey: "myra-kraft-achievers-program-mkap", programLabel: "Myra Kraft Achievers Program (MKAP)" },
  ],
};
