import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const brown: SchoolSourceRecord = {
  schoolName: "Brown University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admission.brown.edu/apply/how-apply",
  retrievedAt: "2026-08-31",
  note: "Brown’s official page explicitly identifies the 2026-27 application cycle and publishes all four general essays plus the PLME and Brown|RISD conditional essays. The page’s program-section boilerplate refers to “three essays required of all first-year applicants,” but the same page clearly lists four; the four listed essays are retained.",
  prompts: [
    { externalRef: "core-open-curriculum", title: "Your approach to the Open Curriculum", promptText: "“There is something distinctive about Brown students. It is a blend of intellectual curiosity, creativity, and humility. A commitment to collaboration. An openness to new ideas and perspectives. A desire to make the world better. And it is resilience: the ability to recover and thrive after experiencing difficulties.” From President Christina Paxson’s 2025 Convocation Address. How will you use these characteristics or others to shape your approach to the Open Curriculum?", minWordCount: 150, maxWordCount: 250, requirement: "required" },
    { externalRef: "core-growing-up", title: "Growing up and contributing to Brown", promptText: "Students entering Brown often find that making their home on College Hill naturally invites reflection on where they came from. Share how an aspect of your growing up has inspired or challenged you, and what unique contributions this might allow you to make to the Brown community.", minWordCount: 150, maxWordCount: 250, requirement: "required" },
    { externalRef: "core-teach-a-class", title: "Teach a class", promptText: "If you could teach a class on any one thing, whether academic or otherwise, what would it be?", minWordCount: 100, maxWordCount: 150, requirement: "required" },
    { externalRef: "core-joy", title: "What brings you joy", promptText: "Brown students care deeply about their work and the world around them. Students find contentment, satisfaction, and meaning in daily interactions and major discoveries. Whether big or small, mundane or spectacular, tell us about something that brings you joy.", minWordCount: 100, maxWordCount: 150, requirement: "required" },
    { externalRef: "plme-why-medicine", title: "PLME: Why medicine?", promptText: "Why medicine?", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required in addition to Brown’s four general essays for PLME applicants.", programKey: "program-in-liberal-medical-education-plme", programLabel: "Program in Liberal Medical Education (PLME)" },
    { externalRef: "plme-why-plme", title: "PLME: Why PLME?", promptText: "Why PLME?", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required in addition to Brown’s four general essays for PLME applicants.", programKey: "program-in-liberal-medical-education-plme", programLabel: "Program in Liberal Medical Education (PLME)" },
    { externalRef: "plme-great-doctor", title: "PLME: What will make you a great doctor?", promptText: "Tell us something about yourself, beyond your interest in medicine, that you think will make you a great doctor.", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required in addition to Brown’s four general essays for PLME applicants.", programKey: "program-in-liberal-medical-education-plme", programLabel: "Program in Liberal Medical Education (PLME)" },
    { externalRef: "brown-risd-dual-degree", title: "Brown | RISD Dual Degree", promptText: "The Brown | RISD Dual Degree Program draws on the complementary strengths of Brown University and Rhode Island School of Design (RISD) to provide students with the opportunity to explore and engage with diverse spheres of academic and creative inquiry. Considering your understanding of the academic programs at Brown and RISD, describe how and why the specific blend of RISD’s experimental, immersive art and design program and Brown’s wide-ranging courses and curricula could constitute an optimal undergraduate education for you. Reflect on how you might integrate or synthesize content, approaches, and methods from these two distinct learning experiences. Additionally, how might you contribute to the Dual Degree community and its commitment to interdisciplinary work?", maxWordCount: 650, requirement: "conditional", conditionalNote: "Required in addition to Brown’s four general essays for Brown|RISD Dual Degree applicants.", programKey: "brown-risd-dual-degree-program", programLabel: "Brown | RISD Dual Degree Program" },
  ],
};
