import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const bucknell: SchoolSourceRecord = {
  schoolName: "Bucknell University",
  cycleLabel: "2026–27",
  verificationStatus: "common-app-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://coursecatalog.bucknell.edu/admissions/applyingforadmission/",
  retrievedAt: "2026-08-31",
  note: "Bucknell’s 2026-27 official catalog says no separate supplementary essay is required but also requires “Questions specific to Bucknell University.” Multiple current-cycle sources agree that the 250-word academic-interest/Why Bucknell text field appears in the Academics section rather than the Writing section.",
  prompts: [
    { externalRef: "please-explain-your-interest-in-your-first-choice-major", title: "Please explain your interest in your first-choice major/undecided", promptText: "Please explain your interest in your first-choice major/undecided status and your second-choice major (should you opt to list one) and why you would choose Bucknell University to pursue your interest(s).", maxWordCount: 250, requirement: "required" },
  ],
};
