import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const carleton: SchoolSourceRecord = {
  schoolName: "Carleton College",
  cycleLabel: "2026–27",
  verificationStatus: "common-app-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.admissions.carleton.edu/register/supplement",
  retrievedAt: "2026-08-31",
  note: "A current-cycle secondary record identifies the required 300-word connection-across-difference prompt. Carleton’s live official “Supplement 2026-27” form independently exposes the optional additional-information field but states no limit for it; older sources reported 250 words, so the limit is left null.",
  prompts: [
    { externalRef: "think-about-someone-you-connect-with-who-s-different", title: "Think about someone you connect with who’s different from you", promptText: "Think about someone you connect with who’s different from you. What do you find most meaningful about your interactions with them?", maxWordCount: 300, requirement: "required" },
    { externalRef: "anything-missing", title: "Anything missing", promptText: "Anything missing? Do you want to share more with us? If so, use this space to fill any gaps you think would assist us in reviewing your application.", requirement: "optional", note: "The source states no word or character limit." },
  ],
};
