import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const carnegieMellon: SchoolSourceRecord = {
  schoolName: "Carnegie Mellon University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.cmu.edu/admission/admission/admission-consideration",
  retrievedAt: "2026-08-31",
  note: "CMU’s official admissions page publishes all three short answers and the 300-word maximum. Current-cycle secondary sources corroborate that the set is unchanged for 2026-27.",
  prompts: [
    { externalRef: "short-answer-major-inspiration", title: "Passion behind your intended area of study", promptText: "Most students choose their intended major or area of study based on a passion or inspiration that’s developed over time — what passion or inspiration led you to choose this area of study?", maxWordCount: 300, requirement: "required" },
    { externalRef: "short-answer-successful-college-experience", title: "A successful college experience", promptText: "Many students pursue college for a specific degree, career opportunity or personal goal. Whichever it may be, learning will be critical to achieve your ultimate goal. As you think ahead to the process of learning during your college years, how will you define a successful college experience?", maxWordCount: 300, requirement: "required" },
    { externalRef: "short-answer-emphasize", title: "What you want to emphasize", promptText: "Consider your application as a whole. What do you personally want to emphasize about your application for the admission committee’s consideration? Highlight something that’s important to you or something you haven’t had a chance to share. Tell us, don’t show us (no websites please).", maxWordCount: 300, requirement: "required" },
  ],
};
