import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const caseWesternReserve: SchoolSourceRecord = {
  schoolName: "Case Western Reserve University",
  cycleLabel: "2026–27",
  verificationStatus: "corroborated",
  applicationPlatform: "common-app",
  sourceUrl: "https://case.edu/admission/apply/first-year-applicants",
  retrievedAt: "2026-08-31",
  note: "Case Western’s current official page confirms that general applicants have no school-specific supplement beyond the shared application essay and that PPSP applicants submit two additional essays. Current-cycle secondary sources agree on both PPSP prompts and their limits.",
  prompts: [
    { externalRef: "in-the-college-application-process-you-are-constantly", title: "In the college application process, you are constantly prompted for a", promptText: "In the college application process, you are constantly prompted for a list of your achievements, awards, and accomplishments. While this information is useful to us, we are interested in hearing more about you. Describe an event, achievement, or experience of which you are particularly proud but that will not show up on a resume, may not garner any recognition, and does not appear anywhere else on your admission application.", maxWordCount: 750, requirement: "conditional", conditionalNote: "Required only for Pre-Professional Scholars Program applicants.", programKey: "pre-professional-scholars-program-medicine-or", programLabel: "Pre-Professional Scholars Program (Medicine or Dental Medicine)" },
    { externalRef: "by-applying-to-the-pre-professional-scholars-program", title: "By applying to the Pre-Professional Scholars Program, you are applying", promptText: "By applying to the Pre-Professional Scholars Program, you are applying to gain admission to professional school earlier than students who apply in the traditional way. Please indicate why you’re interested in your chosen profession. How do you see yourself being particularly suited to this field? What events and/or experiences have led you to your choice?", minWordCount: 250, maxWordCount: 500, requirement: "conditional", conditionalNote: "Required only for Pre-Professional Scholars Program applicants.", programKey: "pre-professional-scholars-program-medicine-or", programLabel: "Pre-Professional Scholars Program (Medicine or Dental Medicine)" },
  ],
};
