import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfChicago: SchoolSourceRecord = {
  schoolName: "University of Chicago",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://collegeadmissions.uchicago.edu/apply/essay/",
  retrievedAt: "2026-08-31",
  note: "The official current UChicago admissions page publishes one required 'Why UChicago?' response and six Extended Essay options, of which the applicant chooses exactly one. UChicago does not impose a strict word limit for either response; the current secondary guide agrees on the complete wording and structure.",
  promptGroups: [
    { key: "uchicago-extended-essay", label: "Extended Essay (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "how-does-the-university-of-chicago-as-you-know-it-now", title: "How does the University of Chicago, as you know it now, satisfy your", promptText: "How does the University of Chicago, as you know it now, satisfy your desire for a particular kind of learning, community, and future? Please address with some specificity your own wishes and how they relate to UChicago.", requirement: "required", note: "The source states no word or character limit." },
    { externalRef: "food-for-thought-how-do-thoughts-eat", title: "Food for thought: How do thoughts eat", promptText: "Food for thought: How do thoughts eat?", requirement: "optional", groupKey: "uchicago-extended-essay", note: "The source states no word or character limit." },
    { externalRef: "the-james-webb-space-telescope-launched-in-2021-utilized", title: "The James Webb Space Telescope, launched in 2021, utilized", promptText: "The James Webb Space Telescope, launched in 2021, utilized origami-inspired techniques to compactly store and deploy its sunshield in space. Choose an artistic practice and use its principles to propose an elegant solution to a problem.", requirement: "optional", groupKey: "uchicago-extended-essay", note: "The source states no word or character limit." },
    { externalRef: "sometimes-metaphors-get-mixed-up", title: "Sometimes metaphors get mixed up", promptText: "Sometimes metaphors get mixed up. For one reason or another, one could say, “we’ll burn that bridge when we get there” or “the world is your china shop”. Make up your own mixed metaphor. Explain how it could make sense, be understood, or even applied.", requirement: "optional", groupKey: "uchicago-extended-essay", note: "The source states no word or character limit." },
    { externalRef: "the-olympics-have-long-celebrated-the-pinnacle-of-human", title: "The Olympics have long celebrated the pinnacle of human athletic", promptText: "The Olympics have long celebrated the pinnacle of human athletic achievement. But what if they expanded to honor the mundane? Imagine a new Olympic event built around an everyday activity like speed dishwashing or competitive grocery bagging. How is it scored, officiated, and judged? Why is it a worthy addition?", requirement: "optional", groupKey: "uchicago-extended-essay", note: "The source states no word or character limit." },
    { externalRef: "ai-allen-iverson", title: "AI: Allen Iverson", promptText: "AI: Allen Iverson. NASA, or the North American Saxophone Alliance. Share a potentially confounding, comedic, or captivating example of MIA (Mistaken Identity of Acronym) and tell us its backstory.", requirement: "optional", groupKey: "uchicago-extended-essay", note: "The source states no word or character limit." },
    { externalRef: "and-as-always-the-classic-choose-your-own-adventure", title: "And, as always… the classic choose your own adventure option", promptText: "And, as always… the classic choose your own adventure option! In the spirit of adventurous inquiry, choose one of our past prompts (or create a question of your own). Be original, creative, thought provoking. Draw on your best qualities as a writer, thinker, visionary, social critic, sage, citizen of the world, or future citizen of the University of Chicago; take a little risk, and have fun!", requirement: "optional", groupKey: "uchicago-extended-essay", note: "The source states no word or character limit." },
  ],
};
