import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const claremontMcKenna: SchoolSourceRecord = {
  schoolName: "Claremont McKenna College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.cmc.edu/admission/first-year-application-instructions",
  retrievedAt: "2026-08-31",
  note: "CMC’s current official first-year instructions publish both required prompts. Current 2026-27 secondary evidence supplies the 250-word limit for each. The separate optional video-response prompts are excluded because they are not written responses.",
  prompts: [
    { externalRef: "supplement-why-cmc", title: "Why Claremont McKenna", promptText: "CMC’s mission is to prepare students for thoughtful and productive lives and responsible leadership in business, government, and the professions. With this mission in mind, please explain why you want to attend Claremont McKenna College.", maxWordCount: 250, requirement: "required" },
    { externalRef: "supplement-open-academy-dialogue", title: "Open Academy and constructive dialogue", promptText: "A critical part of fulfilling our mission is living out the commitments of CMC’s Open Academy: Freedom of Expression, Viewpoint Diversity, and Constructive Dialogue. We want to learn more about your commitment to listening and learning from others with different viewpoints, perspectives, and life experiences from your own. Describe a time when engaging with someone about a specific topic resulted in you changing your attitude, belief, or behavior, or you changed the belief or behavior of someone else. What was the change that occurred for you, and what facilitated that change? What did you learn from that experience, and how has it informed how you engage with others?", maxWordCount: 250, requirement: "required" },
  ],
};
