import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const colby: SchoolSourceRecord = {
  schoolName: "Colby College",
  cycleLabel: "2026–27",
  verificationStatus: "no-supplement-confirmed",
  applicationPlatform: "common-app",
  sourceUrl: "https://afa.colby.edu/apply/",
  retrievedAt: "2026-08-31",
  note: "Colby’s current official admissions page affirmatively states: “We do not require any additional writing supplements.” The general Common App, Coalition, or QuestBridge essay is excluded as a shared-platform essay.",
  prompts: [],
};
