import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const colgate: SchoolSourceRecord = {
  schoolName: "Colgate University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.colgate.edu/admission-aid/apply",
  retrievedAt: "2026-08-31",
  note: "The live Common App Explore page for Colgate (official, current-cycle) confirms there are NO Common App writing questions for Colgate -- this was independently re-confirmed and is consistent with the original August 1, 2026 portal check.",
  prompts: [
    { externalRef: "on-colgate-s-campus-students-engage-with-individuals", title: "On Colgate’s campus, students engage with individuals from a variety of", promptText: "On Colgate’s campus, students engage with individuals from a variety of socioeconomic backgrounds, races, ethnicities, religions, and perspectives during the course of their educational and social experiences. In 250 words or less, please share the benefits you see in engaging with a diverse body of students, faculty, and staff as part of your Colgate experience.", minWordCount: 200, maxWordCount: 250, requirement: "optional" },
    { externalRef: "colgate-students-immerse-themselves-in-social-and", title: "Colgate students immerse themselves in social and intellectual pursuits", promptText: "Colgate students immerse themselves in social and intellectual pursuits that inspire them. Tell us in 250 words or less what inspires you and why you want to pursue that at Colgate.", minWordCount: 200, maxWordCount: 250, requirement: "optional" },
    { externalRef: "please-complete-the-following-so-we-can-learn-a-bit", title: "Please complete the following so we can learn a bit more about you", promptText: "Please complete the following so we can learn a bit more about you. Each response should be no more than 13 words. 1. I am fascinated by… 2. My favorite book, movie, or television show is… 3. The person I admire most is… 4. In the future, I hope to… 5. One historical figure I would like to meet is… 6. My favorite food is… 7. One thing I would change is… 8. My favorite place is… 9. I am the best version of myself when… 10. Something that has changed my perspective is… 11. I am seeking a community that… 12. My favorite family/community/cultural tradition is… 13. I am drawn to Colgate University because…", maxWordCount: 13, requirement: "optional", note: "The 13-word maximum applies separately to each of the 13 stems." },
  ],
};
