import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const coloradoCollege: SchoolSourceRecord = {
  schoolName: "Colorado College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.coloradocollege.edu/admission/apply/supplemental-essay.html",
  retrievedAt: "2026-08-31",
  note: "Colorado College’s official page is explicitly labeled 2026-27 and identifies the essay as optional. The separate optional outcome field accepts a document upload or URL, not a written response, so it is excluded.",
  prompts: [
    { externalRef: "optional-deep-focus", title: "The luxury of focus", promptText: "One of the benefits of Colorado College’s Block Plan is the opportunity to immerse yourself fully in a single subject for 3.5 weeks. We see this as the luxury of focus—the joy and value of directing your full attention to one thing. Tell us about a time when you experienced this kind of deep focus in an academic or extracurricular setting. What were you doing, and how did it turn out?", maxWordCount: 300, requirement: "optional" },
  ],
};
