import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const columbia: SchoolSourceRecord = {
  schoolName: "Columbia University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://undergrad.admissions.columbia.edu/apply/process/columbia-questions",
  retrievedAt: "2026-08-31",
  note: "Columbia's official page publishes the six 2026-27 Columbia-specific questions and their exact word limits; these are confirmed current for the 2026-27 cycle (Fall 2027 entry) and corroborated by multiple independent current-cycle secondary sources (College Essay Guy, Ivy Coach, GradGPT, College Essay Advisors).",
  prompts: [
    { externalRef: "list-the-titles-of-texts-resources-and-outlets-that", title: "List the titles of texts, resources and outlets that have contributed", promptText: "List the titles of texts, resources and outlets that have contributed to your intellectual development outside of academic courses, including but not limited to books, journals, websites, podcasts, essays, plays, presentations, videos, museums and other content that you enjoy.", maxWordCount: 100, requirement: "required" },
    { externalRef: "tell-us-about-an-aspect-of-your-life-so-far-or-your", title: "Tell us about an aspect of your life so far or your lived experience", promptText: "Tell us about an aspect of your life so far or your lived experience that is important to you, and describe how it has shaped the way you would learn from and contribute to Columbia's multidimensional and collaborative environment.", maxWordCount: 150, requirement: "required" },
    { externalRef: "at-columbia-students-representing-a-wide-range-of", title: "At Columbia, students representing a wide range of perspectives are", promptText: "At Columbia, students representing a wide range of perspectives are invited to live and learn together. In such a community, questions and debates naturally arise. Please describe a time when you did not agree with someone and discuss how you engaged with them and what you took away from the interaction.", maxWordCount: 150, requirement: "required" },
    { externalRef: "in-college-university-students-are-often-challenged-in", title: "In college/university, students are often challenged in ways that they", promptText: "In college/university, students are often challenged in ways that they could not anticipate. Please describe a situation in which you have navigated through adversity and discuss how you changed as a result.", maxWordCount: 150, requirement: "required" },
    { externalRef: "why-are-you-interested-in-attending-columbia-university", title: "Why are you interested in attending Columbia University", promptText: "Why are you interested in attending Columbia University? We encourage you to consider the aspect(s) that you find unique and compelling about Columbia.", maxWordCount: 150, requirement: "required" },
    { externalRef: "what-attracts-you-to-your-preferred-areas-of-study-at", title: "What attracts you to your preferred areas of study at Columbia College", promptText: "What attracts you to your preferred areas of study at Columbia College or Columbia Engineering?", maxWordCount: 150, requirement: "conditional", conditionalNote: "Required after the applicant selects Columbia College or Columbia Engineering; the application routes the question using the selected undergraduate school.", programKey: "columbia-college-or-columbia-engineering", programLabel: "Columbia College or Columbia Engineering" },
  ],
};
