import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const davidson: SchoolSourceRecord = {
  schoolName: "Davidson College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.davidson.edu/admission-and-financial-aid/apply/first-year-applicants",
  retrievedAt: "2026-08-31",
  note: "Davidson’s live first-year page publishes both required current prompts and their 250–300 word ranges. A current secondary listing still reproduces the older “3,000 colleges” number, but the official live page now says “just under 4,000”; the official wording is used.",
  prompts: [
    { externalRef: "why-davidson", title: "Why Davidson", promptText: "There are just under 4,000 four-year colleges and universities in the United States. Being as specific as possible, what interests you most about Davidson College?", minWordCount: 250, maxWordCount: 300, requirement: "required" },
    { externalRef: "intellectual-curiosity", title: "A curiosity that excites you", promptText: "Davidson encourages students to explore curiosities in and out of the classroom. What is a topic, activity or idea that excites you? Tell us why. Examples may include hobbies, books, interactions, music, podcasts, movies, etc.", minWordCount: 250, maxWordCount: 300, requirement: "required" },
  ],
};
