import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const emory: SchoolSourceRecord = {
  schoolName: "Emory University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://blog.emoryadmission.com/2026/08/emorys-short-answer-questions-2026-27/",
  retrievedAt: "2026-08-31",
  note: "Emory’s official admission blog published the 2026-27 short-answer set on August 1, 2026. Every applicant answers the 200-word academic-interest question and one of four 150-word options. The 200-word figure is labeled a recommended length rather than a hard maximum.",
  promptGroups: [
    { key: "emory-short-answer", label: "Short answer (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "what-academic-areas-are-you-interested-in-exploring-at", title: "What academic areas are you interested in exploring at Emory University", promptText: "What academic areas are you interested in exploring at Emory University and why?", maxWordCount: 200, requirement: "required" },
    { externalRef: "emory-university-has-a-strong-commitment-to-building", title: "Emory University has a strong commitment to building community", promptText: "Emory University has a strong commitment to building community. Tell us about a community that you have been part of where your personal participation helped to change or shape the community for the better.", maxWordCount: 150, requirement: "optional", groupKey: "emory-short-answer" },
    { externalRef: "reflect-on-a-personal-experience-where-you", title: "Reflect on a personal experience where you intentionally expanded your", promptText: "Reflect on a personal experience where you intentionally expanded your cultural awareness.", maxWordCount: 150, requirement: "optional", groupKey: "emory-short-answer" },
    { externalRef: "emory-university-s-unique-mission-calls-for-service-to", title: "Emory University’s unique mission calls for service to humanity", promptText: "Emory University’s unique mission calls for service to humanity. Share how you might personally contribute to this mission of service to humanity.", maxWordCount: 150, requirement: "optional", groupKey: "emory-short-answer" },
    { externalRef: "in-a-scholarly-community-differing-ideas-often-collide", title: "In a scholarly community, differing ideas often collide before they", promptText: "In a scholarly community, differing ideas often collide before they converge. How do you personally navigate disagreement in a way that promotes progress and deepens meaningful dialogue?", maxWordCount: 150, requirement: "optional", groupKey: "emory-short-answer" },
  ],
};
