import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfGeorgia: SchoolSourceRecord = {
  schoolName: "University of Georgia",
  cycleLabel: "2026–27",
  verificationStatus: "no-supplement-confirmed",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.uga.edu/blog/fall-2027-essay-questions/",
  retrievedAt: "2026-08-31",
  note: "UGA's official Fall 2027 announcement confirms there is no UGA-specific general-admission essay beyond the shared Common Application personal essay, which is excluded per this dataset's shared-platform convention.",
  prompts: [],
};
