import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const georgiaTech: SchoolSourceRecord = {
  schoolName: "Georgia Institute of Technology",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://news.em.gatech.edu/2026/07/29/admission-supplemental-essay/",
  retrievedAt: "2026-08-31",
  note: "Georgia Tech officially eliminated its school-specific first-year supplemental essay for the 2026-27 cycle, so there is no general Georgia Tech prompt in this record. The separate B.S. Music Technology portfolio requires an essay as part of the general admission application.",
  prompts: [
    { externalRef: "submit-an-essay-focused-on-your-understanding-of-the", title: "Submit an essay focused on your understanding of the major, your career", promptText: "Submit an essay focused on your understanding of the major, your career goals, and your previous experiences with both performance and music technology.", requirement: "conditional", conditionalNote: "Required only for applicants to the B.S. in Music Technology as part of that major’s portfolio; it is not required of other Georgia Tech applicants.", programKey: "b-s-in-music-technology", programLabel: "B.S. in Music Technology", note: "The source states no word or character limit." },
  ],
};
