import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const grinnell: SchoolSourceRecord = {
  schoolName: "Grinnell College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.grinnell.edu/admission/apply/first-year/requirements",
  retrievedAt: "2026-08-31",
  note: "Grinnell’s official first-year requirements page publishes the optional, recommended short answer and labels the application deadlines 2026-27. The response is submitted after the Common App or QuestBridge application through the Grinnell portal.",
  prompts: [
    { externalRef: "grinnell-s-core-values-include-supporting-a-diverse", title: "Grinnell’s core values include supporting a diverse community that is", promptText: "Grinnell’s core values include supporting a diverse community that is respectful, egalitarian, and committed to the common good. How might your background, respect for the lived experiences of others, and/or eagerness to be exposed to new perspectives equip you to thrive at Grinnell and serve the common good?", minWordCount: 200, maxWordCount: 450, requirement: "optional" },
  ],
};
