import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const hamilton: SchoolSourceRecord = {
  schoolName: "Hamilton College",
  cycleLabel: "2026–27",
  verificationStatus: "corroborated",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.hamilton.edu/admission/apply/first-year",
  retrievedAt: "2026-08-31",
  note: "Hamilton’s official 2026 first-year page classifies the Supplemental Short Answer as an optional application supplement and confirms it is available through Common App, Coalition/Scoir, QuestBridge, or the applicant portal.",
  prompts: [
    { externalRef: "we-each-bring-different-backgrounds-and-perspectives", title: "We each bring different backgrounds and perspectives, and we teach one", promptText: "We each bring different backgrounds and perspectives, and we teach one another about the world through our individual and shared experiences. How will Hamilton shape your perspective, and how will your perspective shape Hamilton?", maxWordCount: 250, requirement: "optional" },
  ],
};
