import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const harvard: SchoolSourceRecord = {
  schoolName: "Harvard University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://college.harvard.edu/guides/application-tips",
  retrievedAt: "2026-08-31",
  note: "Harvard’s live official Application Tips and supplement FAQ pages publish all five required questions and a 150-word limit for each. Multiple explicitly current 2026-27 secondary sources corroborate the set. No honors-college, undergraduate-school, major, international-applicant, or special-program writing branch was identified.",
  prompts: [
    { externalRef: "short-answer-life-experiences", title: "Life experiences and contribution to Harvard", promptText: "Harvard has long recognized the importance of enrolling a student body with a diversity of perspectives and experiences. How will the life experiences that shaped who you are today enable you to contribute to Harvard?", maxWordCount: 150, requirement: "required" },
    { externalRef: "short-answer-disagreement", title: "A strong disagreement", promptText: "Describe a time when you strongly disagreed with someone about an idea or issue. How did you communicate or engage with this person? What did you learn from this experience?", maxWordCount: 150, requirement: "required" },
    { externalRef: "short-answer-activities-shaped-you", title: "Activities, employment, travel, or family responsibilities", promptText: "Briefly describe any of your extracurricular activities, employment experience, travel, or family responsibilities that have shaped who you are.", maxWordCount: 150, requirement: "required" },
    { externalRef: "short-answer-future-use", title: "Using your Harvard education", promptText: "How do you hope to use your Harvard education in the future?", maxWordCount: 150, requirement: "required" },
    { externalRef: "short-answer-roommates", title: "Top 3 things your roommates might like to know", promptText: "Top 3 things your roommates might like to know about you.", maxWordCount: 150, requirement: "required" },
  ],
};
