import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const harveyMudd: SchoolSourceRecord = {
  schoolName: "Harvey Mudd College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.hmc.edu/admission/apply/first-year-students/",
  retrievedAt: "2026-08-31",
  note: "Harvey Mudd’s live official first-year page publishes two required new 2026-27 responses. Current-cycle sources confirm enforced minimums of 150 words for Question 1 and 50 words for Question 2.",
  prompts: [
    { externalRef: "impact-problems-and-community", title: "Experiences, community, and problems to solve", promptText: "The problems that Harvey Mudd College students hope to tackle are shaped by their experiences, values, and communities. Through our intentionally interdisciplinary curriculum and our mission to develop “a clear understanding of the impact of their work,” Mudders develop the skills needed to address these complex challenges and contribute meaningfully to society. Share how an experience you’ve had or community you belong to has shaped the kinds of problems you want to solve and the impact you want to make.", minWordCount: 150, maxWordCount: 500, requirement: "required" },
    { externalRef: "asking-for-help", title: "Asking for help", promptText: "No one succeeds alone, and at Harvey Mudd College, no one expects you to. In and out of the classroom, HMC students are encouraged to embrace challenges, collaborate with one another, and ask for support when they need it. Describe a time when asking for help made a difference in your work or wellbeing. What led you to reach out, and what did you take away from the experience?", minWordCount: 50, maxWordCount: 250, requirement: "required" },
  ],
};
