import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const haverford: SchoolSourceRecord = {
  schoolName: "Haverford College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.haverford.edu/admission/supplement",
  retrievedAt: "2026-08-31",
  note: "Haverford's official Supplement page publishes both required essays with matching text and a 150-200 word limit for each, though the official page itself does not display an explicit '2026-27' label. Two current-cycle secondary sources (College Essay Guy and Ivy Coach), both explicitly labeled 2026-2027, independently reproduce identical prompt text, corroborating that this is the current cycle's set.",
  prompts: [
    { externalRef: "intellectual-curiosity-at-haverford", title: "Intellectual curiosity at Haverford", promptText: "Tell us about a topic or issue that sparks your curiosity and gets you intellectually excited. How do you hope to engage with this topic or issue at Haverford?", minWordCount: 150, maxWordCount: 200, requirement: "required" },
    { externalRef: "community-values-and-honor-code", title: "Community values and the Honor Code", promptText: "We have highlighted for you some of the values that shape the Haverford community. What are some of the values you seek in your next community? How do Haverford's values, as demonstrated through our Honor Code, resonate with you?", minWordCount: 150, maxWordCount: 200, requirement: "required" },
  ],
};
