import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const indianaBloomington: SchoolSourceRecord = {
  schoolName: "Indiana University Bloomington",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://bloomington.iu.edu/admissions/apply/application-faqs.html",
  retrievedAt: "2026-08-31",
  note: "IU Bloomington's official Application FAQs page (redirected from admissions.indiana.edu) states the IU-specific essay verbatim, applicable to applicants using the Apply IU Application; applicants who instead apply via the Common Application satisfy the writing requirement with one of the Common App's own shared personal-statement prompts rather than an IU-specific supplemental prompt.",
  prompts: [
    { externalRef: "in-200-400-words-describe-your-academic-and-career", title: "In 200–400 words, describe your academic and career plans and any", promptText: "In 200–400 words, describe your academic and career plans and any special interest (for example, undergraduate research, academic interests, leadership opportunities, etc.) that you are eager to pursue as an undergraduate at Indiana University. Also, if you encountered any unusual circumstances, challenges, or obstacles in pursuit of your education, you may share those experiences and how you overcame them.", minWordCount: 200, maxWordCount: 400, requirement: "required" },
  ],
};
