import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const johnsHopkins: SchoolSourceRecord = {
  schoolName: "Johns Hopkins University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://apply.jhu.edu/how-to-apply/application-deadlines-requirements/",
  retrievedAt: "2026-08-31",
  note: "JHU's official Application Deadlines & Requirements page explicitly labels this as the \"2026-2027 Supplemental Essay Prompt\" with a 350-word limit. Multiple current-cycle secondary sources (Ivy Coach, GradGPT, College Essay Guy) independently reproduce identical prompt text.",
  prompts: [
    { externalRef: "engaging-across-differences", title: "Engaging across differences and building bridges", promptText: "At Johns Hopkins, community is built through dialogue, collaboration, and a willingness to engage across differences. Whether on campus or in the broader world, community depends on bridge builders who can listen to differing perspectives, challenge their own assumptions, or work together toward shared goals. Drawing on your own experiences, what have you learned about engaging across differences and how has it shaped the way you think about building bridges, enhancing community, and working with others?", minWordCount: 200, maxWordCount: 350, requirement: "required" },
  ],
};
