import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const lehigh: SchoolSourceRecord = {
  schoolName: "Lehigh University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www2.lehigh.edu/admissions/admissions-requirements",
  retrievedAt: "2026-08-31",
  note: "Lehigh requires two Common App / Coalition with Scoir writing-supplement questions for 2026-27 (Fall 2027 entry): 'How did you first learn about Lehigh University and what motivated you to apply?' (200 words) and the 'celebrate the good' prompt (200 words).",
  prompts: [
    { externalRef: "how-did-you-first-learn-about-lehigh-university-and", title: "How did you first learn about Lehigh University and what motivated you", promptText: "How did you first learn about Lehigh University and what motivated you to apply?", maxWordCount: 200, requirement: "required" },
    { externalRef: "at-lehigh-we-believe-in-pausing-to-celebrate-the-good", title: "At Lehigh, we believe in pausing to celebrate the good—meaningful", promptText: "At Lehigh, we believe in pausing to celebrate the good—meaningful moments that bring joy, pride or motivation. What's something great happening in your life right now? It could be an accomplishment, a personal win (big or small) or something you're genuinely excited about. If it matters to you, we'd love to hear about it.", maxWordCount: 200, requirement: "required" },
  ],
};
