import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfMarylandCollegePark: SchoolSourceRecord = {
  schoolName: "University of Maryland, College Park",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.umd.edu/apply/essay-questions",
  retrievedAt: "2026-08-31",
  note: "Maryland requires six required short-answer responses (650 characters each) for the 2026-27 cycle (Fall 2027 entry), confirmed current.",
  prompts: [
    { externalRef: "if-i-could-travel-anywhere-i-would-go-to", title: "If I could travel anywhere, I would go to…", promptText: "If I could travel anywhere, I would go to…", maxCharCount: 650, requirement: "required" },
    { externalRef: "the-most-interesting-fact-i-ever-learned-from-research", title: "The most interesting fact I ever learned from research was…", promptText: "The most interesting fact I ever learned from research was…", maxCharCount: 650, requirement: "required" },
    { externalRef: "in-addition-to-my-major-my-academic-interests-include", title: "In addition to my major, my academic interests include…", promptText: "In addition to my major, my academic interests include…", maxCharCount: 650, requirement: "required" },
    { externalRef: "my-favorite-thing-about-last-tuesday-was", title: "My favorite thing about last Tuesday was…", promptText: "My favorite thing about last Tuesday was…", maxCharCount: 650, requirement: "required" },
    { externalRef: "something-you-might-not-know-about-me-is", title: "Something you might not know about me is…", promptText: "Something you might not know about me is…", maxCharCount: 650, requirement: "required" },
    { externalRef: "because-we-know-that-diversity-benefits-the-educational", title: "Because we know that diversity benefits the educational experience of", promptText: "Because we know that diversity benefits the educational experience of all students, the University of Maryland values diversity in all of its many forms. This includes (but is not limited to) racial, socio-economic, gender, geographical, and sexual orientation. We are interested in hearing about your own individual life experiences. In a few sentences, will you please describe how you have learned, grown, been inspired or developed skills through one or more components of diversity.", maxCharCount: 650, requirement: "required" },
  ],
};
