import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const michiganState: SchoolSourceRecord = {
  schoolName: "Michigan State University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.msu.edu/apply/first-year",
  retrievedAt: "2026-08-31",
  note: "No school-specific supplemental writing prompt exists for general first-year applicants applying via the Common App or Coalition App beyond the shared personal statement. MSU's own direct application portal (explore.msu.edu/apply) separately requires an essay chosen from a menu of topics that functions as the platform-specific equivalent of the shared personal statement, so it is not modeled as a separate prompt here.",
  prompts: [
    { externalRef: "for-roughly-70-years-the-honors-college-has-valued", title: "For roughly 70 years, the Honors College has valued academic", promptText: "For roughly 70 years, the Honors College has valued academic flexibility and innovative approaches to learning. Please tell us about an experience that shows how you have approached your high school career in a unique way.", requirement: "conditional", conditionalNote: "Optional essay for MSU Honors College consideration, submitted only by applicants who are not invited to the Honors College within eight weeks of completing their first-year MSU application and who choose to submit additional materials by the supplemental deadline.", programKey: "msu-honors-college", programLabel: "MSU Honors College", note: "The source states no word or character limit." },
  ],
};
