import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const middlebury: SchoolSourceRecord = {
  schoolName: "Middlebury College",
  cycleLabel: "2026–27",
  verificationStatus: "no-supplement-confirmed",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.middlebury.edu/college/admissions/apply/instructions",
  retrievedAt: "2026-08-31",
  note: "Middlebury's official application instructions page affirmatively states that no supplemental essay is required beyond the essay prompts on the Common Application/Coalition Application itself: \"Use the prompts on the application.",
  prompts: [],
};
