import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const mit: SchoolSourceRecord = {
  schoolName: "Massachusetts Institute of Technology",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "school-specific",
  sourceUrl: "https://mitadmissions.org/apply/firstyear/essays-activities-academics/",
  retrievedAt: "2026-08-31",
  note: "MIT does not use the Common App or Coalition App; applicants apply through MIT's own MyMIT application. The official mitadmissions.org essays/activities/academics page and four independently-authored 2026-27-dated secondary guides (Ivy Coach, College Transitions, College Essay Advisors updated July 29 2026, Dewey Smart updated Aug 18 2026) agree verbatim on all four short-answer questions and on three of the four main essays.",
  prompts: [
    { externalRef: "essay-field-of-study", title: "Field of study that appeals to you", promptText: "What field of study appeals to you the most right now? (Note: Applicants select from a drop-down list.) Reflect on what has led you to this interest.", maxWordCount: 200, requirement: "required" },
    { externalRef: "essay-own-trail", title: "Your own trail", promptText: "While some reach their goals following well-trodden paths, others blaze their own trails achieving the unexpected. In what ways have you done something different than what was expected in your educational journey?", maxWordCount: 200, requirement: "required" },
    { externalRef: "essay-mit-impact", title: "Problems you want to tackle at MIT", promptText: "Reflect on how your personal and academic experiences have influenced the types of problems you would want to tackle with an MIT education, and who you would like to work on those problems with.", maxWordCount: 200, requirement: "required" },
    { externalRef: "essay-unexpected-challenge", title: "An unexpected challenge", promptText: "How did you manage a situation or challenge that you didn't expect? What did you learn from it?", maxWordCount: 200, requirement: "required" },
    { externalRef: "short-answer-fun", title: "Just for fun", promptText: "What do you do just for fun?", maxWordCount: 50, requirement: "required" },
    { externalRef: "short-answer-admire", title: "Someone you admire", promptText: "Who is someone you admire, whether you know them personally or look up to them from afar? Tell us why.", maxWordCount: 50, requirement: "required" },
    { externalRef: "short-answer-topic", title: "A topic you could talk about for hours", promptText: "What's a topic, academic or non-academic, that you could talk about for hours?", maxWordCount: 50, requirement: "required" },
    { externalRef: "short-answer-generalist", title: "Generalist or specialist", promptText: "MIT values both 'generalists' with varied interests and 'specialists' who focus deeply on one or a few passions. Which do you think best describes you, and why?", maxWordCount: 50, requirement: "required" },
  ],
};
