import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const northeastern: SchoolSourceRecord = {
  schoolName: "Northeastern University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.northeastern.edu/application-information/required-materials/",
  retrievedAt: "2026-08-31",
  note: "Northeastern's official admissions pages and multiple current-cycle secondary sources agree that Northeastern requires no general supplemental essay for first-year applicants: only the Common App/Coalition personal statement is required university-wide.",
  prompts: [
    { externalRef: "in-your-portfolio-personal-statement-please-describe", title: "In your portfolio personal statement, please describe what qualities", promptText: "In your portfolio personal statement, please describe what qualities you feel you will bring to the department and your college-level educational experience and why.", maxWordCount: 500, requirement: "conditional", conditionalNote: "For CAMD applicants submitting the optional portfolio for the Art + Design / Media Arts department.", programKey: "art-design-media-arts", programLabel: "Art + Design / Media Arts" },
    { externalRef: "in-your-journalism-portfolio-please-discuss-the", title: "In your Journalism portfolio, please discuss the possibilities you see", promptText: "In your Journalism portfolio, please discuss the possibilities you see in these fields and how you would pursue them.", maxWordCount: 500, requirement: "conditional", conditionalNote: "For CAMD applicants submitting the optional portfolio for the Journalism department.", programKey: "journalism", programLabel: "Journalism" },
    { externalRef: "a-separate-one-page-statement-describing-your-musical", title: "A separate one-page statement describing your musical background", promptText: "A separate one-page statement describing your musical background, influences, and goals as well as why you think the Music Technology program is right for you.", requirement: "conditional", conditionalNote: "Additional requirement for CAMD applicants submitting the optional portfolio for the Music Technology track (on top of the standard 3-5 item portfolio required for all Music tracks).", programKey: "music-technology", programLabel: "Music Technology", note: "The source states no word or character limit." },
  ],
};
