import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const notreDame: SchoolSourceRecord = {
  schoolName: "University of Notre Dame",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.nd.edu/apply/application-overview/",
  retrievedAt: "2026-08-31",
  note: "Notre Dame's official current application overview publishes the complete writing section: one required 150-word essay and exactly two responses chosen from four 50-100 word options.",
  promptGroups: [
    { key: "nd-short-answer", label: "Short answers (choose two)", requiredCount: 2 },
  ],
  prompts: [
    { externalRef: "required-non-negotiables", title: "College-search non-negotiables", promptText: "Everyone has different priorities when considering their higher education options and building their college or university list. Tell us about your “non-negotiable” factor(s) when searching for your future college home.", maxWordCount: 150, requirement: "required" },
    { externalRef: "choice-faith", title: "Faith and decisions", promptText: "How does faith influence the decisions you make?", minWordCount: 50, maxWordCount: 100, requirement: "optional", groupKey: "nd-short-answer" },
    { externalRef: "choice-personal-experiences", title: "Distinctive personal experiences", promptText: "What is distinctive about your personal experiences and development (eg, family support, culture, disability, personal background, community)? Why are these experiences important to you and how will you enrich the Notre Dame community?", minWordCount: 50, maxWordCount: 100, requirement: "optional", groupKey: "nd-short-answer" },
    { externalRef: "choice-service", title: "Service to others", promptText: "Notre Dame’s undergraduate experience is characterized by a collective sense of care for every person. How do you foster service to others in your community?", minWordCount: 50, maxWordCount: 100, requirement: "optional", groupKey: "nd-short-answer" },
    { externalRef: "choice-fight-for", title: "What would you fight for?", promptText: "What would you fight for?", minWordCount: 50, maxWordCount: 100, requirement: "optional", groupKey: "nd-short-answer" },
  ],
};
