import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const nyu: SchoolSourceRecord = {
  schoolName: "New York University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://meet.nyu.edu/advice/application-tips/your-guide-to-the-nyu-supplemental-essay/",
  retrievedAt: "2026-08-31",
  note: "NYU's own admissions-run advice site (meet.nyu.edu) explicitly labels its guide '2026-27' and publishes the full verbatim text of NYU's single general supplemental essay, describing it as optional. Current-cycle secondary sources (Ivy Coach, College Essay Advisors, College Transitions, AdmissionSight) corroborate the same text; College Essay Guy alone characterizes the essay as functionally required, a discrepancy noted on that prompt.",
  prompts: [
    { externalRef: "bridge-builders", title: "Bridge builders", promptText: "We are looking for students who want to be bridge builders—students who can connect people, groups, and ideas to span divides, foster understanding, and promote collaboration within a dynamic, interconnected, and vibrant global academic community. We are eager for you to tell us how your experiences have helped you understand what qualities and efforts are needed to bridge divides so that people can better learn and work together. Please consider one or more of the following questions in your essay: - Tell us about a time you encountered a perspective different from your own. What did you learn—about yourself, the other person, or the world? - Tell us about an experience you've had working with others who have different perspectives. What role did you try to play in helping people to work together, and what did you learn from your efforts? - Tell us about someone you've observed who does a particularly good job helping people think or work together. How does this person set the stage for common exploration or work? What qualities do you admire in this person?", maxWordCount: 250, requirement: "optional" },
    { externalRef: "in-under-250-words-please-share-how-you-have", title: "In under 250 words, please share how you have demonstrated your", promptText: "In under 250 words, please share how you have demonstrated your commitment to the legacy of Dr. King's ideals of 'Beloved Community' as evidenced through academic achievement, research or service.", maxWordCount: 250, requirement: "conditional", conditionalNote: "Applicant opts in to be considered for the Martin Luther King, Jr. Scholars Program via an additional question presented in the Common App.", programKey: "martin-luther-king-jr-scholars-program", programLabel: "Martin Luther King, Jr. Scholars Program" },
    { externalRef: "a-one-page-statement-of-purpose-describing-your-reasons", title: "A one-page Statement of Purpose describing: your reasons for applying", promptText: "A one-page Statement of Purpose describing: your reasons for applying to an interdisciplinary studio art program; your personal and/or academic background in art; and the influences, experiences, common themes, and interests that have impacted your art practice.", requirement: "conditional", conditionalNote: "Required in addition to a portfolio for first-year applicants to the BFA in Studio Art (Art and Art Professions) at NYU Steinhardt.", programKey: "bfa-studio-art-art-and-art-professions", programLabel: "BFA Studio Art / Art and Art Professions", note: "The source states no word or character limit." },
  ],
};
