import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const oberlin: SchoolSourceRecord = {
  schoolName: "Oberlin College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.oberlin.edu/admissions-and-aid/arts-and-sciences/first-year-applicants",
  retrievedAt: "2026-08-31",
  note: "Oberlin's official College of Arts & Sciences admissions page explicitly and currently states, 'Oberlin does not require any additional supplemental essays (hooray!)' — applicants to the College submit only the shared Common App/Coalition personal statement, excluded here as a shared-platform essay per the project convention.",
  prompts: [
    { externalRef: "composition-development", title: "Composition: development and influences", promptText: "Tell us about your development as a composer so far. Include in your response a discussion of composers, specific works of music, and musical styles and genres that have inspired and influenced you.", maxWordCount: 1000, requirement: "conditional", conditionalNote: "Required as part of the Conservatory of Music Applicant Portal supplement for Composition applicants only.", programKey: "composition", programLabel: "Composition" },
    { externalRef: "composition-aspirations", title: "Composition: aspirations", promptText: "Tell us about your aspirations for your creative, academic and professional trajectories. Address such questions as: Why are you pursuing a degree in composition and what do you hope to achieve at Oberlin and beyond?", maxWordCount: 1000, requirement: "conditional", conditionalNote: "Required as part of the Conservatory of Music Applicant Portal supplement for Composition applicants only.", programKey: "composition", programLabel: "Composition" },
    { externalRef: "timara-goals", title: "TIMARA: artistic and academic goals", promptText: "What are your artistic and academic goals for the next four years?", maxWordCount: 1000, requirement: "conditional", conditionalNote: "Required as part of the Conservatory of Music Applicant Portal supplement for TIMARA (Technology in Music and Related Arts) applicants only.", programKey: "timara-technology-in-music-and-related-arts", programLabel: "TIMARA (Technology in Music and Related Arts)" },
  ],
};
