import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const ohioState: SchoolSourceRecord = {
  schoolName: "Ohio State University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://undergrad.osu.edu/apply/freshmen-columbus/common-app",
  retrievedAt: "2026-08-31",
  note: "Ohio State's official first-year application pages confirm there is no general Ohio State-specific writing supplement: applicants respond only to a Common App personal-statement prompt (a shared-platform essay, excluded here per the Colby-style convention).",
  prompts: [
    { externalRef: "if-you-could-devote-the-next-ten-years-to-addressing", title: "If you could devote the next ten years to addressing one challenge", promptText: "If you could devote the next ten years to addressing one challenge facing your community, nation, or the world, what would it be and why?", maxWordCount: 500, requirement: "conditional", conditionalNote: "Required only for applicants completing the separate Stamps Eminence Scholarship Application; applicant must first indicate interest in Honors or Scholars on the Common Application, apply to Ohio State by the November 1 early action deadline, and then complete this separate scholarship application by November 9.", programKey: "stamps-eminence-scholarship-program-university", programLabel: "Stamps Eminence Scholarship Program (University Honors Program)" },
    { externalRef: "in-what-ways-have-your-life-experiences-and-or", title: "In what ways have your life experiences and/or endeavors prepared you", promptText: "In what ways have your life experiences and/or endeavors prepared you to be an active Morrill Scholar who will champion OSU's Shared Values of 'diversity and innovation' and 'inclusion and equity' while investing in our culture of service reflective of our land grant mission? Please answer fully, and when possible, provide specific examples.", minWordCount: 350, maxWordCount: 500, requirement: "conditional", conditionalNote: "Required only for applicants who indicate interest in the Morrill Scholarship Program (MSP) by checking the appropriate box on the Common Application/Ohio State admission application; applicant must be a U.S. citizen or legal permanent resident admitted to the Columbus campus for the autumn semester immediately following high school graduation. Applying by the November 1 early action deadline is strongly recommended for full consideration; the final MSP application deadline extends through January 15.", programKey: "morrill-scholarship-program", programLabel: "Morrill Scholarship Program" },
  ],
};
