import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfPittsburgh: SchoolSourceRecord = {
  schoolName: "University of Pittsburgh",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.pitt.edu/personal-statement/",
  retrievedAt: "2026-08-31",
  note: "Pitt's own admissions FAQ pages (official, admissions.pitt.edu domain) confirm a separate Frederick Honors College essay/'essay prompt' exists and is distinct from the general personal statement -- one FAQ is literally titled around applicants who 'don't want to respond to the essay prompts right now' for Honors, and a second FAQ ('How do I apply for consideration for Frederick Honors College?') instructs applicants to mark interest in Pitt Honors and then 'respond to the Pitt Honors essay prompt that will show up on your application.' This shows the admissions.pitt.edu/honors/ overview page's silence on a separate prompt is just a holistic-review summary (it lists 'quality of the Common…",
  prompts: [
    { externalRef: "share-information-not-included-elsewhere-in-your", title: "Share information not included elsewhere in your University of", promptText: "Share information not included elsewhere in your University of Pittsburgh admissions application.", maxWordCount: 650, requirement: "conditional", conditionalNote: "The Pitt personal statement or Common App essay is required for scholarship consideration, Frederick Honors College consideration, international students, and test-optional applicants; otherwise optional." },
    { externalRef: "frederick-honors-college-applicants-pitt-honors", title: "Frederick Honors College Applicants: Pitt Honors students are", promptText: "Frederick Honors College Applicants: Pitt Honors students are encouraged to engage deeply with their communities and the world. Describe a topic, issue, or experience that has shaped how you engage with others. How will you continue this exploration as a member of the Frederick Honors College?", maxWordCount: 650, requirement: "conditional", conditionalNote: "Required, in addition to (not instead of) the Pitt personal statement/Common App essay, for any first-year applicant who indicates interest in the Frederick Honors College. This is now confirmed by Pitt's own official admissions FAQ pages, which describe Honors-interested applicants needing to 'respond to the Pitt Honors essay prompt(s)' on their application; the general admissions.pitt.edu/honors/ overview page's holistic-factors summary (which mentions only the personal statement/Common App essay) is a general review-criteria description and does not itemize this separate supplemental…", programKey: "david-c-frederick-honors-college", programLabel: "David C. Frederick Honors College" },
  ],
};
