import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const pitzer: SchoolSourceRecord = {
  schoolName: "Pitzer College",
  cycleLabel: "2026–27",
  verificationStatus: "common-app-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.pitzer.edu/admission-aid/how-apply/first-year-applicants",
  retrievedAt: "2026-08-31",
  note: "Pitzer's official first-year applicants page (which independently confirms it describes the 2026-27 cycle via its 'test-free policy through the 2026-2027 application cycle' statement) publishes a single required Pitzer Writing Supplement with a choice of two 650-word prompts, submitted through the Common App.",
  promptGroups: [
    { key: "pitzer-writing-supplement", label: "Pitzer Writing Supplement (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "core-values", title: "Engaging with a Pitzer core value", promptText: "Reflecting on your involvement throughout high school or within the community, how have you engaged with one of Pitzer's core values?", maxWordCount: 650, requirement: "optional", groupKey: "pitzer-writing-supplement" },
    { externalRef: "college-fit", title: "Your college experience and Pitzer fit", promptText: "Describe what you are looking for from your college experience and why Pitzer would be a good fit for you.", maxWordCount: 650, requirement: "optional", groupKey: "pitzer-writing-supplement" },
    { externalRef: "as-a-mission-driven-institution-we-value-and-celebrate", title: "As a mission-driven institution, we value and celebrate the synergy", promptText: "As a mission-driven institution, we value and celebrate the synergy created by our differences and similarities. We welcome you to write about distinctive aspects of your background, identity, or personal interests that you would bring to Pitzer, and how you plan to engage in our community.", maxWordCount: 250, requirement: "optional" },
  ],
};
