import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const pomona: SchoolSourceRecord = {
  schoolName: "Pomona College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.pomona.edu/admissions/apply/first-year-applicants",
  retrievedAt: "2026-08-31",
  note: "Pomona requires two Pomona-specific writing items: a 150-word Academic Interest Statement, and a 250-word short-response essay for which the applicant chooses one of three options.",
  promptGroups: [
    { key: "pomona-short-response", label: "Short response (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "academic-interest", title: "Academic interest", promptText: "What draws you to the subject(s) you selected as potential major(s)? If undecided, share more about one of your academic passions or interests.", maxWordCount: 150, requirement: "required" },
    { externalRef: "short-response-community-values", title: "Community values and perspectives", promptText: "Pomona is home to a diverse community of faculty, staff and students who, through close ties and collaboration, enable each other to identify and explore their greatest passions. Considering this, respond to one of the following: Reflecting on a community that you are a part of, what values or perspectives from that community would you bring to Pomona?", maxWordCount: 250, requirement: "optional", groupKey: "pomona-short-response" },
    { externalRef: "short-response-outside-classroom", title: "An experience outside the classroom", promptText: "Pomona is home to a diverse community of faculty, staff and students who, through close ties and collaboration, enable each other to identify and explore their greatest passions. Considering this, respond to one of the following: Describe an experience you had outside the classroom that changed the way you think and/or how you engage with your peers. What was that experience and what did you learn from it?", maxWordCount: 250, requirement: "optional", groupKey: "pomona-short-response" },
    { externalRef: "short-response-how-others-see-you", title: "How others would describe you", promptText: "Pomona is home to a diverse community of faculty, staff and students who, through close ties and collaboration, enable each other to identify and explore their greatest passions. Considering this, respond to one of the following: Choose any person or group of people in your life and share how they would describe you.", maxWordCount: 250, requirement: "optional", groupKey: "pomona-short-response" },
  ],
};
