import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const princeton: SchoolSourceRecord = {
  schoolName: "Princeton University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admission.princeton.edu/apply/princeton-specific-questions",
  retrievedAt: "2026-08-31",
  note: "Princeton's official 'Princeton-Specific Questions' admissions page (current, live during the 2026-27 / Fall 2027 cycle — corroborated by Princeton's own 'Standardized Testing Policy Beginning With 2027-28 Admission Cycle' page, which confirms 2026-27 is the current cycle) gives the complete verbatim prompt set, matching College Essay Guy's 2026/2027 guide almost exactly.",
  prompts: [
    { externalRef: "academic-interest-ab", title: "Academic interest (A.B. degree or undecided)", promptText: "As a research institution that also prides itself on its liberal arts curriculum, Princeton allows students to explore areas across the humanities and the arts, the natural sciences, and the social sciences. What academic areas most pique your curiosity, and how do the programs offered at Princeton suit your particular interests?", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required for applicants applying for the A.B. degree or who are undecided, in place of the B.S.E. version of this question.", programKey: "college-of-arts-and-sciences-a-b-undecided", programLabel: "College of Arts and Sciences (A.B. / undecided applicants)" },
    { externalRef: "academic-interest-bse", title: "Academic interest (B.S.E. degree)", promptText: "Please describe why you are interested in studying engineering at Princeton. Include any of your experiences in or exposure to engineering, and how you think the programs offered at the University suit your particular interests.", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required for applicants applying for the B.S.E. (Bachelor of Science in Engineering) degree, in place of the A.B./undecided version of this question.", programKey: "b-s-e-engineering-applicants", programLabel: "B.S.E. (engineering) applicants" },
    { externalRef: "your-voice-1", title: "Your Voice: lived experience", promptText: "Princeton values community and encourages students, faculty, staff and leadership to engage in respectful conversations that can expand their perspectives and challenge their ideas and beliefs. As a prospective member of this community, reflect on how your lived experiences will impact the conversations you will have in the classroom, the dining hall or other campus spaces. What lessons have you learned in life thus far? What will your classmates learn from you? In short, how has your lived experience shaped you?", maxWordCount: 500, requirement: "required" },
    { externalRef: "your-voice-2", title: "Your Voice: service and civic engagement", promptText: "Princeton has a longstanding commitment to understanding our responsibility to society through service and civic engagement. How does your own story intersect with these ideals?", maxWordCount: 250, requirement: "required" },
    { externalRef: "more-about-you-skill", title: "More About You: a new skill", promptText: "What is a new skill you would like to learn in college?", maxWordCount: 50, requirement: "required" },
    { externalRef: "more-about-you-joy", title: "More About You: what brings you joy", promptText: "What brings you joy?", maxWordCount: 50, requirement: "required" },
    { externalRef: "more-about-you-song", title: "More About You: soundtrack of your life", promptText: "What song represents the soundtrack of your life at this moment?", maxWordCount: 50, requirement: "required" },
    { externalRef: "we-ask-all-students-to-submit-a-graded-written-paper", supportingMaterial: "an existing graded school paper, submitted rather than written", title: "We ask all students to submit a graded written paper for consideration", promptText: "We ask all students to submit a graded written paper for consideration as part of their application to Princeton. The paper should be from an academic course in English, social studies or history, from the last three years of secondary school, including senior year. You may send a paper, essay, research paper or in-class essay exam. Papers should be at least one page in length. Please include the entire paper as well as the prompt, the grade you received and any available comments. The paper should be originally written in English (no translations). We prefer expository, thesis-driven analytical writing rather than science research, creative writing, personal narratives or papers mostly focused on data analysis.", requirement: "required", note: "The source states no word or character limit." },
  ],
};
