import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const purdue: SchoolSourceRecord = {
  schoolName: "Purdue University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.admissions.purdue.edu/apply/apply.php",
  retrievedAt: "2026-08-31",
  note: "Purdue's general first-year supplemental prompts (the 'opportunities at Purdue' question, the major/campus-location question, and the conditional alternate-major/campus-location question) remain well corroborated across College Essay Guy, College Essay Advisors, Scholarships360, and College Transitions' current 2026-27-labeled guides and are unchanged from prior review.",
  prompts: [
    { externalRef: "how-will-opportunities-at-purdue-support-your-interests", title: "How will opportunities at Purdue support your interests, both in and", promptText: "How will opportunities at Purdue support your interests, both in and out of the classroom?", maxWordCount: 250, requirement: "required" },
    { externalRef: "briefly-discuss-your-reasons-for-choosing-your-major", title: "Briefly discuss your reasons for choosing your major and your interest", promptText: "Briefly discuss your reasons for choosing your major and your interest in studying at this campus location (Indianapolis or West Lafayette).", maxWordCount: 250, requirement: "required" },
    { externalRef: "briefly-discuss-your-reasons-for-pursuing-the-alternate", title: "Briefly discuss your reasons for pursuing the alternate major and", promptText: "Briefly discuss your reasons for pursuing the alternate major and campus location (Indianapolis or West Lafayette) you have selected.", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required only for applicants who list an alternate major/campus choice on their application.", programKey: "alternate-major", programLabel: "Alternate major or campus choice" },
    { externalRef: "explain-your-vision-ideas-or-goals-for-how-you-hope-to", title: "Explain your vision, ideas, or goals for how you hope to shape your", promptText: "Explain your vision, ideas, or goals for how you hope to shape your honors experience while at Purdue. Please put this in the context of the four pillars which are the foundation of the John Martinson Honors College.", maxWordCount: 500, requirement: "conditional", conditionalNote: "Required only for applicants who indicate interest in the John Martinson Honors College on the Purdue Common Application (must be selected by the Nov. 1 Early Action deadline).", programKey: "john-martinson-honors-college", programLabel: "John Martinson Honors College" },
    { externalRef: "please-describe-the-interdisciplinary-nature-of-your", title: "Please describe the interdisciplinary nature of your chosen field of", promptText: "Please describe the interdisciplinary nature of your chosen field of study and how it complements or supports other fields.", maxWordCount: 500, requirement: "conditional", conditionalNote: "Required only for applicants who indicate interest in the John Martinson Honors College on the Purdue Common Application (must be selected by the Nov. 1 Early Action deadline).", programKey: "john-martinson-honors-college", programLabel: "John Martinson Honors College" },
  ],
};
