import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const reed: SchoolSourceRecord = {
  schoolName: "Reed College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.reed.edu/admission-aid/how-to-apply/",
  retrievedAt: "2026-08-31",
  note: "The official page states a maximum of 'up to 500 words' but does not print an explicit minimum; two current-cycle secondary sources explicitly labeled for the 2026-27 / 2026/2027 cycle (College Essay Advisors and College Essay Guy) both give an identical word-for-word prompt and describe a 200-500 word range, so a 200-word floor is reported by secondary sources though not stated on the official page.",
  prompts: [
    { externalRef: "paideia-class", title: "A Paideia class", promptText: "For one week at the end of January, Reed students upend the traditional classroom hierarchy and teach classes about any topic they love, academic or otherwise. This week is known as Paideia, after the Greek term signifying \"education\"—the complete education of mind, body, and spirit. What would you teach that would contribute to the Reed community?", minWordCount: 200, maxWordCount: 500, requirement: "required" },
  ],
};
