import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const rice: SchoolSourceRecord = {
  schoolName: "Rice University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "questbridge",
  sourceUrl: "https://admission.rice.edu/apply/first-year-domestic-applicants",
  retrievedAt: "2026-08-31",
  note: "Rice's official 'First-Year Domestic Applicants' page explicitly labels its content 'Essay Prompts (2026-2027)' and confirms identical prompts for QuestBridge applicants ('Essay Prompts for students using the QuestBridge application (2026-2027)') and for international applicants.",
  promptGroups: [
    { key: "rice-long-response", label: "500-word response (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "academic-areas", title: "Academic areas at Rice", promptText: "Please explain what draws you to the academic areas you selected above and how you hope to explore them at Rice University.", maxWordCount: 150, requirement: "required" },
    { externalRef: "rice-experience", title: "The Rice experience", promptText: "Based upon your exploration of Rice University, what elements of the Rice experience appeal to you?", maxWordCount: 150, requirement: "required" },
    { externalRef: "community-residential-college", title: "Residential College perspectives", promptText: "The Residential College System is at the heart of Rice student life and is heavily influenced by the particular cultural traditions and unique life experiences each student brings. What life experiences and/or unique perspectives are you looking forward to sharing with fellow Owls in the residential college system?", maxWordCount: 500, requirement: "optional", groupKey: "rice-long-response" },
    { externalRef: "community-change-agents", title: "Joining a community of change agents", promptText: "Rice is strengthened by its diverse community of learning and discovery that produces leaders and change agents across the spectrum of human endeavor. What perspectives shaped by your background, experiences, upbringing, and/or cultural identity inspire you to join our community of change agents at Rice?", maxWordCount: 500, requirement: "optional", groupKey: "rice-long-response" },
    { externalRef: "why-are-you-determined-to-study-architecture", title: "Why are you determined to study architecture", promptText: "Why are you determined to study architecture? Please explain your motivation and describe how your past experiences have led you to apply to the Rice School of Architecture in particular. Have you had an opportunity outside of school—such as an internship, building project, architecture summer program or other experience—that strengthened your interest in the field? If so, please describe how the experience further compels you to pursue a career in architecture.", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required in addition to the general Rice Supplement for applicants to the Rice School of Architecture (BArch).", programKey: "architecture-barch", programLabel: "Architecture (BArch)" },
    { externalRef: "describe-a-building-place-or-city-that-you-have", title: "Describe a building, place, or city that you have encountered and found", promptText: "Describe a building, place, or city that you have encountered and found especially compelling. What specifically captured your attention, and why? In your response, reflect on how this experience has shaped your understanding of architecture and the built environment.", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required in addition to the general Rice Supplement for applicants to the Rice School of Architecture (BArch).", programKey: "architecture-barch", programLabel: "Architecture (BArch)" },
  ],
};
