import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfRichmond: SchoolSourceRecord = {
  schoolName: "University of Richmond",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admission.richmond.edu/process/materials/index.html",
  retrievedAt: "2026-08-31",
  note: "Richmond's current application-materials page identifies the 2026-27 application, and the current prompt guide reproduces the three exact official options and the 350-650 word range. Applicants choose one.",
  promptGroups: [
    { key: "richmond-essay", label: "Essay (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "relentlessly-welcoming", title: "Make a space more welcoming", promptText: "Richmond is a community that strives to be relentlessly welcoming. Tell us about a time you made a space better for other people by helping them feel welcome, heard, included, or supported.", minWordCount: 350, maxWordCount: 650, requirement: "optional", groupKey: "richmond-essay" },
    { externalRef: "ideas-into-actions", title: "Turn ideas into actions", promptText: "Richmond students turn ideas into actions. Tell us about a time you learned by doing, making, building, testing, helping, or leading and what that experience taught you about yourself, the world, or the kind of impact you want to have.", minWordCount: 350, maxWordCount: 650, requirement: "optional", groupKey: "richmond-essay" },
    { externalRef: "unique-spider", title: "Your unique mark on a Spider community", promptText: "Richmond’s mascot is the Spider. Just as you are unique, this singular mascot represents over 52,680 unique species of spiders. Tell us about the communities, experiences, or ambitions that have shaped you into the unique person you are and how you will make your mark as part of a Spider community.", minWordCount: 350, maxWordCount: 650, requirement: "optional", groupKey: "richmond-essay" },
  ],
};
