import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfRochester: SchoolSourceRecord = {
  schoolName: "University of Rochester",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.rochester.edu/applying/how-to-apply/",
  retrievedAt: "2026-08-31",
  note: "Rochester's official site explicitly publishes the new 2026-27 all-applicant essay (unchanged from prior review).",
  prompts: [
    { externalRef: "curiosity-creativity", title: "Combine curiosity, creativity, and Rochester opportunities", promptText: "The University of Rochester is a place where curiosity and creativity meet. How will you combine our academic flexibility and co-curricular opportunities to create an experience that reflects your interests and ambitions?", maxWordCount: 250, requirement: "required" },
    { externalRef: "what-field-area-of-study-are-you-interested-in", title: "What field/area of study are you interested in researching", promptText: "What field/area of study are you interested in researching?", maxWordCount: 20, requirement: "optional", note: "Optional field within the Common Application's Rochester-specific question set. It is gated behind a preceding yes/no toggle asking whether the applicant is interested in pursuing research while enrolled at Rochester; any applicant (first-year, not limited to Combined Degree Program applicants) who answers yes is then shown this 20-word field." },
    { externalRef: "what-relevant-experiences-or-insight-have-led-to-your", title: "What relevant experiences or insight have led to your interest in this", promptText: "What relevant experiences or insight have led to your interest in this particular program? Describe how Rochester’s resources: facilities, faculty, peers and research will meet your academic and personal ambitions. Describe how you see yourself contributing to the challenging field you want to enter as a Rochester graduate.", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required for applicants to a Combined Degree Program (REMS, GEAR, GRADE, HEAL, DDE, or the Business Masters Pathway/BMP). This is a single shared essay used across all Combined Degree Programs rather than a separate program-specific prompt for each program.", programKey: "combined-degree-programs", programLabel: "Combined Degree Programs" },
  ],
};
