import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const rutgers: SchoolSourceRecord = {
  schoolName: "Rutgers University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.rutgers.edu/apply/first-year-applicants",
  retrievedAt: "2026-08-31",
  note: "Rutgers is a single unified admissions system across its New Brunswick, Newark, and Camden campuses; no campus-specific essay differences exist. The official first-year applicant page and the live application portal confirm that the only required essay for general applicants is the standard personal statement (7 shared topic choices via Common App or Rutgers' own application), which is not modeled as a distinct prompt here per this dataset's shared-platform convention.",
  prompts: [
    { externalRef: "to-be-a-rutgers-university-new-brunswick-honors-scholar", title: "To be a Rutgers University–New Brunswick Honors Scholar is to explore", promptText: "To be a Rutgers University–New Brunswick Honors Scholar is to explore, learn, and engage at the highest level. If this describes you, we invite you to examine our website and then apply here by telling us: How have you challenged yourself to embrace new experiences and continue learning about yourself and the world? Also, how will your experiences enhance the Rutgers University–New Brunswick Honors community? Aim for about 500 words.", maxWordCount: 500, requirement: "conditional", conditionalNote: "Applicant checks the box/selects 'Yes' indicating interest in Rutgers Honors community consideration on the Rutgers Application or the Common Application (available to applicants admitted to the School of Arts and Sciences, School of Engineering, School of Environmental and Biological Sciences, Rutgers Business School–New Brunswick, Mason Gross School of the Arts, or Ernest Mario School of Pharmacy at Rutgers–New Brunswick).", programKey: "honors-college", programLabel: "Honors College" },
  ],
};
