import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const scripps: SchoolSourceRecord = {
  schoolName: "Scripps College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.scrippscollege.edu/admission/apply/first-year-applicants",
  retrievedAt: "2026-08-31",
  note: "Scripps requires a 200-word required 'Why Scripps' essay plus a choose-one supplemental essay (150-300 words) selected from three options: a trade-lives prompt, a compromise prompt, and a podcast-topic prompt.",
  promptGroups: [
    { key: "scripps-second-essay", label: "Second supplemental essay (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "why-have-you-chosen-to-apply-to-scripps-college", title: "Why have you chosen to apply to Scripps College", promptText: "Why have you chosen to apply to Scripps College?", maxWordCount: 200, requirement: "required" },
    { externalRef: "if-you-could-trade-lives-with-someone-fictional-or-real", title: "If you could trade lives with someone (fictional or real) for a day", promptText: "If you could trade lives with someone (fictional or real) for a day, who would it be and why?", minWordCount: 150, maxWordCount: 300, requirement: "optional", groupKey: "scripps-second-essay" },
    { externalRef: "tell-us-about-a-time-you-had-to-compromise", title: "Tell us about a time you had to compromise", promptText: "Tell us about a time you had to compromise. What did that experience teach you?", minWordCount: 150, maxWordCount: 300, requirement: "optional", groupKey: "scripps-second-essay" },
    { externalRef: "you-have-just-been-invited-to-host-your-own-podcast", title: "You have just been invited to host your own podcast", promptText: "You have just been invited to host your own podcast. What will you talk about and why did you select that topic?", minWordCount: 150, maxWordCount: 300, requirement: "optional", groupKey: "scripps-second-essay" },
  ],
};
