import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const smith: SchoolSourceRecord = {
  schoolName: "Smith College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.smith.edu/admission-aid/apply-smith/first-year-applicants",
  retrievedAt: "2026-08-31",
  note: "Smith requires a single 250-word residential-curriculum essay asking what personal experiences, background, or abilities an applicant would bring to share with residential neighbors, and what they would hope their neighbors would share in return.",
  prompts: [
    { externalRef: "what-personal-experiences-background-or-abilities-would", title: "What personal experiences, background or abilities would you bring to", promptText: "What personal experiences, background or abilities would you bring to this residential environment to share with your neighbors and what would you hope your neighbors would share with you?", maxWordCount: 250, requirement: "required" },
  ],
};
