import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfSouthernCalifornia: SchoolSourceRecord = {
  schoolName: "University of Southern California",
  cycleLabel: "2026–27",
  verificationStatus: "common-app-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admission.usc.edu/prospective-students/how-to-apply/",
  retrievedAt: "2026-08-31",
  note: "Two independent current 2026-27 sources that checked the live Common App portal agree on the complete USC set: one required academic-interest essay, two optional/conditional essays, and ten short takes. They also agree that the prior-cycle Viterbi and Dornsife questions no longer appear and that no current school-specific writing questions are gated by intended major.",
  prompts: [
    { externalRef: "describe-how-you-plan-to-pursue-your-academic-interests", title: "Describe how you plan to pursue your academic interests and why you", promptText: "Describe how you plan to pursue your academic interests and why you want to explore them at USC specifically. Please feel free to address your first- and second-choice major selections.", maxWordCount: 250, requirement: "required" },
    { externalRef: "the-usc-student-commitment-charges-trojans-to-value", title: "The USC Student Commitment charges Trojans to “value honest, open", promptText: "The USC Student Commitment charges Trojans to “value honest, open communication and robust debate,” and to “champion ideological diversity and embrace freedom of expression.” Describe a time when you disagreed with someone you know about something important to you. Did you change your mind or reach common ground?", maxWordCount: 250, requirement: "optional" },
    { externalRef: "starting-with-the-beginning-of-high-school-secondary", title: "Starting with the beginning of high school/secondary school, if you", promptText: "Starting with the beginning of high school/secondary school, if you have had a gap where you were not enrolled in school during a fall or spring term, please address this gap in your educational history. You do not need to address a summer break.", maxWordCount: 250, requirement: "optional", note: "Optional field intended only for applicants with a fall or spring enrollment gap since the beginning of high school/secondary school." },
    { externalRef: "describe-yourself-in-three-words", title: "Describe yourself in three words", promptText: "Describe yourself in three words.", requirement: "required", note: "Limit: 25 characters per word. 25 characters allowed for each of the three words." },
    { externalRef: "what-is-your-favorite-snack", title: "What is your favorite snack", promptText: "What is your favorite snack?", maxCharCount: 100, requirement: "required" },
    { externalRef: "best-movie-of-all-time", title: "Best movie of all time", promptText: "Best movie of all time", maxCharCount: 100, requirement: "required" },
    { externalRef: "dream-job", title: "Dream job", promptText: "Dream job", maxCharCount: 100, requirement: "required" },
    { externalRef: "if-your-life-had-a-theme-song-what-would-it-be", title: "If your life had a theme song, what would it be", promptText: "If your life had a theme song, what would it be?", maxCharCount: 100, requirement: "required" },
    { externalRef: "dream-trip", title: "Dream trip", promptText: "Dream trip", maxCharCount: 100, requirement: "required" },
    { externalRef: "what-tv-show-will-you-binge-watch-next", title: "What TV show will you binge watch next", promptText: "What TV show will you binge watch next?", maxCharCount: 100, requirement: "required" },
    { externalRef: "which-well-known-person-or-fictional-character-would-be", title: "Which well-known person or fictional character would be your ideal", promptText: "Which well-known person or fictional character would be your ideal roommate?", maxCharCount: 100, requirement: "required" },
    { externalRef: "favorite-book", title: "Favorite book", promptText: "Favorite book", maxCharCount: 100, requirement: "required" },
    { externalRef: "if-you-could-teach-a-class-on-any-topic-what-would-it-be", title: "If you could teach a class on any topic, what would it be", promptText: "If you could teach a class on any topic, what would it be?", maxCharCount: 100, requirement: "required" },
  ],
};
