import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const stanford: SchoolSourceRecord = {
  schoolName: "Stanford University",
  cycleLabel: "2026–27",
  verificationStatus: "corroborated",
  applicationPlatform: "common-app",
  sourceUrl: "https://admission.stanford.edu/apply/first-year/",
  retrievedAt: "2026-08-31",
  note: "Four independent reputable secondary sources -- Ivy Coach, College Essay Guy, College Transitions, and Dewey Smart -- each explicitly labeled for the 2026-27 cycle / Class of 2031 (with College Essay Guy noting an August 3, 2026 update and Dewey Smart noting a July 21, 2026 official-page-as-of check) unanimously agree on the same complete set of 8 prompts: 5 short-answer questions (50-word limit each) and 3 short essays (100-250 word range each).",
  prompts: [
    { externalRef: "short-answer-challenge", title: "Significant challenge society faces", promptText: "What is the most significant challenge that society faces today?", maxWordCount: 50, requirement: "required" },
    { externalRef: "short-answer-summers", title: "Last two summers", promptText: "How did you spend your last two summers?", maxWordCount: 50, requirement: "required" },
    { externalRef: "short-answer-historical-moment", title: "Historical moment you wish you'd witnessed", promptText: "What historical moment or event do you wish you could have witnessed?", maxWordCount: 50, requirement: "required" },
    { externalRef: "short-answer-activity", title: "An extracurricular, job, or responsibility", promptText: "Briefly elaborate on one of your extracurricular activities, a job you hold, or responsibilities you have for your family.", maxWordCount: 50, requirement: "required" },
    { externalRef: "short-answer-five-things", title: "Five things that matter to you", promptText: "List five things that are important to you.", maxWordCount: 50, requirement: "required" },
    { externalRef: "short-essay-learning", title: "Genuinely excited about learning", promptText: "The Stanford community is deeply curious and driven to learn in and out of the classroom. Reflect on an idea or experience that makes you genuinely excited about learning.", minWordCount: 100, maxWordCount: 250, requirement: "required" },
    { externalRef: "short-essay-roommate", title: "Note to your future roommate", promptText: "Virtually all of Stanford's undergraduates live on campus. Write a note to your future roommate that reveals something about you or that will help your roommate – and us – get to know you better.", minWordCount: 100, maxWordCount: 250, requirement: "required" },
    { externalRef: "short-essay-contribution", title: "Distinctive contribution", promptText: "Please describe what aspects of your life experiences, interests and character would help you make a distinctive contribution as an undergraduate to Stanford University.", minWordCount: 100, maxWordCount: 250, requirement: "required" },
  ],
};
