import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const swarthmore: SchoolSourceRecord = {
  schoolName: "Swarthmore College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.swarthmore.edu/admissions-aid/application-materials-deadlines",
  retrievedAt: "2026-08-31",
  note: "A current-cycle secondary source (GradGPT, explicitly dated/verified for the 2026-27 cycle as of August 1, 2026) reports the identical two prompts and limits, and a 2025-26-dated secondary source (Scholarships360) confirms the same prompt language was unchanged the prior cycle, indicating stability.",
  prompts: [
    { externalRef: "what-aspects-of-your-self-identity-or-personal", title: "What aspects of your self-identity or personal background are most", promptText: "What aspects of your self-identity or personal background are most significant to you? Reflecting on the elements of your home, school, or other communities that have shaped your life, explain how you have grown in your ability to navigate differences when engaging with others, or demonstrated your ability to collaborate in communities other than your own.", maxWordCount: 250, requirement: "required" },
    { externalRef: "tell-us-about-a-topic-that-has-fascinated-you-recently", title: "Tell us about a topic that has fascinated you recently – either inside", promptText: "Tell us about a topic that has fascinated you recently – either inside or outside of the classroom. What made you curious about this? Has this topic connected across other areas of your interests? How has this experience shaped you and what encourages you to keep exploring?", maxWordCount: 250, requirement: "required" },
  ],
};
