import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const texasAM: SchoolSourceRecord = {
  schoolName: "Texas A&M University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.tamu.edu/apply/freshman/index.html",
  retrievedAt: "2026-08-31",
  note: "Texas A&M's official freshman admissions page (admissions.tamu.edu/apply/freshman) directly reproduces the full set of required and optional essay/short-answer prompts for freshman applicants, consistent with Fall 2027 cycle dates shown on the same and related official pages (applications open August 1, 2026; October 15, 2026 priority deadline for College Station & McAllen).",
  prompts: [
    { externalRef: "personal-story", title: "Your story", promptText: "Tell us your story. What unique opportunities or challenges have you experienced throughout your high school career that have shaped who you are today?", minWordCount: 10, maxWordCount: 750, requirement: "required" },
    { externalRef: "college-readiness", title: "A life event that prepared you for college", promptText: "Describe a life event which you feel has prepared you to be successful in college.", minWordCount: 10, maxWordCount: 250, requirement: "required" },
    { externalRef: "why-tamu", title: "Why Texas A&M", promptText: "We know you have a lot of options. In a few words, why did you choose to apply to Texas A&M?", maxWordCount: 100, requirement: "required" },
    { externalRef: "life-goals", title: "Life goals and objectives", promptText: "In a few words, what are some of your life goals and objectives?", maxWordCount: 100, requirement: "required" },
    { externalRef: "major-choice", title: "Why your chosen major", promptText: "In a few words, why have you chosen your academic major(s)?", maxWordCount: 100, requirement: "required" },
    { externalRef: "education-plans", title: "Plans beyond a bachelor's degree", promptText: "Briefly describe any educational plans you have beyond earning your bachelor's degree.", maxWordCount: 100, requirement: "required" },
    { externalRef: "additional-context", title: "Additional context", promptText: "Are there experiences or opportunities that have shaped or influenced your abilities or academic record, which you have not already written about?", maxWordCount: 250, requirement: "optional" },
  ],
};
