import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const trinityCollege: SchoolSourceRecord = {
  schoolName: "Trinity College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.trincoll.edu/admissions/undergraduate-admissions/application-process/",
  retrievedAt: "2026-08-31",
  note: "This refers to Trinity College in Hartford, Connecticut (not Trinity University in Texas or Trinity College Dublin). Trinity's official Application Process page states first-year applicants complete the standard Common Application essay plus one optional Trinity-specific short essay under 300 words.",
  prompts: [
    { externalRef: "background-at-trinity", title: "Background and the Trinity community", promptText: "The identities you claim, the challenges you face, and the successes you enjoy shape the background for your college experience to come. What is an aspect of your background that you are excited to share and/or explore as a member of the Trinity community and why?", maxWordCount: 300, requirement: "optional" },
  ],
};
