import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const tufts: SchoolSourceRecord = {
  schoolName: "Tufts University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.tufts.edu/apply/short-answer-questions/",
  retrievedAt: "2026-08-31",
  note: "Two official Tufts sources agree completely: the standing 'Short Answer Questions' page (which itself labels its content for the Class of 2031, i.e. Fall 2027 entry) and a dedicated official admissions-blog post titled 'Tufts' Short Answer Questions for the Class of 2031.' Both confirm the current structure is exactly two required short-answer responses per applicant: a universal 75-150 word engagement question, plus a second 100-200 word question whose content is determined by the applicant's chosen undergraduate school/program (School of Arts & Sciences, School of Engineering, SMFA BFA, or the SMFA+A&S Combined Degree) rather than a free choice among alternative topics.",
  prompts: [
    { externalRef: "college-search-engagement", title: "Learning about and engaging with Tufts", promptText: "Please describe how you have learned about and engaged with Tufts during your college search process.", minWordCount: 75, maxWordCount: 150, requirement: "required" },
    { externalRef: "arts-sciences-assignment", title: "A favorite school assignment", promptText: "Tell us about one of your favorite school assignments in the past two years. What was the assignment and why did you enjoy it?", minWordCount: 100, maxWordCount: 200, requirement: "conditional", conditionalNote: "Required second short-answer response for applicants applying to the School of Arts and Sciences (i.e., not Engineering or SMFA). This is not a choice among alternative topics — it is the fixed prompt for this school.", programKey: "school-of-arts-and-sciences", programLabel: "School of Arts and Sciences" },
    { externalRef: "engineering-project", title: "An engineering or science project", promptText: "Tell us about an engineering or science-related project that you have helped build, design, create, or iterate in the past two years. What was the project and what was your role?", minWordCount: 100, maxWordCount: 200, requirement: "conditional", conditionalNote: "Required second short-answer response for applicants applying to the School of Engineering. This is not a choice among alternative topics — it is the fixed prompt for this school.", programKey: "school-of-engineering", programLabel: "School of Engineering" },
    { externalRef: "bfa-portfolio-piece", title: "A specific portfolio piece", promptText: "Tell us more about a specific piece in your portfolio. What were the ideas you intended to explore, and how did those ideas inform the process of making the piece?", minWordCount: 100, maxWordCount: 200, requirement: "conditional", conditionalNote: "Required second short-answer response for applicants applying to the BFA program at the School of the Museum of Fine Arts (SMFA). This is not a choice among alternative topics — it is the fixed prompt for this program.", programKey: "bfa", programLabel: "BFA" },
    { externalRef: "combined-degree-portfolio", title: "Portfolio and academic inspiration", promptText: "Tell us more about a specific piece in your portfolio. How did an academic course, project, or interest inspire the ideas that you explored in this piece? Or, how did making this piece influence your academic interests?", minWordCount: 100, maxWordCount: 200, requirement: "conditional", conditionalNote: "Required second short-answer response for applicants applying to the Combined Degree (BFA + BA/BS) program between SMFA and the School of Arts and Sciences. This is not a choice among alternative topics — it is the fixed prompt for this program.", programKey: "combined-degree-bfa-ba-bs", programLabel: "Combined Degree (BFA+BA/BS)" },
  ],
};
