import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const tulane: SchoolSourceRecord = {
  schoolName: "Tulane University",
  cycleLabel: "2026–27",
  verificationStatus: "no-supplement-confirmed",
  applicationPlatform: "common-app",
  sourceUrl: "https://admission.tulane.edu/apply/instructions",
  retrievedAt: "2026-08-31",
  note: "Tulane's long-standing 250-word 'Why Tulane?' supplemental essay has been dropped for the 2026-27 cycle (Fall 2027 entry): first-year applicants submit only the shared Common App personal statement, with no Tulane-specific writing supplement.",
  prompts: [],
};
