import type { SchoolSourceRecord } from "../types";

// Penn's official writing page is explicitly headed "2026-27 Short Answer and
// Essay Prompts" and publishes common, school-specific, and specialized-program
// questions together. All writing prompts on that page are represented here.
export const universityOfPennsylvania: SchoolSourceRecord = {
  schoolName: "University of Pennsylvania",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.upenn.edu/how-to-apply/preparing-your-application/writing",
  retrievedAt: "2026-08-24",
  note: "Official Penn Admissions writing page, explicitly labeled '2026-27 Short Answer and Essay Prompts.' Every applicant answers two common prompts and one conditional school-specific prompt. Applicants to listed coordinated dual-degree or specialized programs also answer the applicable program-specific prompts. Huntsman's separate target-language selection is a non-writing dropdown and is therefore not imported as an essay prompt. Common App is recorded as primary platform metadata; Penn also accepts Coalition and QuestBridge.",
  prompts: [
    {
      externalRef: "all-thank-you-note",
      title: "Thank-you note",
      promptText: "Write a short thank-you note to someone you have not yet thanked and would like to acknowledge. (We encourage you to share this note with that person, if possible, and reflect on the experience!)",
      minWordCount: 50,
      maxWordCount: 200,
      requirement: "required",
    },
    {
      externalRef: "all-community",
      title: "Explore community at Penn",
      promptText: "How will you explore community at Penn? Consider how Penn will help shape your perspective, and how your experiences and perspective will help shape Penn.",
      minWordCount: 50,
      maxWordCount: 200,
      requirement: "required",
    },
    {
      externalRef: "school-nursing",
      title: "School-specific: Nursing",
      promptText: "Penn Nursing intends to meet the health needs of society in a global and multicultural world by preparing its students to impact healthcare by advancing science. Why are you applying to Nursing, where do you see yourself professionally in the future, and how will you contribute to our mission of promoting equity in healthcare?",
      minWordCount: 50,
      maxWordCount: 200,
      requirement: "conditional",
      conditionalNote: "Required for applicants selecting Penn Nursing as their single-degree school.",
    },
    {
      externalRef: "school-arts-sciences",
      title: "School-specific: College of Arts and Sciences",
      promptText: "The College of Arts and Sciences is designed to foster discovery and connection. Describe something you are curious about—something you'd like to learn more about or find a new approach to—and how you might pursue that curiosity in the College.",
      minWordCount: 50,
      maxWordCount: 200,
      requirement: "conditional",
      conditionalNote: "Required for applicants selecting the College of Arts and Sciences as their single-degree school.",
    },
    {
      externalRef: "school-wharton",
      title: "School-specific: Wharton",
      promptText: "Wharton prepares its students to make an impact by applying business methods and economic theory to real-world problems, including economic, political, and social issues. Discuss a current issue of importance to you and how you hope a Wharton education would help you explore it.",
      minWordCount: 50,
      maxWordCount: 200,
      requirement: "conditional",
      conditionalNote: "Required for applicants selecting the Wharton School as their single-degree school.",
    },
    {
      externalRef: "school-engineering",
      title: "School-specific: Engineering",
      promptText: "Penn Engineering prepares its students to become leaders in technology by combining a strong foundation in the natural sciences and mathematics with depth of study in focused disciplinary majors. Describe how you plan to pursue your engineering interests at Penn, particularly within the intended major you selected.",
      minWordCount: 50,
      maxWordCount: 200,
      requirement: "conditional",
      conditionalNote: "Required for applicants selecting the School of Engineering and Applied Science as their single-degree school.",
    },
    {
      externalRef: "huntsman-language-experience",
      title: "Huntsman: Target-language experience",
      promptText: "Describe your experience with the target language you selected. You may wish to share the length of time you’ve studied or used this language, how you’ve learned it, the skills you’ve acquired, and/or the skills you still wish to develop. Please also explain why you are interested in studying this language and the region(s) of the world where it is spoken.",
      minWordCount: 50,
      maxWordCount: 200,
      requirement: "conditional",
      conditionalNote: "Required only for applicants to the Huntsman Program in International Studies and Business, in addition to Penn's common prompts.",
    },
    {
      externalRef: "huntsman-global-issue",
      title: "Huntsman: International studies and business",
      promptText: "The Huntsman Program supports the development of globally-minded scholars who become engaged citizens, creative innovators, and ethical leaders in the public, private, and non-profit sectors in the United States and around the world. What draws you to a dual degree in international studies and business, and how would you use what you learn to address a global issue where these two domains intersect?",
      minWordCount: 50,
      maxWordCount: 400,
      requirement: "conditional",
      conditionalNote: "Required only for applicants to the Huntsman Program in International Studies and Business, in addition to Penn's common prompts.",
    },
    {
      externalRef: "lsm-integration",
      title: "LSM: Life sciences and management",
      promptText: "The Vagelos Life Sciences & Management (LSM) program brings together two powerful modes of understanding—scientific inquiry and strategic thinking—to prepare students to engage thoughtfully and creatively with some of the most complex challenges of our time. What questions, problems, or opportunities would you hope to explore through LSM, and how might the integration of life sciences and management shape your approach to them? Focus on the ideas, values, or questions that draw you to this intersection, rather than how LSM might advance your career, and make sure this essay is distinct from your single-degree application.",
      minWordCount: 50,
      maxWordCount: 400,
      requirement: "conditional",
      conditionalNote: "Required only for applicants to the Roy and Diana Vagelos Program in Life Sciences and Management, in addition to Penn's common prompts.",
    },
    {
      externalRef: "mt-engineering-business",
      title: "M&T: Engineering and business perspectives",
      promptText: "Explain how you will use the M&T program to pursue problems or opportunities that require both engineering and business perspectives.",
      minWordCount: 50,
      maxWordCount: 400,
      requirement: "conditional",
      conditionalNote: "Required only for applicants to the Jerome Fisher Program in Management and Technology, in addition to Penn's common prompts.",
    },
    {
      externalRef: "mt-created-built",
      title: "M&T: Something you built",
      promptText: "Describe something you created, designed, improved, or built. What motivated you, and what did you learn from the process?",
      minWordCount: 50,
      maxWordCount: 200,
      requirement: "conditional",
      conditionalNote: "Required only for applicants to the Jerome Fisher Program in Management and Technology, in addition to Penn's common prompts.",
    },
    {
      externalRef: "nhcm-interest",
      title: "NHCM: Nursing and Healthcare Management",
      promptText: "Describe your interest in nursing and health care management, and how Penn's coordinated dual-degree program in nursing and business would help you meet your goals. Please ensure that this essay is distinct from your single-degree application, if applicable.",
      minWordCount: 50,
      maxWordCount: 400,
      requirement: "conditional",
      conditionalNote: "Required only for applicants to the Nursing and Healthcare Management coordinated dual-degree program, in addition to Penn's common prompts.",
    },
    {
      externalRef: "viper-major-combination",
      title: "VIPER: Major combination",
      promptText: "VIPER students pursue dual degrees in science or math and engineering. Which major combination(s) interest you most right now and why? Your response to this prompt is not binding; students often shift majors as they learn more through the program.",
      minWordCount: 50,
      maxWordCount: 200,
      requirement: "conditional",
      conditionalNote: "Required only for applicants to the Roy and Diana Vagelos Integrated Program in Energy Research, in addition to Penn's common prompts.",
    },
    {
      externalRef: "viper-energy-interest",
      title: "VIPER: Energy science and technology",
      promptText: "Describe your interest in the VIPER program, including how any past experiences (academic, research, extracurricular, etc.) have shaped your interest in energy science and technology, and how you envision participation in VIPER fitting into your future goals.",
      minWordCount: 50,
      maxWordCount: 400,
      requirement: "conditional",
      conditionalNote: "Required only for applicants to the Roy and Diana Vagelos Integrated Program in Energy Research, in addition to Penn's common prompts.",
    },
    {
      externalRef: "vic-alignment",
      title: "VIC: Visual and Interactive Computing",
      promptText: "Discuss how your interests align with the Visual and Interactive Computing (VIC) program at the University of Pennsylvania.",
      minWordCount: 400,
      maxWordCount: 650,
      requirement: "conditional",
      conditionalNote: "Required only for applicants to the BSE in Visual and Interactive Computing, in addition to Penn's common prompts.",
    },
  ],
};
