import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfNorthCarolinaChapelHill: SchoolSourceRecord = {
  schoolName: "University of North Carolina at Chapel Hill",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.unc.edu/short-essays-removed-from-carolinas-2026-2027-application/",
  retrievedAt: "2026-08-31",
  note: "UNC officially removed its two general short-answer questions for 2026-27. The optional 500-word Assured Enrollment Programs response is confirmed current for the 2026-27 cycle (Fall 2027 entry) via UNC's official announcement and independent current-cycle application inventories.",
  prompts: [
    { externalRef: "the-optional-space-below-allows-you-to-share-why-you-re", title: "The optional space below allows you to share why you’re interested in", promptText: "The optional space below allows you to share why you’re interested in the assured enrollment program(s) you’ve selected and how they align with your educational goals.", maxWordCount: 500, requirement: "optional" },
  ],
};
