import type { RawPromptRecord, SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

// One array, seven campuses: the Personal Insight Questions are the same
// eight questions on one application, so they are shared rather than copied.
// validateCanonicalAgreement in ../normalize.ts fails the build if they ever
// drift apart, and sharing the array is what makes that impossible here.
const PERSONAL_INSIGHT_QUESTIONS: RawPromptRecord[] = [
  { externalRef: "piq-1-leadership", title: "PIQ 1: Leadership experience", promptText: "Describe an example of your leadership experience in which you have positively influenced others, helped resolve disputes or contributed to group efforts over time.", maxWordCount: 350, requirement: "optional", groupKey: "uc-piq" },
  { externalRef: "piq-2-creativity", title: "PIQ 2: Creative side", promptText: "Every person has a creative side, and it can be expressed in many ways: problem solving, original and innovative thinking, and artistically, to name a few. Describe how you express your creative side.", maxWordCount: 350, requirement: "optional", groupKey: "uc-piq" },
  { externalRef: "piq-3-talent", title: "PIQ 3: Greatest talent or skill", promptText: "What would you say is your greatest talent or skill? How have you developed and demonstrated that talent over time?", maxWordCount: 350, requirement: "optional", groupKey: "uc-piq" },
  { externalRef: "piq-4-educational-opportunity", title: "PIQ 4: Educational opportunity or barrier", promptText: "Describe how you have taken advantage of a significant educational opportunity or worked to overcome an educational barrier you have faced.", maxWordCount: 350, requirement: "optional", groupKey: "uc-piq" },
  { externalRef: "piq-5-challenge", title: "PIQ 5: Most significant challenge", promptText: "Describe the most significant challenge you have faced and the steps you have taken to overcome this challenge. How has this challenge affected your academic achievement?", maxWordCount: 350, requirement: "optional", groupKey: "uc-piq" },
  { externalRef: "piq-6-academic-interest", title: "PIQ 6: An academic subject that inspires you", promptText: "Think about an academic subject that inspires you. Describe how you have furthered this interest inside and/or outside of the classroom.", maxWordCount: 350, requirement: "optional", groupKey: "uc-piq" },
  { externalRef: "piq-7-community", title: "PIQ 7: Made your community a better place", promptText: "What have you done to make your school or your community a better place?", maxWordCount: 350, requirement: "optional", groupKey: "uc-piq" },
  { externalRef: "piq-8-strong-candidate", title: "PIQ 8: What makes you a strong candidate", promptText: "Beyond what has already been shared in your application, what do you believe makes you a strong candidate for admission to the University of California?", maxWordCount: 350, requirement: "optional", groupKey: "uc-piq" },
];

const universityOfCaliforniaBerkeleyExtras: RawPromptRecord[] = [
  { externalRef: "share-with-us-the-world-you-come-from-for-example-your", title: "Share with us the world you come from (for example, your family", promptText: "Share with us the world you come from (for example, your family, school, community, city, or town). What unique experiences from your world motivated you to apply to this business and engineering dual degree program?", maxWordCount: 350, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to Berkeley's Management, Entrepreneurship, & Technology (M.E.T.) dual-degree program (a joint Haas School of Business + College of Engineering major). Submitted through a separate M.E.T. supplemental application in addition to the UC Application and its Personal Insight Questions.", programKey: "management-entrepreneurship-and-technology-m-e-t", programLabel: "Management, Entrepreneurship, & Technology (M.E.T.)" },
];

export const universityOfCaliforniaBerkeley: SchoolSourceRecord = {
  schoolName: "University of California, Berkeley",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "school-specific",
  sourceUrl: "https://admission.universityofcalifornia.edu/how-to-apply/applying-as-a-first-year/personal-insight-questions.html",
  retrievedAt: "2026-08-31",
  note: "UC Berkeley uses the UC Application, not the Common App. The writing requirement for essentially all first-year applicants is the UC system-wide set of 8 Personal Insight Questions (PIQs), of which applicants choose exactly 4 to answer, each limited to 350 words; this is confirmed by the official UC Admissions PIQ page, the official UC PIQ freshman-applicant guide PDF, and a current (2026-27-dated) College Essay Guy guide, all in agreement on the wording of all 8 prompts and the 4-of-8/350-word structure.",
  promptGroups: [
    { key: "uc-piq", label: "Personal Insight Questions (choose four)", requiredCount: 4 },
  ],
  prompts: [...PERSONAL_INSIGHT_QUESTIONS, ...universityOfCaliforniaBerkeleyExtras],
  sharedApplicationKey: "university-of-california",
};

export const universityOfCaliforniaLosAngeles: SchoolSourceRecord = {
  schoolName: "University of California, Los Angeles",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "school-specific",
  sourceUrl: "https://admission.universityofcalifornia.edu/how-to-apply/applying-as-a-first-year/personal-insight-questions.html",
  retrievedAt: "2026-08-31",
  note: "The 8 system-wide UC Personal Insight Questions (choose 4 of 8, 350 words each) are confirmed current for the 2026-27 cycle (Fall 2027 entry) via official UC and UCLA admissions pages.",
  promptGroups: [
    { key: "uc-piq", label: "Personal Insight Questions (choose four)", requiredCount: 4 },
  ],
  prompts: PERSONAL_INSIGHT_QUESTIONS,
  sharedApplicationKey: "university-of-california",
};

export const universityOfCaliforniaDavis: SchoolSourceRecord = {
  schoolName: "University of California, Davis",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "school-specific",
  sourceUrl: "https://admission.universityofcalifornia.edu/how-to-apply/applying-as-a-first-year/personal-insight-questions.html",
  retrievedAt: "2026-08-31",
  note: "University of California, Davis uses the UC Application. First-year applicants answer exactly 4 of the 8 system-wide UC Personal Insight Questions, with a 350-word limit for each response. The live official UC sources establish the complete prompt set, while current 2026-27 secondary guides confirm that the wording and 4-of-8 structure apply to this cycle.",
  promptGroups: [
    { key: "uc-piq", label: "Personal Insight Questions (choose four)", requiredCount: 4 },
  ],
  prompts: PERSONAL_INSIGHT_QUESTIONS,
  sharedApplicationKey: "university-of-california",
};

const universityOfCaliforniaIrvineExtras: RawPromptRecord[] = [
  { externalRef: "a-one-page-self-statement-about-who-you-are-as-a", title: "A one-page self-statement about who you are as a developing artist and", promptText: "A one-page self-statement about who you are as a developing artist and what you hope to learn while at UCI.", requirement: "optional", note: "Limit: 1 page." },
  { externalRef: "we-invite-you-to-submit-examples-of-your-creative-work", title: "We invite you to submit examples of your creative work and a statement", promptText: "We invite you to submit examples of your creative work and a statement about who you are and what aspect of design you’re interested in. The statement about yourself can take any form you choose, including essay, self-tape, song, etc.", requirement: "optional", note: "The source states no word or character limit." },
  { externalRef: "because-so-much-art-is-collaborative-please-include-a", title: "Because so much art is collaborative, please include a sentence or two", promptText: "Because so much art is collaborative, please include a sentence or two with each submission outlining what your specific contribution was.", requirement: "optional", note: "The source states no word or character limit." },
  { externalRef: "a-statement-about-why-directing-your-production-of-the", title: "A statement about why directing your production of the play is", promptText: "A statement about why directing your production of the play is important to you. The statement can either be written (400-500 words) or a self-tape (3-5 minutes).", maxWordCount: 500, requirement: "optional" },
  { externalRef: "we-invite-you-to-submit-a-short-essay-3-5-pages-that", supportingMaterial: "a writing sample, and an already-written essay is explicitly allowed", title: "We invite you to submit a short essay (3-5 pages) that analyzes a", promptText: "We invite you to submit a short essay (3-5 pages) that analyzes a dramatic text, a performance, or another cultural event that excites you. This can be something new, or you are welcome to submit an essay you’re especially proud of.", requirement: "optional", note: "Limit: 5 pages." },
  { externalRef: "a-one-page-self-statement-about-who-you-are-as-a-14", title: "A one-page self-statement about who you are as a developing artist", promptText: "A one-page self-statement about who you are as a developing artist", requirement: "optional", note: "Limit: 1 page." },
  { externalRef: "for-the-following-questions-please-feel-free-to-share", title: "For the following questions, please feel free to share any anecdotes or", promptText: "For the following questions, please feel free to share any anecdotes or personal stories that will provide further insight on your answers. - Please describe what you think are the most important attributes of leadership and please describe how you implement those attributes to your own leadership style. - Please describe what you would consider effective pillars of communication and how has it affected the ways you engage your artistry. - In moments of high stress or uncertainty, what techniques or approaches have you implemented in your daily life that have kept you grounded and how has that approach been implemented into your artistry? - Please describe what collaboration means to you and describe your artistic approach in your *area of interest*. You may submit your answers in either written form (500 words maximum) or as a self-tape response.", maxWordCount: 500, requirement: "optional" },
];

export const universityOfCaliforniaIrvine: SchoolSourceRecord = {
  schoolName: "University of California, Irvine",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "school-specific",
  sourceUrl: "https://admission.universityofcalifornia.edu/how-to-apply/applying-as-a-first-year/personal-insight-questions.html",
  retrievedAt: "2026-08-31",
  note: "UC Irvine uses the UC Application: first-year applicants answer exactly 4 of the 8 UC Personal Insight Questions, each with a 350-word limit. UCI's official current supplemental-application and arts pages also establish current Fall 2027 audition/portfolio pathways.",
  promptGroups: [
    { key: "uc-piq", label: "Personal Insight Questions (choose four)", requiredCount: 4 },
  ],
  prompts: [...PERSONAL_INSIGHT_QUESTIONS, ...universityOfCaliforniaIrvineExtras],
  sharedApplicationKey: "university-of-california",
};

const universityOfCaliforniaSanDiegoExtras: RawPromptRecord[] = [
  { externalRef: "create-an-artist-s-statement-of-no-more-than-500-words", title: "Create an artist’s statement of no more than 500 words that briefly", promptText: "Create an artist’s statement of no more than 500 words that briefly describes your art practice and how your selected Visual Arts program will help to cultivate this practice", maxWordCount: 500, requirement: "optional" },
  { externalRef: "provide-a-previously-written-research-paper-or-paper", supportingMaterial: "a previously written research paper or excerpt", title: "Provide a previously written research paper or paper excerpt (no more", promptText: "Provide a previously written research paper or paper excerpt (no more than three pages) that showcases your interest in art or cultural history and research (you can draw on the disciplines of art history, history, sociology, anthropology, communication, literature and other areas of cultural inquiry).", requirement: "optional", note: "Limit: 3 pages." },
  { externalRef: "provide-a-personal-statement-of-no-more-than-500-words", title: "Provide a personal statement of no more than 500 words that describes", promptText: "Provide a personal statement of no more than 500 words that describes your interest in art history, your future professional goals, and your specific interest in the UCSD Visual Arts department.", maxWordCount: 500, requirement: "optional" },
  { externalRef: "all-applicants-must-submit-a-statement-of-interest-of", title: "All applicants must submit a statement of interest of no more than 500", promptText: "All applicants must submit a statement of interest of no more than 500 words in which you describe your musical experience, and your musical, educational, and career goals.", maxWordCount: 500, requirement: "optional" },
  { externalRef: "please-list-and-describe-each-item-you-upload", supportingMaterial: "a list and description of each portfolio upload", title: "Please list and describe each item you upload", promptText: "Please list and describe each item you upload. If you have collaborated with others, please clearly explain exactly what your role was, and who else participated.", requirement: "optional", note: "The source states no word or character limit." },
  { externalRef: "please-submit-a-1-minute-video-or-a-written-statement", title: "Please submit a 1-minute video OR a written statement of no more than", promptText: "Please submit a 1-minute video OR a written statement of no more than 350 words answering the following prompt: “What sparks your passion and curiosity about this artistic field?” We want to know about your genuine interest in Theatre & Dance.", maxWordCount: 350, requirement: "optional" },
  { externalRef: "please-submit-1-3-examples-of-your-work-that-best", supportingMaterial: "work samples, submitted with a brief description of each", title: "Please submit 1-3 examples of your work that best demonstrates your", promptText: "Please submit 1-3 examples of your work that best demonstrates your experiences in your area of interest. This may include images, text (no more than 800 words), or videos (no more than 3 minutes for all videos combined). Please list and briefly describe each item you upload. Please note if the work is your original piece or how you assisted on the project.", maxWordCount: 800, requirement: "optional" },
];

export const universityOfCaliforniaSanDiego: SchoolSourceRecord = {
  schoolName: "University of California, San Diego",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "school-specific",
  sourceUrl: "https://admission.universityofcalifornia.edu/how-to-apply/applying-as-a-first-year/personal-insight-questions.html",
  retrievedAt: "2026-08-31",
  note: "The 8 system-wide UC Personal Insight Questions are confirmed current for 2026-27. UC San Diego's optional portfolio/audition written-response fields for Visual Arts (Media/Studio/ICAM/Speculative Design and Art History), Music (statement of interest and Music Technology/ICAM-Music item descriptions), and Theatre & Dance are confirmed current for the 2026-27 cycle (Fall 2027 entry).",
  promptGroups: [
    { key: "uc-piq", label: "Personal Insight Questions (choose four)", requiredCount: 4 },
  ],
  prompts: [...PERSONAL_INSIGHT_QUESTIONS, ...universityOfCaliforniaSanDiegoExtras],
  sharedApplicationKey: "university-of-california",
};

const universityOfCaliforniaSantaBarbaraExtras: RawPromptRecord[] = [
  { externalRef: "write-a-letter-to-the-attention-of-the-ccs-art-faculty", title: "Write a letter to the attention of the CCS Art faculty, stating your", promptText: "Write a letter to the attention of the CCS Art faculty, stating your academic interests, your reasons for wanting to study at CCS, and your background in Art. In addition, please describe any aspects of your personal background, accomplishments, or experiences with diversity that you feel are important in evaluating your application. This letter is separate from the essay required in the UC application.", requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "art", programLabel: "Art", note: "The source states no word or character limit." },
  { externalRef: "write-a-letter-to-the-attention-of-the-ccs-biology", title: "Write a letter to the attention of the CCS Biology faculty, stating", promptText: "Write a letter to the attention of the CCS Biology faculty, stating your academic interests, your reasons for wanting to study at CCS, and your background in Biology. If you have a future career goal, explain how you believe CCS will help you reach that goal. This letter is separate from the essay required in the UC application.", requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "biology", programLabel: "Biology", note: "The source states no word or character limit." },
  { externalRef: "write-a-letter-to-the-attention-of-the-ccs-chemistry", title: "Write a letter to the attention of the CCS Chemistry and Biochemistry", promptText: "Write a letter to the attention of the CCS Chemistry and Biochemistry faculty, stating your academic interests, your reasons for wanting to study at CCS, and your background in Chemistry. This letter is separate from the essay required in the UC application.", requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "chemistry-and-biochemistry", programLabel: "Chemistry & Biochemistry", note: "The source states no word or character limit." },
  { externalRef: "write-a-letter-to-the-attention-of-the-ccs-computing", title: "Write a letter to the attention of the CCS Computing faculty, stating", promptText: "Write a letter to the attention of the CCS Computing faculty, stating your academic interests, your reasons for wanting to study at CCS, and your background in Computing. This letter is separate from the essay required in the UC application.", requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "computing", programLabel: "Computing", note: "The source states no word or character limit." },
  { externalRef: "introduce-yourself-and-describe-how-your-interest-in", title: "Introduce yourself and describe how your interest in marine science", promptText: "Introduce yourself and describe how your interest in marine science developed. What specific question, challenge, or opportunity related to the ocean most motivates you today? Explain why science, as opposed to other fields you might study, is the path you're most drawn to. How do you hope to develop the knowledge, skills, and experiences at CCS to pursue your interests in marine science?", maxWordCount: 150, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "marine-science", programLabel: "Marine Science" },
  { externalRef: "describe-an-idea-discovery-experience-or-problem-that", title: "Describe an idea, discovery, experience, or problem that changed the", promptText: "Describe an idea, discovery, experience, or problem that changed the way you think about marine systems. Explain what made it intellectually compelling and how it challenged your assumptions. How has this experience influenced the kinds of questions you want to explore or the impact you hope to have through your work?", maxWordCount: 150, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "marine-science", programLabel: "Marine Science" },
  { externalRef: "tell-us-about-a-project-or-problem-you-pursued-inside", title: "Tell us about a project or problem you pursued inside or outside of a", promptText: "Tell us about a project or problem you pursued inside or outside of a traditional classroom. This could be a research project, a community initiative, creative work, or another self-directed endeavor. Describe your role, how you approached challenges or setbacks, and how the experience shaped your approach to solving complex problems.", maxWordCount: 150, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "marine-science", programLabel: "Marine Science" },
  { externalRef: "ccs-provides-students-unusual-freedom-to-shape-their", title: "CCS provides students unusual freedom to shape their own academic path", promptText: "CCS provides students unusual freedom to shape their own academic path from the start. Describe why this learning environment appeals to you and how you would take advantage of its flexibility. What disciplines, perspectives, or experiences do you hope to integrate into your education, and how would doing so help you pursue your goals? Why is this program more appealing to you than other marine science programs? Be as specific as possible.", maxWordCount: 150, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "marine-science", programLabel: "Marine Science" },
  { externalRef: "describe-a-mathematical-problem-that-challenged-you-and", title: "Describe a mathematical problem that challenged you and what steps you", promptText: "Describe a mathematical problem that challenged you and what steps you took to find a solution.", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "mathematics", programLabel: "Mathematics" },
  { externalRef: "what-kinds-of-mathematics-have-you-been-exposed-to", title: "What kinds of mathematics have you been exposed to beyond calculus, if", promptText: "What kinds of mathematics have you been exposed to beyond calculus, if any?", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "mathematics", programLabel: "Mathematics" },
  { externalRef: "describe-any-mathematical-experiences-or-activities", title: "Describe any mathematical experiences or activities that you have been", promptText: "Describe any mathematical experiences or activities that you have been involved into other than taking high school math classes, if any (for example, math camps, math circle, community college classes, math clubs, math competitions, etc)?", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "mathematics", programLabel: "Mathematics" },
  { externalRef: "what-unique-qualities-and-characteristics-do-you-bring", title: "What unique qualities and characteristics do you bring as an applicant", promptText: "What unique qualities and characteristics do you bring as an applicant that make you a good fit for CCS? How might your unique qualities help you achieve your goals during your time here?", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "mathematics", programLabel: "Mathematics" },
  { externalRef: "why-have-you-chosen-mathematics-as-opposed-to-another", title: "Why have you chosen mathematics as opposed to another exact science or", promptText: "Why have you chosen mathematics as opposed to another exact science or creative activity?", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "mathematics", programLabel: "Mathematics" },
  { externalRef: "if-there-is-anything-else-that-you-feel-is-relevant-for", title: "If there is anything else that you feel is relevant for your", promptText: "If there is anything else that you feel is relevant for your application, please share it here.", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "mathematics", programLabel: "Mathematics" },
  { externalRef: "this-is-not-to-be-taken-lightly", title: "This is not to be taken lightly", promptText: "This is not to be taken lightly! Please type a one to three-page letter, addressed to the CCS Music Composition faculty, that answers the following questions: What is your background in music? When did you begin writing music and why? Why are you interested in studying at the College of Creative Studies? What are your career goals at this point in your life? Do you intend to enter the professional music world? Graduate school? What would you like to be doing five years from now? Ten years? Talk a little bit about your music. Why are you interested in writing music? Who are your major influences? What instrument(s) do you play? How do you go about your compositional process? Where do you feel you are in your creative development?", requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "music-composition", programLabel: "Music Composition", note: "Limit: 3 pages." },
  { externalRef: "it-is-helpful-though-not-required-to-include-a", supportingMaterial: "technical notes per submitted work", title: "It is helpful, though not required, to include a paragraph about each", promptText: "It is helpful, though not required, to include a paragraph about each work submitted. For electronic works, the accompanying information should include technical notes, i.e. what program(s) you used in composing the work; your sound sources, etc., .pdf format is recommended.", requirement: "optional", note: "The source states no word or character limit." },
  { externalRef: "the-letter-of-intent-gives-us-additional-information", title: "The letter of intent gives us additional information about your", promptText: "The letter of intent gives us additional information about your motivation and preparation to study physics in an advanced program. The letter should be written in essay format in your own words and should ideally not exceed two pages. Please address the letter to the CCS Physics Admissions Committee that consists of Physics faculty. Your letter may include anything you feel is relevant to your application, however, please make sure to address the following prompts: - What is your background in physics? (This is a great opportunity to discuss any extracurricular activities in Physics that you participated in). - What is your background in mathematics, specifically calculus? - Why are you interested in studying at the College of Creative Studies? - What are your career goals at this point in your life? What would you like to be doing ten years from now? - Why are you interested in physics? When did you first get interested in Physics? Who (if any) are your major influences?", requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "physics", programLabel: "Physics", note: "Limit: 2 pages." },
  { externalRef: "submit-a-2-3-page-letter-professionally-formatted-and", title: "Submit a 2-3 page letter, professionally formatted and addressed to the", promptText: "Submit a 2-3 page letter, professionally formatted and addressed to the W&L faculty. Your letter should: - Briefly introduce yourself. Who you are, where you are from, your interests, and your goals. - Describe your most recent reading experience (and here we acknowledge that one can read a variety of texts -- from more traditional books and stories to films, music, and multimedia compositions) that changed your understanding of literature, life, and/or language? Are there any works that you wish to emulate or that inspire you as a writer? - Describe your work as a writer so far. What motivates you to write? In what ways have you pursued writing both in school and outside of school? - What kind of work would you like to do as a writer or as a student of literature in the CCS Writing & Literature community? This letter is separate from the essay required in the UC application.", requirement: "conditional", conditionalNote: "Required only for first-year applicants applying to the indicated College of Creative Studies major; submitted in addition to the UC Application and its Personal Insight Questions.", programKey: "writing-and-literature", programLabel: "Writing & Literature", note: "Limit: 3 pages." },
];

export const universityOfCaliforniaSantaBarbara: SchoolSourceRecord = {
  schoolName: "University of California, Santa Barbara",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "school-specific",
  sourceUrl: "https://admission.universityofcalifornia.edu/how-to-apply/applying-as-a-first-year/personal-insight-questions.html",
  retrievedAt: "2026-08-31",
  note: "The system-wide UC PIQs are verified and unchanged. UCSB's College of Creative Studies (CCS) requires a separate major-specific application; all currently published CCS written-response fields are included exactly.",
  promptGroups: [
    { key: "uc-piq", label: "Personal Insight Questions (choose four)", requiredCount: 4 },
  ],
  prompts: [...PERSONAL_INSIGHT_QUESTIONS, ...universityOfCaliforniaSantaBarbaraExtras],
  sharedApplicationKey: "university-of-california",
};

export const universityOfCaliforniaSantaCruz: SchoolSourceRecord = {
  schoolName: "University of California, Santa Cruz",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "school-specific",
  sourceUrl: "https://admission.universityofcalifornia.edu/how-to-apply/applying-as-a-first-year/personal-insight-questions.html",
  retrievedAt: "2026-08-31",
  note: "University of California, Santa Cruz uses the UC Application. First-year applicants answer exactly 4 of the 8 system-wide UC Personal Insight Questions, with a 350-word limit for each response. The live official UC sources establish the complete prompt set, while current 2026-27 secondary guides confirm that the wording and 4-of-8 structure apply to this cycle.",
  promptGroups: [
    { key: "uc-piq", label: "Personal Insight Questions (choose four)", requiredCount: 4 },
  ],
  prompts: PERSONAL_INSIGHT_QUESTIONS,
  sharedApplicationKey: "university-of-california",
};
