import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfMinnesotaTwinCities: SchoolSourceRecord = {
  schoolName: "University of Minnesota Twin Cities",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.tc.umn.edu/apply/application-checklist/application-checklist-freshman",
  retrievedAt: "2026-08-31",
  note: "The general academic-interest field is optional and confirmed via the official first-year application checklist. The School of Nursing's three written prompts and the Dance BA/BFA's two written prompts are confirmed current for the 2026-27 cycle (Fall 2027 entry) via official University of Minnesota pages.",
  prompts: [
    { externalRef: "the-u-of-m-has-8-freshman-admitting-colleges-and-more", title: "The U of M has 8 freshman-admitting colleges and more than 150 majors", promptText: "The U of M has 8 freshman-admitting colleges and more than 150 majors. Please share a few words about what you’d like to study in college, career paths that interest you, or your favorite subjects in school. Please limit your response to 1,000 characters or approximately 150 words. (Your answer will help us get to know you better; it will not be reviewed for writing skills.)", maxCharCount: 1000, requirement: "optional" },
    { externalRef: "why-have-you-chosen-to-pursue-a-nursing-career", title: "Why have you chosen to pursue a nursing career", promptText: "Why have you chosen to pursue a nursing career? Explain how your experiences shaped your decision.", maxCharCount: 1500, requirement: "conditional", conditionalNote: "Required when Nursing is selected as the first-choice major.", programKey: "nursing", programLabel: "Nursing" },
    { externalRef: "how-have-your-studies-prepared-you-for-a-career-in", title: "How have your studies prepared you for a career in nursing", promptText: "How have your studies prepared you for a career in nursing?", maxCharCount: 1500, requirement: "conditional", conditionalNote: "Required when Nursing is selected as the first-choice major.", programKey: "nursing", programLabel: "Nursing" },
    { externalRef: "provide-a-brief-reflection-about-why-you-feel-the", title: "Provide a brief reflection about why you feel the University of", promptText: "Provide a brief reflection about why you feel the University of Minnesota School of Nursing will be the best fit with your degree and career plans.", maxCharCount: 1500, requirement: "conditional", conditionalNote: "Required when Nursing is selected as the first-choice major.", programKey: "nursing", programLabel: "Nursing" },
    { externalRef: "how-would-you-describe-your-current-dance-practice", title: "How would you describe your current dance practice", promptText: "How would you describe your current dance practice?", requirement: "conditional", conditionalNote: "Required as page one of the two-page writing sample for students auditioning for the Dance major.", programKey: "dance-ba-bfa", programLabel: "Dance BA/BFA", note: "Limit: 1 page." },
    { externalRef: "choose-a-video-of-a-dance-performance-that-moves-you", title: "Choose a video of a dance performance that moves you and describe it in", promptText: "Choose a video of a dance performance that moves you and describe it in detail. Why did you choose this piece?", requirement: "conditional", conditionalNote: "Required as page two of the two-page writing sample for students auditioning for the Dance major.", programKey: "dance-ba-bfa", programLabel: "Dance BA/BFA", note: "Limit: 1 page." },
  ],
};
