import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfMiami: SchoolSourceRecord = {
  schoolName: "University of Miami",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.miami.edu/undergraduate/application-process/admission-requirements/freshman/index.html",
  retrievedAt: "2026-08-31",
  note: "The University officially confirms that there is no general first-year supplemental essay for 2026-27. Frost School of Music applicants complete a separate current supplemental application containing the published Frost essay, and Music Engineering and Audio Technology applicants also caption each portfolio item.",
  prompts: [
    { externalRef: "write-a-short-2-3-paragraph-essay-about-what-is", title: "Write a short (2-3 paragraph) essay about what is distinctly appealing", promptText: "Write a short (2-3 paragraph) essay about what is distinctly appealing to you about the Frost degree program to which you're applying.", requirement: "conditional", conditionalNote: "Required in the Frost School of Music supplemental application.", programKey: "all-undergraduate-frost-degree-programs", programLabel: "All undergraduate Frost degree programs", note: "Limit: 3 paragraphs." },
    { externalRef: "include-a-brief-note-or-caption-for-each-item", title: "Include a brief note or caption for each item describing your role, the", promptText: "Include a brief note or caption for each item describing your role, the tools used, and what you learned.", requirement: "conditional", conditionalNote: "Required for each submitted portfolio item from Music Engineering and Audio Technology applicants.", programKey: "music-engineering-and-audio-technology", programLabel: "Music Engineering and Audio Technology", note: "The source states no word or character limit." },
  ],
};
