import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const vanderbiltUniversity: SchoolSourceRecord = {
  schoolName: "Vanderbilt University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.vanderbilt.edu/apply/personal-essay-and-short-answer-prompts/",
  retrievedAt: "2026-08-31",
  note: "Vanderbilt's official pages establish the all-applicant short answer and the additional Peabody College teacher-education response, both confirmed current for the 2026-27 cycle (Fall 2027 entry).",
  prompts: [
    { externalRef: "short-answer-dare-to-grow", title: "Dare to grow", promptText: "Vanderbilt University’s motto, Crescere aude, is Latin for “dare to grow.” In your response, reflect on how one or more aspects of your identity, culture, or background has played a role in your personal growth, and how it will contribute to our campus community as you dare to grow at Vanderbilt.", maxWordCount: 300, requirement: "required" },
    { externalRef: "vanderbilt-university-s-peabody-college-of-education", title: "Vanderbilt University’s Peabody College of Education and Human", promptText: "Vanderbilt University’s Peabody College of Education and Human Development has a rich tradition of excellence in teacher education, preparing students to pursue a research-grounded, practice-intensive program leading to licensure. Students pursuing careers in education spend as much time in the classrooms and hallways of Nashville’s public schools as they do in seminar rooms on campus, observing and working in a variety of community and educational settings. What prior experience with and enthusiasm for the field of education will you bring to Vanderbilt? In your response, reflect on why you want to be an educator.", maxWordCount: 300, requirement: "conditional", conditionalNote: "Required for Peabody applicants selecting Elementary Education, Secondary Education, or Special Education.", programKey: "elementary-education-secondary-education-or", programLabel: "Elementary Education, Secondary Education, or Special Education" },
  ],
};
