import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const vassarCollege: SchoolSourceRecord = {
  schoolName: "Vassar College",
  cycleLabel: "2026–27",
  verificationStatus: "common-app-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.vassar.edu/admission/apply/requirements/",
  retrievedAt: "2026-08-31",
  note: "Two reputable 2026-27 prompt inventories agree on the required choose-one essay and both optional upload fields. Vassar's current official first-year page independently confirms that Your Space is entirely optional.",
  promptGroups: [
    { key: "vassar-essay", label: "Vassar essay (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "at-vassar-we-aim-to-foster-an-inclusive-community", title: "At Vassar, we aim to foster an inclusive community through our", promptText: "At Vassar, we aim to foster an inclusive community through our philosophy of engaged pluralism. Engaged pluralism is rooted in “the conviction that collaborating across differences is necessary for social transformation and critical for the well-being of any community and its members.” In short, we believe it’s our differences that make us stronger. Tell us a little bit about an important part of your identity and how it has shaped your life and/or interactions with others.", maxWordCount: 300, requirement: "optional", groupKey: "vassar-essay" },
    { externalRef: "vassar-is-a-diverse-community-that-inspires-positive", title: "Vassar is a diverse community that inspires positive change through", promptText: "Vassar is a diverse community that inspires positive change through open inquiry, deep dives into society’s most difficult challenges, and collaborative problem solving. We care deeply about one another, the communities that have forged us, and the community we build together on campus. Tell us about the community (or communities) you come from and how it has shaped your lived experiences and identity.", maxWordCount: 300, requirement: "optional", groupKey: "vassar-essay" },
    { externalRef: "if-you-wish-to-provide-details-of-circumstances-not", supportingMaterial: "a file upload for circumstances not reflected elsewhere, or a resume", title: "If you wish to provide details of circumstances not reflected in the", promptText: "If you wish to provide details of circumstances not reflected in the application, please upload a file here. Similarly, if you wish to upload your resume, include it here.", requirement: "optional", note: "The source states no word or character limit." },
    { externalRef: "your-space-is-your-opportunity-to-allow-the-committee", title: "Your Space is your opportunity to allow the Committee on Admission to", promptText: "Your Space is your opportunity to allow the Committee on Admission to learn something about you that you have not addressed in another section of the application. For example, in the past, applicants have shared poetry, short stories, cartoons, digital images of art projects, photography, and collages, and/or links to videos, and short films. It is your space, so if you choose to complete it, send something that is a reflection of you!", requirement: "optional", note: "The source states no word or character limit." },
  ],
};
