import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const villanova: SchoolSourceRecord = {
  schoolName: "Villanova University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.villanova.edu/university/undergraduate-admission/applying-to-villanova/application-essays.html",
  retrievedAt: "2026-08-31",
  note: "Villanova's official 2026-27 page verifies the general first-year choose-one writing supplement (five prompts, one required, ~250 words each) — unchanged from prior review.",
  promptGroups: [
    { key: "villanova-supplement", label: "Writing supplement (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "supplement-equity-justice", title: "Advancing equity and justice", promptText: "As Pope Leo XIV (Villanova Class of 1977) has said, “no one can single-handedly bear the weight of the challenges the world is facing, just as no one is so weak that they cannot play their part.” What have you done to play your part in advancing equity and justice in your community?", maxWordCount: 250, requirement: "optional", groupKey: "villanova-supplement", note: "About 250 words." },
    { externalRef: "supplement-life-lesson", title: "A lesson in life", promptText: "What is a lesson in life that you have learned that you would want to share with others at Villanova?", maxWordCount: 250, requirement: "optional", groupKey: "villanova-supplement", note: "About 250 words." },
    { externalRef: "supplement-new-home", title: "Villanova as your new home", promptText: "\"Villanova\" means \"new home.\" Why do you want to call Villanova your new home?", maxWordCount: 250, requirement: "optional", groupKey: "villanova-supplement", note: "About 250 words." },
    { externalRef: "supplement-ai-common-good", title: "Technology and the common good", promptText: "Villanova embraces Artificial Intelligence (AI) with a commitment to thoughtful, ethical use rooted in our Augustinian mission and values. How do you see technology helping you to lead, serve, and contribute to the common good?", maxWordCount: 250, requirement: "optional", groupKey: "villanova-supplement", note: "About 250 words." },
    { externalRef: "supplement-borrowed-strength", title: "Someone borrowing your strength", promptText: "At Villanova, we often say \"each of us strengthens all of us.\" Please detail a time when someone has borrowed some of your strength in their time of need.", maxWordCount: 250, requirement: "optional", groupKey: "villanova-supplement", note: "About 250 words." },
  ],
};
