import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const virginiaTech: SchoolSourceRecord = {
  schoolName: "Virginia Polytechnic Institute and State University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.vt.edu/admissions/undergraduate/apply/ut-prosim-short-answer-questions.html",
  retrievedAt: "2026-08-31",
  note: "Virginia Tech's official page (explicitly titled for the 2026-27 cycle) confirms all four Ut Prosim Profile short-answer questions are required, 120 words each, for degree-seeking first-year applicants. The Honors College uses the same Virginia Tech application with no separate essay.",
  prompts: [
    { externalRef: "virginia-tech-s-motto-is-ut-prosim-which-means-that-i", title: "Virginia Tech’s motto is “Ut Prosim” which means ‘That I May Serve’", promptText: "Virginia Tech’s motto is “Ut Prosim” which means ‘That I May Serve’. Share how you contribute to a community that is important to you. How long have you been involved? What have you learned and how would you like to share that with others at Virginia Tech?", maxWordCount: 120, requirement: "required" },
    { externalRef: "have-you-had-an-experience-when-you-or-someone-you-know", title: "Have you had an experience when you or someone you know were not being", promptText: "Have you had an experience when you or someone you know were not being included? Did you reach out to anyone for assistance, direction, or resources? Were you able to affect change and/or influence others? Did this experience change your perspective and if so, how?", maxWordCount: 120, requirement: "required" },
    { externalRef: "share-a-time-when-you-were-most-proud-of-yourself", title: "Share a time when you were most proud of yourself either as a role", promptText: "Share a time when you were most proud of yourself either as a role model or when you displayed your leadership. What specific skills did you contribute to the experience? How did others rely on you for guidance? What did you learn about yourself during this time?", maxWordCount: 120, requirement: "required" },
    { externalRef: "describe-a-goal-that-you-have-set-and-the-steps-you", title: "Describe a goal that you have set and the steps you will take to", promptText: "Describe a goal that you have set and the steps you will take to achieve it. What made you set this goal for yourself? What is your timeline to achieve this goal? Who do you seek encouragement or guidance from and how do they support your progress as you work on this goal?", maxWordCount: 120, requirement: "required" },
  ],
};
