import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfVirginia: SchoolSourceRecord = {
  schoolName: "University of Virginia",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admission.virginia.edu/admission/deadlines-instructions",
  retrievedAt: "2026-08-31",
  note: "UVA has no general supplemental writing requirement; only School of Nursing applicants receive an additional prompt, confirmed current for the 2026-27 cycle (Fall 2027 entry) at a 250-word limit.",
  prompts: [
    { externalRef: "describe-a-health-care-related-experience-or-another", title: "Describe a health care-related experience or another significant", promptText: "Describe a health care-related experience or another significant interaction that deepened your interest in studying Nursing.", maxWordCount: 250, requirement: "conditional", conditionalNote: "Required only for applicants to the School of Nursing; not required of other UVA applicants.", programKey: "nursing", programLabel: "Nursing" },
  ],
};
