import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const wakeForest: SchoolSourceRecord = {
  schoolName: "Wake Forest University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.wfu.edu/2026/07/wake-forest-applications-open-august-1-heres-whats-new/",
  retrievedAt: "2026-08-31",
  note: "Wake Forest's official July 2026 announcement establishes the complete 2026-27 written supplement: one required 100-word Why Wake response and, if the applicant opts into the optional written supplement, one response selected from four choices.",
  prompts: [
    { externalRef: "required-why-wake", title: "Why Wake?", promptText: "Why have you decided to apply to Wake Forest? Share with us anything that has made you interested in our institution.", maxWordCount: 100, requirement: "required" },
    { externalRef: "optional-written-books", title: "Five intriguing books", promptText: "List five books you’ve read that have intrigued you.", requirement: "optional", conditionalNote: "Optional written supplement: choose and respond to one of these four prompts.", note: "Limit: 150 characters per book title." },
    { externalRef: "optional-written-curiosity", title: "Intellectual curiosity", promptText: "Tell us what piques your intellectual curiosity or has helped you understand the world’s complexity. This can include a work you’ve read, a project you’ve completed for a class, and even co-curricular activities in which you have been involved.", maxWordCount: 150, requirement: "optional", conditionalNote: "Optional written supplement: choose and respond to one of these four prompts." },
    { externalRef: "optional-written-maya-angelou", title: "A Maya Angelou quote", promptText: "Dr. Maya Angelou, renowned author, poet, civil-rights activist, and former Wake Forest University Reynolds Professor of American Studies, inspired others to celebrate their identities and to honor each person’s dignity. Choose one of Dr. Angelou’s powerful quotes. How does this quote relate to your lived experience or reflect how you plan to contribute to the Wake Forest community?", maxWordCount: 300, requirement: "optional", conditionalNote: "Optional written supplement: choose and respond to one of these four prompts." },
    { externalRef: "optional-written-top-ten", title: "Top Ten List", promptText: "Give us your Top Ten List. (The choice of theme is yours.)", requirement: "optional", conditionalNote: "Optional written supplement: choose and respond to one of these four prompts.", note: "Limit: 100 characters per line." },
  ],
};
