import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfWashington: SchoolSourceRecord = {
  schoolName: "University of Washington",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admit.washington.edu/apply/first-year/how-to-apply/writing-section/",
  retrievedAt: "2026-08-31",
  note: "UW's official current writing page confirms that first-year applicants now submit the standard Common App personal essay and optional Common App context fields; those are not UW-specific prompts and are therefore not duplicated here.",
  prompts: [
    { externalRef: "we-want-to-know-why-you-are-excited-to-push-your", title: "We want to know why you are excited to push your education outside the", promptText: "We want to know why you are excited to push your education outside the areas of academic learning with which you are most comfortable. To help us understand your enthusiasm for exploring different ways of thinking and learning tell us: What do you pay attention to? What is a unique lens through which you see the world? How does that connect to your current interests and future curiosities?", maxWordCount: 450, requirement: "conditional", conditionalNote: "Required for applicants seeking first-year Interdisciplinary Honors admission for Autumn 2027.", programKey: "interdisciplinary-honors", programLabel: "Interdisciplinary Honors" },
  ],
};
