import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const wellesley: SchoolSourceRecord = {
  schoolName: "Wellesley College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.wellesley.edu/admission-aid/apply/first-year-applicants",
  retrievedAt: "2026-08-31",
  note: "Wellesley's current official first-year page publishes the school-specific prompt and confirms it is required for fall 2027 applicants. Current 2026-27 corroboration establishes the two-paragraph, 250-to-400-word range.",
  prompts: [
    { externalRef: "required-bridges-perspectives", title: "Building bridges across perspectives", promptText: "Wellesley students actively seek ways to build bridges and to change the world for the better. Tell us about an experience working with and alongside people of different backgrounds and/or perspectives from your own. Why was this important to you, and what lessons from this will you bring with you to Wellesley?", minWordCount: 250, maxWordCount: 400, requirement: "required" },
  ],
};
