import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const wesleyan: SchoolSourceRecord = {
  schoolName: "Wesleyan University",
  cycleLabel: "2026–27",
  verificationStatus: "no-supplement-confirmed",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.wesleyan.edu/admission/undergraduate-admission/first-year.html",
  retrievedAt: "2026-08-31",
  note: "Wesleyan's current first-year application requirements list the Common Application or Coalition Application, Wesleyan member-specific questions, recommendations, transcripts, and optional arts materials, but publish no Wesleyan-specific essay or short-answer writing field for first-year applicants.",
  prompts: [],
};
