import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const williamAndMary: SchoolSourceRecord = {
  schoolName: "William & Mary",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.wm.edu/admission/undergraduateadmission/how-to-apply/first-year-applicants/application-checklist/essay/",
  retrievedAt: "2026-08-31",
  note: "William & Mary offers six optional short-answer choices (~300 words each); applicants may answer up to two, confirmed current for the 2026-27 cycle (Fall 2027 entry) via convergent independently-authored current-cycle sources.",
  prompts: [
    { externalRef: "are-there-any-particular-communities-that-are-important", title: "Are there any particular communities that are important to you, and how", promptText: "Are there any particular communities that are important to you, and how do you see yourself being a part of our community?", maxWordCount: 300, requirement: "optional", conditionalNote: "Optional: applicants may answer up to two of these six short-answer prompts." },
    { externalRef: "share-more-about-a-personal-academic-interest-or-career", title: "Share more about a personal academic interest or career goal", promptText: "Share more about a personal academic interest or career goal.", maxWordCount: 300, requirement: "optional", conditionalNote: "Optional: applicants may answer up to two of these six short-answer prompts." },
    { externalRef: "how-has-your-family-culture-and-or-background-shaped", title: "How has your family, culture and/or background shaped your lived", promptText: "How has your family, culture and/or background shaped your lived experience?", maxWordCount: 300, requirement: "optional", conditionalNote: "Optional: applicants may answer up to two of these six short-answer prompts." },
    { externalRef: "what-led-to-your-interest-in-william-and-mary", title: "What led to your interest in William & Mary", promptText: "What led to your interest in William & Mary?", maxWordCount: 300, requirement: "optional", conditionalNote: "Optional: applicants may answer up to two of these six short-answer prompts." },
    { externalRef: "tell-us-about-a-challenge-or-adversity-you-ve", title: "Tell us about a challenge or adversity you’ve experienced and how that", promptText: "Tell us about a challenge or adversity you’ve experienced and how that has impacted you as an individual.", maxWordCount: 300, requirement: "optional", conditionalNote: "Optional: applicants may answer up to two of these six short-answer prompts." },
    { externalRef: "if-we-visited-your-town-what-would-you-want-to-show-us", title: "If we visited your town, what would you want to show us", promptText: "If we visited your town, what would you want to show us?", maxWordCount: 300, requirement: "optional", conditionalNote: "Optional: applicants may answer up to two of these six short-answer prompts." },
  ],
};
