import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const williams: SchoolSourceRecord = {
  schoolName: "Williams College",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://www.williams.edu/admission-aid/how-to-apply/first-year/",
  retrievedAt: "2026-08-31",
  note: "Williams officially confirms that it does not require a writing supplement, while publishing several optional or conditional writing submissions: an academic paper, a scientific-research description, theatre writing samples, and studio-art piece descriptions.",
  prompts: [
    { externalRef: "williams-does-not-require-a-writing-supplement", title: "Williams does not require a writing supplement", promptText: "Williams does not require a writing supplement. However, some students feel they do their best writing in an academic essay rather than a narrative piece. If you are interested in submitting an example of your academic writing, please submit a paper on any topic of your choice. It need not be graded, and may be an in-class handwritten assignment. We ask that you include a description of the assignment or prompt. Please do not submit lab reports.", requirement: "optional", note: "The source states no word or character limit." },
    { externalRef: "if-you-ve-pursued-significant-scientific-or", title: "If you’ve pursued significant scientific or mathematical research and", promptText: "If you’ve pursued significant scientific or mathematical research and are considering a research or academic career, we welcome a brief description of your work.", requirement: "optional", note: "Length: brief description; no numeric limit stated." },
    { externalRef: "writing-submit-one-or-more-samples-of-representative", title: "Writing: Submit one or more samples of representative original work", promptText: "Writing: Submit one or more samples of representative original work. Entire selection should not exceed 10 pages.", requirement: "optional", note: "Limit: 10 pages." },
    { externalRef: "please-include-a-short-description-for-each-piece-in", title: "Please include a short description for each piece in your portfolio", promptText: "Please include a short description for each piece in your portfolio when you upload into SlideRoom.", requirement: "conditional", conditionalNote: "Required for each piece when submitting an optional studio art portfolio.", programKey: "studio-art-portfolio", programLabel: "Studio Art Portfolio", note: "Length: short description; no numeric limit stated." },
  ],
};
