import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const universityOfWisconsinMadison: SchoolSourceRecord = {
  schoolName: "University of Wisconsin-Madison",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.wisc.edu/essays/",
  retrievedAt: "2026-08-31",
  note: "UW-Madison's official current essay page publishes both the all-applicant school-specific response and the Universities of Wisconsin Application-only personal essay, with a 650-word maximum for each. Current cycle guides agree that Common App applicants answer only the school-specific UW-Madison response in addition to the Common App personal essay.",
  prompts: [
    { externalRef: "tell-us-why-you-would-like-to-attend-the-university-of", title: "Tell us why you would like to attend the University of Wisconsin–Madison", promptText: "Tell us why you would like to attend the University of Wisconsin–Madison. In addition, please include why you are interested in studying the major(s) you have selected. If you selected undecided, please describe your areas of possible academic interest.", maxWordCount: 650, requirement: "required" },
    { externalRef: "each-student-is-unique", title: "Each student is unique", promptText: "Each student is unique. Please tell us about the particular life experiences, talents, commitments, and/or interests you will bring to our campus.", maxWordCount: 650, requirement: "conditional", conditionalNote: "Required only when applying through the Universities of Wisconsin Application; Common App applicants instead submit a Common App personal essay." },
  ],
};
