import type { SchoolSourceRecord } from "../types";

// GENERATED by scripts/build-catalogue.mts from
// docs/catalogue/master-supplemental-2026-27.json. Do not edit by hand: the
// judgements (dropped rows, choose-N groups, scope) live in
// scripts/catalogue-transform.mts, and re-running the generator overwrites this.

export const yale: SchoolSourceRecord = {
  schoolName: "Yale University",
  cycleLabel: "2026–27",
  verificationStatus: "officially-verified",
  applicationPlatform: "common-app",
  sourceUrl: "https://admissions.yale.edu/essay-topics",
  retrievedAt: "2026-08-31",
  note: "Yale's official 2026-27 essay page establishes the complete platform-specific core set. All applicants answer the 200-word academic-interest response. Common Application and Coalition applicants also answer three 200-character short takes and choose one 400-word essay; QuestBridge applicants do not complete those latter fields.",
  promptGroups: [
    { key: "yale-choose-one", label: "Yale essay (choose one)", requiredCount: 1 },
  ],
  prompts: [
    { externalRef: "short-answer-topic-excites", title: "A topic or idea that excites you", promptText: "Tell us about a topic or idea that excites you and is related to one or more academic areas you selected above. Why are you drawn to it?", maxWordCount: 200, requirement: "required" },
    { externalRef: "short-take-teach-write-create", title: "Short Take: teach, write, or create", promptText: "If you could teach any college course, write a book, or create an original piece of art of any kind, what would it be?", maxCharCount: 200, requirement: "required", note: "Required for Common Application and Coalition Application applicants only; not requested from QuestBridge applicants." },
    { externalRef: "short-take-grow-develop", title: "Short Take: grow or develop", promptText: "What is one aspect of yourself that you hope to grow or develop during college?", maxCharCount: 200, requirement: "required", note: "Required for Common Application and Coalition Application applicants only; not requested from QuestBridge applicants." },
    { externalRef: "short-take-not-elsewhere", title: "Short Take: not included elsewhere", promptText: "What is something about you that is not included anywhere else in your application?", maxCharCount: 200, requirement: "required", note: "Required for Common Application and Coalition Application applicants only; not requested from QuestBridge applicants." },
    { externalRef: "essay-opposing-view", title: "Choose One: an opposing view", promptText: "Reflect on a time you discussed an issue important to you with someone holding an opposing view. Why did you find the experience meaningful?", maxWordCount: 400, requirement: "optional", groupKey: "yale-choose-one" },
    { externalRef: "essay-community", title: "Choose One: a meaningful community", promptText: "Reflect on your membership in a community to which you feel connected. Why is this community meaningful to you? You may define community however you like.", maxWordCount: 400, requirement: "optional", groupKey: "yale-choose-one" },
    { externalRef: "essay-personal-experience", title: "Choose One: personal experience", promptText: "Reflect on an element of your personal experience that you feel will enrich your college. How has it shaped you?", maxWordCount: 400, requirement: "optional", groupKey: "yale-choose-one" },
    { externalRef: "complete-the-stem-research-supplement-form-to-describe", title: "Complete the STEM Research Supplement form to describe your research", promptText: "Complete the STEM Research Supplement form to describe your research and your specific contributions if the work was done in collaboration with others.", requirement: "optional", note: "Length: not publicly stated." },
    { externalRef: "submit-one-or-more-samples-of-your-work-as-an-arts", title: "Submit one or more samples of your work as an arts portfolio and use", promptText: "Submit one or more samples of your work as an arts portfolio and use the arts supplement questionnaire to specify your contributions to making the film.", requirement: "optional", note: "Length: not publicly stated." },
    { externalRef: "use-the-update-admissions-application-form-to-upload-a", title: "Use the Update Admissions Application form to upload a document with a", promptText: "Use the Update Admissions Application form to upload a document with a brief description.", requirement: "optional", note: "Length: brief description; no numeric limit stated." },
  ],
};
