/**
 * Embeds every catalogue prompt once and commits the vectors.
 *
 * Why commit them rather than compute at runtime: they are static data. The
 * catalogue changes when someone edits a source record, not when a student does
 * anything, so recomputing 255 vectors on every match recomputation would be
 * work with a known answer. Committing them also makes the numbers in
 * docs/evaluation/reuse-scoring.md reproducible from the repo alone.
 *
 * Re-run after changing the catalogue, EMBEDDING_MODEL, or the text fed to the
 * model. The output is deterministic for a given model, so an unnecessary run is
 * a no-op diff.
 *
 *   node --experimental-strip-types --import ./scripts/ts-resolve.mjs \
 *     scripts/precompute-prompt-vectors.mts
 */
import { writeFileSync } from "node:fs";

import { EMBEDDING_DIMENSIONS, EMBEDDING_DTYPE, EMBEDDING_MODEL, embedTexts, encodeVector } from "../src/lib/embedding.ts";
import { listCoveredSchoolNames, lookupSchoolSource } from "../src/lib/retrieval/registry.ts";
import { promptEmbeddingText } from "../src/lib/semantic.ts";

const prompts: { school: string; ref: string; text: string }[] = [];
for (const school of listCoveredSchoolNames()) {
  for (const prompt of lookupSchoolSource(school)?.prompts ?? []) {
    prompts.push({ school, ref: prompt.externalRef, text: promptEmbeddingText(prompt.title, prompt.promptText) });
  }
}

console.log(`Embedding ${prompts.length} prompts with ${EMBEDDING_MODEL} (${EMBEDDING_DTYPE})...`);
const vectors = await embedTexts(prompts.map((prompt) => prompt.text));
if (!vectors) {
  console.error("The embedding model could not be loaded, so there is nothing to write.");
  console.error("Install dependencies and allow the first-run model download, then retry.");
  process.exit(1);
}
if (vectors.some((vector) => vector.length !== EMBEDDING_DIMENSIONS)) {
  console.error(`Expected ${EMBEDDING_DIMENSIONS}-dimensional vectors; refusing to write a mismatched file.`);
  process.exit(1);
}

const rows = prompts
  .map((prompt, index) => ({ ...prompt, encoded: encodeVector(vectors[index]) }))
  .sort((a, b) => a.school.localeCompare(b.school) || a.ref.localeCompare(b.ref));

const body = rows.map((row) => `  ["${row.school}", "${row.ref}", "${row.encoded}"],`).join("\n");
writeFileSync("src/lib/retrieval/prompt-vectors.ts", `// GENERATED by scripts/precompute-prompt-vectors.mts. Do not edit by hand.
//
// One int8-quantised, base64-encoded embedding per catalogue prompt, produced by
// ${EMBEDDING_MODEL} (${EMBEDDING_DTYPE}) over the title and prompt text. See
// src/lib/embedding.ts for the encoding and why it is quantised rather than
// stored as JSON floats.
//
// Embeddings are only comparable to others from the same model, so this file and
// EMBEDDING_MODEL change together or not at all.

export const PROMPT_VECTOR_MODEL = ${JSON.stringify(EMBEDDING_MODEL)};

/** [schoolName, externalRef, base64 int8 vector] */
export const PROMPT_VECTORS: [school: string, externalRef: string, encoded: string][] = [
${body}
];
`);
console.log(`Wrote src/lib/retrieval/prompt-vectors.ts (${rows.length} vectors)`);
