/**
 * Case data for the qualitative review in docs/evaluation/qualitative-review.md.
 *
 * Real demo essays scored against the whole catalogue through the same functions
 * the app uses, with every factor, ceiling and similarity exposed so each result
 * can be judged rather than trusted. Selection deliberately favours borderline
 * and suspicious cases: obvious successes tell you nothing.
 *
 *   node --experimental-strip-types --import ./scripts/ts-resolve.mjs scripts/review-recommendations.mts
 */
import { writeFileSync } from "node:fs";

import { classifyText } from "../src/lib/classification.ts";
import { DEMO_ESSAYS } from "../src/lib/db/demo-workspace.ts";
import { calibrate, cosine, decodeVector, embedTexts } from "../src/lib/embedding.ts";
import { PROMPT_FAMILIES } from "../src/lib/db/taxonomy.ts";
import { type MatchInput, scoreMatch } from "../src/lib/matching.ts";
import { categoryReview } from "../src/lib/retrieval/category-review.ts";
import { PROMPT_VECTORS } from "../src/lib/retrieval/prompt-vectors.ts";
import { listCoveredSchoolNames, lookupSchoolSource } from "../src/lib/retrieval/registry.ts";
import { detectSchoolMentionsIn } from "../src/lib/school-mentions.ts";
import { essayEmbeddingText } from "../src/lib/semantic.ts";
import { wordCount } from "../src/lib/essays.ts";

const slugByName = new Map(PROMPT_FAMILIES.map(([slug, name]) => [name, slug]));
const vectorByKey = new Map(PROMPT_VECTORS.map(([s, r, e]) => [`${s}|${r}`, decodeVector(e)]));

type Prompt = { school: string; ref: string; title: string; text: string; primary: string; families: string[]; tags: string[]; fn: string; min: number | null; max: number | null; vector?: number[] };
const prompts: Prompt[] = [];
for (const school of listCoveredSchoolNames()) {
  for (const p of lookupSchoolSource(school)?.prompts ?? []) {
    const r = categoryReview(school, p.externalRef)!;
    prompts.push({
      school, ref: p.externalRef, title: p.title, text: p.promptText.replace(/\s+/g, " ").trim(),
      primary: r[2], families: r[3], tags: r[4], fn: r[5],
      min: p.minWordCount ?? null, max: p.maxWordCount ?? null,
      vector: vectorByKey.get(`${school}|${p.externalRef}`),
    });
  }
}
const schoolNames = prompts.map((p) => p.school);

const essayTexts = DEMO_ESSAYS.map((e) => essayEmbeddingText(e.title, e.content));
const essayVectors = await embedTexts(essayTexts);
if (!essayVectors) {
  console.error("The embedding model is unavailable; this report needs it. Run once with the model cached.");
  process.exit(1);
}

type Essay = { title: string; primary: string; signals: string[]; words: number; phrases: string[]; vector: number[]; z: Map<string, number> };
const essays: Essay[] = DEMO_ESSAYS.map((e, index) => {
  const derived = classifyText(essayEmbeddingText(e.title, e.content));
  const targets = prompts.filter((p) => p.vector);
  const cal = calibrate(targets.map((p) => cosine(essayVectors[index], p.vector!)));
  return {
    title: e.title,
    primary: slugByName.get(e.family) ?? "other",
    signals: [...new Set([...derived.secondarySlugs, ...derived.tags])],
    words: wordCount(e.content),
    phrases: [...new Set(detectSchoolMentionsIn({ title: e.title, body: e.content }, schoolNames))],
    vector: essayVectors[index],
    z: new Map(targets.map((p, i) => [p.ref, cal[i]])),
  };
});

const input = (essay: Essay, prompt: Prompt): MatchInput => ({
  essayWordCount: essay.words,
  essayPrimaryFamilySlug: essay.primary,
  essaySecondaryFamilySlugs: essay.signals.filter((s) => slugByName.has(s) || PROMPT_FAMILIES.some(([slug]) => slug === s)),
  essayTags: essay.signals,
  essaySchoolSpecificPhrases: essay.phrases,
  essayFunction: null,
  promptSchoolName: prompt.school,
  promptPrimaryFamilySlug: prompt.primary,
  promptSecondaryFamilySlugs: prompt.families,
  promptTags: prompt.tags,
  promptFunction: prompt.fn as never,
  promptMinWordCount: prompt.min,
  promptMaxWordCount: prompt.max,
  semanticZScore: essay.z.get(prompt.ref) ?? null,
});

type Case = { essay: Essay; prompt: Prompt; result: ReturnType<typeof scoreMatch>; z: number; cos: number };
const cases: Case[] = [];
for (const essay of essays) {
  for (const prompt of prompts) {
    if (!prompt.vector) continue;
    cases.push({
      essay, prompt, result: scoreMatch(input(essay, prompt)),
      z: essay.z.get(prompt.ref) ?? 0, cos: cosine(essay.vector, prompt.vector),
    });
  }
}

const out: string[] = [];
const w = (line = "") => out.push(line);
w("# Recommendation cases, for qualitative judgement");
w();
w(`${cases.length.toLocaleString()} pairs: ${essays.length} demo essays against ${prompts.filter((p) => p.vector).length} catalogue prompts,`);
w("scored through the same functions the app uses. Generated by");
w("`scripts/review-recommendations.mts`; the judgements are in qualitative-review.md.");
w();
w("## Essays under test");
w();
w("| Essay | Primary | Words | Derived secondaries | School mentions |");
w("|---|---|---|---|---|");
for (const e of essays) {
  w(`| ${e.title} | ${e.primary} | ${e.words} | ${e.signals.join(", ") || "—"} | ${e.phrases.join(", ") || "—"} |`);
}
w();

function table(title: string, note: string, selected: Case[]) {
  w(`## ${title}`);
  w();
  w(note);
  w();
  w("| # | Essay | Prompt | Essay cat | Prompt cat | cos | z | P | S | Sec | F | Ceiling (binds?) | Score | Band |");
  w("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|");
  for (const [i, c] of selected.entries()) {
    const f = c.result.factors;
    const scoreBand = c.result.score >= 70 ? "reusable-slight-edits" : c.result.score >= 60 ? "reusable-edits" : c.result.score >= 50 ? "reusable-significant-edits" : "new-response";
    const binds = c.result.ceilings.length > 0 && scoreBand !== c.result.recommendedAction;
    w(`| ${i + 1} | ${c.essay.title} | ${c.prompt.school}: ${c.prompt.title} | ${c.essay.primary} | ${c.prompt.primary} | ${c.cos.toFixed(3)} | ${c.z.toFixed(2)} | ${f.primary} | ${f.semantic} | ${f.secondary} | ${f.function} | ${c.result.ceilings.join("; ") || "—"} ${c.result.ceilings.length ? (binds ? "**(binds)**" : "(no)") : ""} | **${c.result.score}** | \`${c.result.recommendedAction}\` |`);
  }
  w();
}

const byScore = [...cases].sort((a, b) => b.result.score - a.result.score);
table("Top 15 overall", "Surprising top-ranked recommendations are the cheapest way to find a broken formula.", byScore.slice(0, 15));
table("Same primary category", "The signal the old formula relied on entirely.", byScore.filter((c) => c.essay.primary === c.prompt.primary).slice(0, 8));
table("Different primary, semantically close", "Where the old formula scored zero and this one may not.", byScore.filter((c) => c.essay.primary !== c.prompt.primary && c.z > 1.5).slice(0, 8));
table("Why Us and Why Major prompts", "Adjacent categories that the review separates and students conflate.", byScore.filter((c) => c.prompt.primary === "why-us" || c.prompt.primary === "why-major").slice(0, 10));
table("Personal Statement prompts", "Only two exist; both should attract broad narrative essays.", byScore.filter((c) => c.prompt.primary === "personal-statement").slice(0, 6));
table("`Other` prompts", "37% of the catalogue and the least reusable category.", byScore.filter((c) => c.prompt.primary === "other").slice(0, 10));
table("Carried by secondary overlap", "Pairs where the secondary factor is doing real work.", byScore.filter((c) => c.result.factors.secondary >= 14).slice(0, 6));
table("High semantic, low composite", "The formula overruling the model. Each one should have a reason.", [...cases].filter((c) => c.z > 2 && c.result.score < 60).sort((a, b) => b.z - a.z).slice(0, 8));
table("High composite, modest semantic", "The formula outvoting a lukewarm model score.", [...cases].filter((c) => c.result.score >= 65 && c.z < 1).sort((a, b) => b.result.score - a.result.score).slice(0, 8));
table("Substantial word-count difference", "Editing cost, which must not move the score.", [...cases].filter((c) => c.prompt.max !== null && (c.essay.words / c.prompt.max > 2.5 || c.essay.words / c.prompt.max < 0.4) && c.result.score >= 45).sort((a, b) => b.result.score - a.result.score).slice(0, 8));
table("Ceilings that bind", "Where the band is lower than the score allows.", [...cases].filter((c) => {
  const sb = c.result.score >= 70 ? "reusable-slight-edits" : c.result.score >= 60 ? "reusable-edits" : c.result.score >= 50 ? "reusable-significant-edits" : "new-response";
  return sb !== c.result.recommendedAction;
}).sort((a, b) => b.result.score - a.result.score).slice(0, 8));
for (const boundary of [70, 60, 50]) {
  table(`Either side of ${boundary}`, `A ${boundary - 1} and a ${boundary} should be visibly different situations, or the band is not real.`,
    [...cases].filter((c) => Math.abs(c.result.score - boundary) <= 1).sort((a, b) => b.result.score - a.result.score).slice(0, 6));
}
table("Surprising omissions", "Highest-similarity pairs that are NOT recommended.", [...cases].filter((c) => c.result.recommendedAction === "new-response").sort((a, b) => b.z - a.z).slice(0, 10));

w("## Structural: what the score can reach, and what actually limits it");
w();
w("Every pair above shows `Sec 0` and `F 10`. That is not a coincidence of the");
w("sample - it is the normal case, and it collapses the formula into far fewer");
w("distinct outcomes than four factors suggest.");
w();
w("An essay has no recorded function unless it is already assigned to a prompt, so");
w("for any new essay the function factor is a constant 10. Secondary overlap is");
w("zero on 82% of pairs (see secondary-diagnosis.md). What remains is");
w("`25 x [same category] + semantic + 10`:");
w();
w("| Situation | Reachable range | Best case band |");
w("|---|---|---|");
w("| Same category, function unknown | 35–70 | `reusable-slight-edits` at exactly 70 |");
w("| Different category, function unknown | 10–45 | `new-response` — **cannot reach the floor** |");
w("| Same category, function known and matching | 45–80 | top band with headroom |");
w("| Different category, function known and matching | 20–55 | `reusable-significant-edits` |");
w();
const distinct = new Map<number, number>();
for (const c of cases) distinct.set(c.result.score, (distinct.get(c.result.score) ?? 0) + 1);
const atExactly70 = distinct.get(70) ?? 0;
const atExactly45 = distinct.get(45) ?? 0;
w(`Measured over ${cases.length.toLocaleString()} pairs: **${atExactly70}** score exactly 70 and **${atExactly45}** score exactly 45.`);
const scoreAt70Plus = cases.filter((c) => c.result.score >= 70).length;
w(`Of the ${scoreAt70Plus} pairs whose score reaches the top band, **${atExactly70}** sit exactly on its`);
w(`boundary (${cases.filter((c) => c.result.recommendedAction === "reusable-slight-edits").length} keep the label after ceilings). One point of a noisy factor`);
w("therefore decides the label for nearly every one of the best recommendations,");
w("which is a fragile place for the ranking to pile up.");
w();
w("### What supplying an essay function would do");
w();
w("The onboarding work already proposes capturing which prompt an essay was");
w("written for. This bounds the effect of that, by rescoring every pair with the");
w("function factor at each of its three possible values.");
w();
w("| Essay function | ≥50 | ≥60 | ≥70 | Cross-category pairs ≥50 |");
w("|---|---|---|---|---|");
for (const [label, fn] of [["unknown (today)", null], ["known, matches prompt", "match"], ["known, differs", "differ"]] as const) {
  let a50 = 0, a60 = 0, a70 = 0, cross = 0;
  for (const c of cases) {
    const essayFunction = fn === null ? null : fn === "match" ? (c.prompt.fn as never) : ("describe" === c.prompt.fn ? ("discuss-future-contribution" as never) : ("describe" as never));
    const r = scoreMatch({ ...input(c.essay, c.prompt), essayFunction });
    if (r.score >= 50) a50 += 1;
    if (r.score >= 60) a60 += 1;
    if (r.score >= 70) a70 += 1;
    if (r.score >= 50 && c.essay.primary !== c.prompt.primary) cross += 1;
  }
  w(`| ${label} | ${a50} (${((a50 / cases.length) * 100).toFixed(1)}%) | ${a60} (${((a60 / cases.length) * 100).toFixed(1)}%) | ${a70} (${((a70 / cases.length) * 100).toFixed(1)}%) | ${cross} |`);
}
w();
w("Note this script sets `essayFunction: null` throughout, modelling a newly");
w("written essay. The live path in reuse.ts supplies a function for essays already");
w("assigned to a prompt, so an established portfolio scores higher than this table");
w("shows - which is exactly why capturing it at creation matters.");
w();

writeFileSync("docs/evaluation/recommendation-cases.md", out.join("\n") + "\n");
console.log(`Wrote docs/evaluation/recommendation-cases.md (${cases.length} pairs)`);
